-- OAuth/OIDC dashboard login (PRD §10.2, §23.3; amendement n°30).
--
-- The identities table has existed since 00001 — one row per (provider,
-- subject) an account is linked to. What was missing is everything around it:
--
--   * oauth_provider_configs — the operator's client credentials, one row per
--     provider. The client secret follows the secret store (§23.2): envelope-
--     encrypted, AAD bound to the row uuid, never rendered back by the API.
--     A table rather than instance_settings columns: six providers with the
--     same shape is a relation, not twelve nullable singleton columns.
--
--   * oauth_login_states — the browser is away at the identity provider
--     between "authorize" and "callback". state (hashed: a database dump must
--     not let anyone complete a login), the PKCE verifier and the OIDC nonce
--     wait here, NOT in a cookie: a cookie-borne verifier dies on the
--     multi-replica deploys of ADR-021, and the DB row is what makes the
--     state single-use (DELETE ... RETURNING) instead of merely checked.

-- +goose Up
CREATE TABLE oauth_provider_configs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- Generated by the application before insert: the envelope AAD binds
    -- client_secret_enc to it.
    uuid uuid NOT NULL UNIQUE,
    provider oauth_provider NOT NULL UNIQUE,
    -- Sign-in button label; matters mostly for the generic 'oidc' provider
    -- ("Okta", "Keycloak"), where the enum value names nothing a user knows.
    display_name text,
    client_id text NOT NULL,
    client_secret_enc bytea NOT NULL,
    -- OpenID Connect discovery base, for the providers whose endpoints are
    -- not fixed ('oidc', 'azure' with its tenant). NULL for the rest.
    issuer_url text,
    -- Configured but disabled: the button disappears, the credentials stay.
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE oauth_login_states (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- SHA-256 of the state parameter the provider echoes on callback.
    state_hash text NOT NULL UNIQUE,
    provider oauth_provider NOT NULL,
    -- 'login' or 'link': an anonymous login round-trip must not be redeemable
    -- as "attach this identity to a signed-in account", nor the reverse.
    purpose text NOT NULL,
    -- The signed-in user a 'link' round-trip attaches to; NULL for a login.
    user_id bigint REFERENCES users (id) ON DELETE CASCADE,
    -- PKCE code_verifier (§23.3): stored server-side so the callback can
    -- prove to the provider that WE started this flow. Useless without the
    -- client secret, hence stored as-is.
    pkce_verifier text NOT NULL,
    -- OIDC nonce, expected back INSIDE the signed ID token.
    nonce text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

-- +goose Down
DROP TABLE oauth_login_states;
DROP TABLE oauth_provider_configs;
