// Central icon registry — the ONLY place lucide icons are imported. Icons are
// referenced everywhere else by their kebab-case name (the design kit's
// vocabulary), and this map is what keeps the bundle tree-shaken: an icon
// absent from this table does not ship.
import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  Bell,
  Box,
  Boxes,
  Cable,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleX,
  Clock,
  Copy,
  Cpu,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FolderGit2,
  GitBranch,
  Globe,
  HardDrive,
  Hash,
  Info,
  Key,
  KeyRound,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  Paintbrush,
  PanelLeft,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Sparkles,
  Square,
  SquareDashed,
  Terminal,
  Trash2,
  TriangleAlert,
  Upload,
  UserMinus,
  UserPlus,
  Users,
  Webhook,
  X,
  Zap,
  type LucideIconData,
} from 'lucide-angular';

export const ICONS: Record<string, LucideIconData> = {
  activity: Activity,
  'alert-triangle': TriangleAlert,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  bell: Bell,
  box: Box,
  boxes: Boxes,
  cable: Cable,
  check: Check,
  'check-circle': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  circle: Circle,
  'circle-x': CircleX,
  clock: Clock,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  'file-text': FileText,
  'folder-git-2': FolderGit2,
  'git-branch': GitBranch,
  globe: Globe,
  'hard-drive': HardDrive,
  hash: Hash,
  info: Info,
  key: Key,
  'key-round': KeyRound,
  'list-checks': ListChecks,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'message-square': MessageSquare,
  'more-horizontal': Ellipsis,
  paintbrush: Paintbrush,
  'panel-left': PanelLeft,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  logs: ScrollText,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  'settings-2': Settings2,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  square: Square,
  'square-dashed': SquareDashed,
  terminal: Terminal,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  webhook: Webhook,
  x: X,
  zap: Zap,
};
