package proxy

import (
	"strings"
	"testing"
)

func TestPriorityFormula(t *testing.T) {
	// §3.1: most specific path first, whatever the declaration order.
	cases := map[string]int{"/": 1, "/api": 1004, "/api/v2": 2007}
	for path, want := range cases {
		if got := Priority(path); got != want {
			t.Errorf("Priority(%q) = %d, want %d", path, got, want)
		}
	}
	if Priority("/api/v2") <= Priority("/api") || Priority("/api") <= Priority("/") {
		t.Fatal("specificity ordering broken")
	}
}

func TestGenerateDynamic(t *testing.T) {
	out := GenerateDynamic(RouteGroup{
		AppUUID:    "9f3c2a1e",
		ForceHTTPS: true,
		Routes: []Route{
			{FQDN: "app.example.com", Path: "/", TargetPort: 3000},
		},
	}, 41)

	for _, want := range []string{
		"# generated by AkerDock — revision 41 — DO NOT EDIT",
		"9f3c2a1e-r0-web:",
		"9f3c2a1e-r0:",
		"rule: Host(`app.example.com`) && PathPrefix(`/`)",
		"priority: 1",
		"middlewares: [9f3c2a1e-https-redirect]",
		"certResolver: http01",
		`url: "http://9f3c2a1e:3000"`,
		"redirectScheme:",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated file missing %q\n%s", want, out)
		}
	}
}

func TestGenerateWaker(t *testing.T) {
	// ADR-036: same hosts/priorities/TLS as the awake file, but services point
	// at the waker and each router stamps the wake header with the resource UUID.
	out := GenerateWaker(RouteGroup{
		AppUUID:    "9f3c2a1e",
		ForceHTTPS: true,
		Routes: []Route{
			{FQDN: "app.example.com", Path: "/", TargetPort: 3000},
		},
	}, "res-uuid-1234", 5)

	for _, want := range []string{
		"# generated by AkerDock — revision 5 — DO NOT EDIT",
		"9f3c2a1e-r0-web:",
		"9f3c2a1e-r0:",
		"rule: Host(`app.example.com`) && PathPrefix(`/`)",
		"service: 9f3c2a1e-waker",
		"9f3c2a1e-wake:",
		"X-AkerDock-Wake: \"res-uuid-1234\"",
		`url: "http://akerdock-waker:8080"`,
		"redirectScheme:",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated waker file missing %q\n%s", want, out)
		}
	}

	// The app's real container/port must NEVER appear: traffic goes to the waker.
	if strings.Contains(out, ":3000") {
		t.Errorf("waker file leaks the app target port\n%s", out)
	}
	// The websecure router must carry the wake middleware; the web router carries
	// the redirect (ForceHTTPS) instead, so the header is stamped post-redirect.
	if !strings.Contains(out, "middlewares: [9f3c2a1e-wake]") {
		t.Errorf("websecure router missing wake middleware\n%s", out)
	}
}

func TestGenerateWakerNoForceHTTPS(t *testing.T) {
	// Without ForceHTTPS the web router itself must carry the wake middleware,
	// otherwise a plain-HTTP first hit would never wake the target.
	out := GenerateWaker(RouteGroup{
		AppUUID: "abcd",
		Routes:  []Route{{FQDN: "x.example.com", Path: "/", TargetPort: 80}},
	}, "res-9", 1)
	if strings.Count(out, "middlewares: [abcd-wake]") != 2 {
		t.Errorf("both routers must carry the wake middleware when no redirect\n%s", out)
	}
}

func TestGenerateControlPlane(t *testing.T) {
	out := GenerateControlPlane("manager.example.com", 8080, 7)

	for _, want := range []string{
		"# generated by AkerDock — revision 7 — DO NOT EDIT",
		"00-control-plane-r0-web:",
		"00-control-plane-r0:",
		"rule: Host(`manager.example.com`) && PathPrefix(`/`)",
		"middlewares: [00-control-plane-https-redirect]",
		"certResolver: http01",
		`url: "http://host.docker.internal:8080"`,
		"redirectScheme:",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("control-plane file missing %q\n%s", want, out)
		}
	}
	// Idempotence matters: bootstrap compares this content with the last
	// applied revision to skip a no-op re-apply on every proxy start.
	if out != GenerateControlPlane("manager.example.com", 8080, 7) {
		t.Fatal("generation must be deterministic")
	}
}

func TestGenerateDynamicDeterministicOrder(t *testing.T) {
	rg := RouteGroup{AppUUID: "u", Routes: []Route{
		{FQDN: "b.example.com", Path: "/", TargetPort: 80},
		{FQDN: "a.example.com", Path: "/", TargetPort: 80},
	}}
	a := GenerateDynamic(rg, 1)
	rg.Routes[0], rg.Routes[1] = rg.Routes[1], rg.Routes[0]
	b := GenerateDynamic(rg, 1)
	if a != b {
		t.Fatal("generation must be deterministic regardless of declaration order")
	}
	if strings.Index(a, "a.example.com") > strings.Index(a, "b.example.com") {
		t.Fatal("routes must be sorted by (fqdn, path)")
	}
}
