// Package proxy implements the intermediate representation of
// docs/specs/proxy-contract.md and its Traefik generation (P0). The IR is
// provider-agnostic: priorities are computed here, never delegated to
// proxy heuristics (§3.1).
package proxy

import (
	"fmt"
	"net"
	"sort"
	"strconv"
	"strings"

	"github.com/deepteams/akerdock/internal/accessroute"
)

// Route is one (fqdn, path) → internal port HTTP route of a RouteGroup.
type Route struct {
	FQDN       string
	Path       string // normalized, starts with "/"
	TargetPort int    // internal container port
	// Endpoint overrides the group endpoint for this route: the container
	// of one compose component (compose-spec §6). Empty = group endpoint.
	Endpoint     string
	PublicRoutes []accessroute.Route
}

// AccessPolicy is the resource-wide wall attached to protected routers.
// PublicRoutes omit only this middleware; other route behavior is preserved.
type AccessPolicy struct {
	Mode           string // basic_auth | sso
	BasicAuthHash  string
	ForwardAuthURL string
	CallbackURL    string
	// CallbackPath is the reserved path whose reserved router proxies to the
	// control plane to mint the scoped cookie. Empty defaults to the
	// application callback (§4.1); an ingress endpoint (ADR-060) sets its own
	// so its cookie flow never collides with an application's.
	CallbackPath string
}

// accessCallbackPath returns the policy's callback path or the default.
func (p *AccessPolicy) accessCallbackPath() string {
	if p != nil && p.CallbackPath != "" {
		return p.CallbackPath
	}
	return "/.akerdock/app-callback"
}

// RouteGroup is the routing of one application (§2.3).
type RouteGroup struct {
	AppUUID string
	// WildcardDomain and DNSProvider describe the server's wildcard, when it
	// has one. With a DNSProvider, a route under the wildcard rides the single
	// DNS-01 wildcard certificate. Without one, the wildcard is only a naming
	// template: every route — under the wildcard or not — gets its own
	// per-router HTTP-01 certificate (§7.2), which is why the resolver choice
	// below checks BOTH fields.
	WildcardDomain string
	DNSProvider    string
	// Endpoint is the service target: the container name in the stable
	// form, or the candidate IP during a rolling switch (§7.2). Empty
	// defaults to the container name.
	Endpoint   string
	Routes     []Route
	ForceHTTPS bool
	Access     *AccessPolicy
	// Noindex answers every request with `X-Robots-Tag: noindex, nofollow`
	// (§4.7). Set on previews unconditionally — a preview is a copy of a site,
	// and an indexed copy competes with the original — and on production routes
	// when the resource asks for it.
	Noindex bool
	// IngressAttachPath, when set, emits one reserved high-priority router per
	// FQDN for the laptop attach WebSocket of an ingress endpoint (ADR-060 §2):
	// same service target and TLS, but NO access middleware — the attach
	// authenticates with its own single-use token, and a wall here would block
	// the CLI along with the visitors.
	IngressAttachPath string
}

// Priority implements the §3.1 formula: 1000 × segments(path) + len(path).
// The most specific path always wins, whatever the declaration order.
func Priority(path string) int {
	segments := 0
	for _, s := range strings.Split(path, "/") {
		if s != "" {
			segments++
		}
	}
	return 1000*segments + len(path)
}

// GenerateDynamic renders the per-application Traefik dynamic file
// (§5.3): deterministic router/service/middleware names derived from the
// application UUID (INV-011), routes sorted by (fqdn, path).
func GenerateDynamic(rg RouteGroup, revision int64) string {
	routes := append([]Route(nil), rg.Routes...)
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].FQDN != routes[j].FQDN {
			return routes[i].FQDN < routes[j].FQDN
		}
		return routes[i].Path < routes[j].Path
	})

	var b strings.Builder
	forceHTTPS := rg.ForceHTTPS || rg.Access != nil
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("http:\n  routers:\n")
	for n, route := range routes {
		rule := fmt.Sprintf("Host(`%s`) && PathPrefix(`%s`)", route.FQDN, route.Path)
		priority := Priority(route.Path)

		fmt.Fprintf(&b, "    %s-r%d-web:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [web]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		// A redirecting router answers 301 and never reaches the application:
		// its own response carries no content to keep out of an index.
		switch {
		case forceHTTPS:
			writeMiddlewares(&b, rg, "https-redirect")
		case rg.Noindex:
			writeMiddlewares(&b, rg, "noindex")
		}
		fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)

		fmt.Fprintf(&b, "    %s-r%d:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		writeMiddlewares(&b, rg, secureMiddlewares(rg)...)
		fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)
		writeTLS(&b, rg, route.FQDN)

		if rg.Access != nil {
			for publicN, public := range route.PublicRoutes {
				if !accessroute.Covers(route.Path, public) {
					continue
				}
				fmt.Fprintf(&b, "    %s-r%d-public-%d:\n", rg.AppUUID, n, publicN)
				b.WriteString("      entryPoints: [websecure]\n")
				fmt.Fprintf(&b, "      rule: Host(`%s`) && %s && %s\n", route.FQDN,
					accessroute.PathExpression(public), accessroute.MethodExpression(public.Methods))
				fmt.Fprintf(&b, "      priority: %d\n", publicPriority(route.Path))
				// A public exception drops the access wall and NOTHING else:
				// noindex still applies to it.
				if rg.Noindex {
					writeMiddlewares(&b, rg, "noindex")
				}
				fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)
				writeTLS(&b, rg, route.FQDN)
			}
		}
	}
	attach := ingressAttachTargets(rg, routes)
	writeAccessCallbackRouters(&b, rg, routes)
	writeIngressAttachRouters(&b, rg, attach)
	if forceHTTPS || rg.Access != nil || rg.Noindex {
		b.WriteString("  middlewares:\n")
	}
	if forceHTTPS {
		fmt.Fprintf(&b, "    %s-https-redirect:\n", rg.AppUUID)
		b.WriteString("      redirectScheme:\n        scheme: https\n        permanent: true\n")
	}
	writeAccessMiddleware(&b, rg)
	writeNoindexMiddleware(&b, rg)
	// One service per distinct target port. The contract's single-service
	// form (§5.1) holds when every route targets the same port; per-route
	// services keep domain:port targeting correct in the meantime.
	b.WriteString("  services:\n")
	for n, route := range routes {
		fmt.Fprintf(&b, "    %s-s%d:\n", rg.AppUUID, n)
		b.WriteString("      loadBalancer:\n        servers:\n")
		fmt.Fprintf(&b, "          - url: \"http://%s:%d\"\n", routeTarget(rg, route), route.TargetPort)
	}
	writeIngressAttachServices(&b, rg, attach)
	writeAccessCallbackService(&b, rg)
	return b.String()
}

// AgentContainerName is the server agent's container (ADR-056 — born as the
// scale-to-zero waker, ADR-036, it now carries the command channel, host-ops
// and builds): a mode of the AkerDock binary run from the same image, on the
// server's internal network, never published. Its waker module remains the
// reverse-proxy in front of every scale_to_zero resource.
const AgentContainerName = "akerdock-agent"

// LegacyAgentContainerName is the pre-rename container name (ADR-056). New
// agents carry it as a NETWORK ALIAS so scale-to-zero route files generated
// before the rename keep resolving; the ensure removes any container still
// bearing it when it creates the renamed one.
const LegacyAgentContainerName = "akerdock-waker"

// AgentPort is the internal HTTP port the agent's waker module listens on
// (§8.2).
const AgentPort = 8080

// WakeHeader is proxy-contract §8.2's request-tagging header. No Go code
// emits or reads it anymore — the agent's waker module routes by Host — but
// the name stays declared here as the contract's single source in code.
const WakeHeader = "X-AkerDock-Wake"

const accessCallbackPriority = 2_000_000

// IngressAttachPath is the reserved path a laptop dials to attach to an
// ingress endpoint (ADR-060 §2), on the endpoint's own FQDN. Same magnitude as
// the callback priority: both are exact-path rules that can never overlap.
const IngressAttachPath = "/.akerdock/ingress"

const ingressAttachPriority = 2_000_000

func publicPriority(basePath string) int {
	// Win over this route's protected router, but never over a more-specific
	// domain route (possibly owned by another resource on the same host).
	return Priority(basePath) + 1
}

func writeTLS(b *strings.Builder, rg RouteGroup, fqdn string) {
	if rg.DNSProvider != "" && underWildcard(fqdn, rg.WildcardDomain) {
		fmt.Fprintf(b, "      tls:\n        certResolver: %s\n", DNSResolverName(rg.DNSProvider))
		// One wildcard certificate covers every host under the domain.
		fmt.Fprintf(b, "        domains:\n          - main: %q\n            sans: [\"*.%s\"]\n", rg.WildcardDomain, rg.WildcardDomain)
		return
	}
	b.WriteString("      tls:\n        certResolver: http01\n")
}

// writeMiddlewares emits the middlewares line of a router, prefixing each
// suffix with the group scope: names are global to the proxy, so two resources
// sharing a bare `noindex` would fight over one definition.
func writeMiddlewares(b *strings.Builder, rg RouteGroup, suffixes ...string) {
	if len(suffixes) == 0 {
		return
	}
	names := make([]string, 0, len(suffixes))
	for _, s := range suffixes {
		names = append(names, rg.AppUUID+"-"+s)
	}
	fmt.Fprintf(b, "      middlewares: [%s]\n", strings.Join(names, ", "))
}

// secureMiddlewares is what every https router of the group carries, in the
// order they apply: the wall first — an unauthenticated request must not reach
// the application to collect a response header.
func secureMiddlewares(rg RouteGroup) []string {
	var names []string
	if rg.Access != nil {
		names = append(names, "access")
	}
	if rg.Noindex {
		names = append(names, "noindex")
	}
	return names
}

// writeNoindexMiddleware defines the response header keeping the group's
// domains out of search results. nofollow rides along: an indexed link found
// on a noindexed page puts the URL back in the index anyway.
func writeNoindexMiddleware(b *strings.Builder, rg RouteGroup) {
	if !rg.Noindex {
		return
	}
	fmt.Fprintf(b, "    %s-noindex:\n", rg.AppUUID)
	b.WriteString("      headers:\n        customResponseHeaders:\n          X-Robots-Tag: \"noindex, nofollow\"\n")
}

func writeAccessMiddleware(b *strings.Builder, rg RouteGroup) {
	if rg.Access == nil {
		return
	}
	switch rg.Access.Mode {
	case "basic_auth":
		fmt.Fprintf(b, "    %s-access:\n      basicAuth:\n        users:\n          - %q\n",
			rg.AppUUID, rg.Access.BasicAuthHash)
	case "sso":
		fmt.Fprintf(b, "    %s-access:\n      forwardAuth:\n        address: %q\n",
			rg.AppUUID, rg.Access.ForwardAuthURL)
	}
}

func writeAccessCallbackRouters(b *strings.Builder, rg RouteGroup, routes []Route) {
	if rg.Access == nil || rg.Access.Mode != "sso" || rg.Access.CallbackURL == "" {
		return
	}
	seen := map[string]struct{}{}
	callbackN := 0
	for _, route := range routes {
		if _, ok := seen[route.FQDN]; ok {
			continue
		}
		seen[route.FQDN] = struct{}{}
		fmt.Fprintf(b, "    %s-access-callback-%d:\n", rg.AppUUID, callbackN)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(b, "      rule: Host(`%s`) && Path(`%s`)\n", route.FQDN, rg.Access.accessCallbackPath())
		fmt.Fprintf(b, "      priority: %d\n", accessCallbackPriority)
		fmt.Fprintf(b, "      service: %s-access-callback\n", rg.AppUUID)
		writeTLS(b, rg, route.FQDN)
		callbackN++
	}
}

// ingressAttachTarget is one reserved attach router and the backend it serves:
// the FQDN it answers on, and the agent front that FQDN's first route points
// at. Computed once so the router and its service cannot disagree.
type ingressAttachTarget struct {
	fqdn     string
	endpoint string
	port     int
}

// ingressAttachTargets resolves one target per distinct FQDN, in the order of
// the already-sorted routes. The map is a dedupe set only — never iterated —
// so the output stays byte-stable across runs, which is what the checksum-based
// apply and the drift detection rest on (§6.2).
func ingressAttachTargets(rg RouteGroup, routes []Route) []ingressAttachTarget {
	if rg.IngressAttachPath == "" {
		return nil
	}
	seen := make(map[string]struct{}, len(routes))
	targets := make([]ingressAttachTarget, 0, len(routes))
	for _, route := range routes {
		if _, ok := seen[route.FQDN]; ok {
			continue
		}
		seen[route.FQDN] = struct{}{}
		targets = append(targets, ingressAttachTarget{
			fqdn: route.FQDN, endpoint: routeTarget(rg, route), port: route.TargetPort,
		})
	}
	return targets
}

// writeIngressAttachRouters emits the reserved attach router of an ingress
// group: one per distinct FQDN, on its own h2c service. Modeled on the callback
// routers and generated natively by the IR — never spliced into the YAML after
// the fact.
func writeIngressAttachRouters(b *strings.Builder, rg RouteGroup, targets []ingressAttachTarget) {
	for n, target := range targets {
		fmt.Fprintf(b, "    %s-ingress-attach-%d:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(b, "      rule: Host(`%s`) && Path(`%s`)\n", target.fqdn, rg.IngressAttachPath)
		fmt.Fprintf(b, "      priority: %d\n", ingressAttachPriority)
		fmt.Fprintf(b, "      service: %s-ingress-attach-%d\n", rg.AppUUID, n)
		writeTLS(b, rg, target.fqdn)
	}
}

// writeIngressAttachServices emits the attach path's own service, pointed at
// the same agent front as the visitor route but over **h2c** (ADR-063): the
// laptop's control and data requests then stay multiplexed on one connection
// all the way to the agent, with native full duplex, instead of being
// downgraded to one HTTP/1.1 connection per relayed stream.
//
// It is a separate service on purpose. The visitor routers keep their plain
// `http://` service, because `Connection` and `Upgrade` are invalid HTTP/2
// request headers (RFC 7540 §8.1.2.2) and Traefik performs no RFC 8441
// translation — an h2c backend hop would break every relayed WebSocket upgrade.
func writeIngressAttachServices(b *strings.Builder, rg RouteGroup, targets []ingressAttachTarget) {
	for n, target := range targets {
		fmt.Fprintf(b, "    %s-ingress-attach-%d:\n", rg.AppUUID, n)
		b.WriteString("      loadBalancer:\n        servers:\n")
		fmt.Fprintf(b, "          - url: \"h2c://%s:%d\"\n", target.endpoint, target.port)
	}
}

// routeTarget is the backend a route forwards to: its own endpoint (one
// compose component), else the group's, else the container named after the
// resource.
func routeTarget(rg RouteGroup, route Route) string {
	switch {
	case route.Endpoint != "":
		return route.Endpoint
	case rg.Endpoint != "":
		return rg.Endpoint
	default:
		return rg.AppUUID
	}
}

// IngressGroup is the routing of one declared ingress endpoint (ADR-060): a
// single stable FQDN, permanently pointed at the agent's HTTP front, walled
// per the endpoint's access mode, noindexed and HTTPS-forced unconditionally.
type IngressGroup struct {
	UUID           string
	FQDN           string
	WildcardDomain string
	DNSProvider    string
	Access         *AccessPolicy
}

// GenerateIngress renders the dynamic file of an ingress endpoint. The router
// exists from declaration on — attaching later touches no Traefik file, which
// is also what lets HTTP-01 issue the certificate while the URL still serves
// the agent's offline page.
func GenerateIngress(g IngressGroup, revision int64) string {
	return GenerateDynamic(RouteGroup{
		AppUUID:           g.UUID,
		WildcardDomain:    g.WildcardDomain,
		DNSProvider:       g.DNSProvider,
		Endpoint:          AgentContainerName,
		ForceHTTPS:        true,
		Noindex:           true,
		Access:            g.Access,
		IngressAttachPath: IngressAttachPath,
		Routes:            []Route{{FQDN: g.FQDN, Path: "/", TargetPort: AgentPort}},
	}, revision)
}

func writeAccessCallbackService(b *strings.Builder, rg RouteGroup) {
	if rg.Access == nil || rg.Access.Mode != "sso" || rg.Access.CallbackURL == "" {
		return
	}
	fmt.Fprintf(b, "    %s-access-callback:\n", rg.AppUUID)
	b.WriteString("      loadBalancer:\n        passHostHeader: false\n        servers:\n")
	fmt.Fprintf(b, "          - url: %q\n", rg.Access.CallbackURL)
}

// DNSResolverName is the deterministic name of a DNS-01 resolver (§7.2). One
// resolver per provider, named after it, so the dynamic files can reference it
// without knowing anything else about the server.
func DNSResolverName(provider string) string { return "dns01-" + provider }

// ControlPlaneScope is the reserved scope of the dynamic file routing the
// instance FQDN when the server hosts the instance (§1.3, PRD §14.2). Reserved
// means no application can ever claim it: scopes of applications are UUIDs.
const ControlPlaneScope = "00-control-plane"

// ControlPlaneHost is how the proxy container reaches the control plane
// process of its own host. It only resolves because the container is run with
// --add-host=host.docker.internal:host-gateway — the control plane is a
// compose service on another Docker network, unreachable by container name.
const ControlPlaneHost = "host.docker.internal"

// GenerateControlPlane renders the dynamic file serving the AkerDock
// dashboard behind the proxy with an automatic certificate (PRD §14.2), so
// the direct control-plane port can be closed to the outside. Always
// ForceHTTPS: a login page over clear HTTP is not an operator choice.
func GenerateControlPlane(fqdn string, port int, revision int64) string {
	return GenerateDynamic(RouteGroup{
		AppUUID:    ControlPlaneScope,
		Endpoint:   ControlPlaneHost,
		ForceHTTPS: true,
		Routes:     []Route{{FQDN: fqdn, Path: "/", TargetPort: port}},
	}, revision)
}

// TCPRoute exposes a database without publishing a port on its container
// (§2.6): the database never restarts to change its public port — the proxy
// does, which costs seconds and touches no data.
type TCPRoute struct {
	ResourceUUID string
	ListenPort   int
	TargetPort   int
}

// GenerateTCP renders the dynamic file of a TCP route (§5.6). HostSNI(`*`) is
// raw passthrough: the database's own TLS (§6.3) crosses untouched — the proxy
// must not terminate a connection whose certificate it does not own.
func GenerateTCP(t TCPRoute, revision int64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("tcp:\n  routers:\n")
	fmt.Fprintf(&b, "    %s-tcp:\n", t.ResourceUUID)
	fmt.Fprintf(&b, "      entryPoints: [%s]\n", TCPEntryPoint(t.ListenPort))
	b.WriteString("      rule: HostSNI(`*`)\n")
	fmt.Fprintf(&b, "      service: %s-tcp\n", t.ResourceUUID)
	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s-tcp:\n", t.ResourceUUID)
	b.WriteString("      loadBalancer:\n        servers:\n")
	fmt.Fprintf(&b, "          - address: \"%s:%d\"\n", t.ResourceUUID, t.TargetPort)
	return b.String()
}

// TCPEntryPoint is the deterministic name of the entrypoint a TCP route listens
// on (§5.2). Deterministic because the static config and the dynamic file are
// generated by different code paths, at different times: they can only agree if
// neither of them invents the name.
func TCPEntryPoint(port int) string { return fmt.Sprintf("tcp-%d", port) }

// GenerateStatic renders /var/lib/akerdock/proxy/traefik.yaml (§5.2). Any
// change to it requires recreating the proxy container (§1.4).
//
// dnsProvider is the Lego provider identifier of the server's DNS-01 credential
// (empty when the server issues no wildcard). The credential itself NEVER
// appears here: it lives in /var/lib/akerdock/proxy/acme.env (0600), injected into
// the container with --env-file, precisely so it cannot end up in a config file
// that is checksummed, stored as a revision and read back (INV-003).
//
// edgeTrustedIPs is the ADR-077 half of the relay that lives on the ORIGIN:
// the addresses of the server's designated edge, and nothing else. When set,
// the 443 entrypoint accepts PROXY protocol from them (the edge's TCP
// passthrough prepends it, or every wall decision and access log here would
// read the edge's LAN address as the visitor) and the 80 entrypoint trusts
// their X-Forwarded-* (that hop is plain HTTP reverse proxying). Addresses
// outside the list are never interpreted as either, so direct LAN traffic is
// untouched.
func GenerateStatic(httpPort, httpsPort int, acmeEmail, dnsProvider string, tcpPorts []int, edgeTrustedIPs []string, revision int64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("api:\n  dashboard: false\n  insecure: true\nping: {}\n\n")
	fmt.Fprintf(&b, "entryPoints:\n  web:\n    address: \":%d\"\n", httpPort)
	writeTrustedIPs(&b, "forwardedHeaders", edgeTrustedIPs)
	fmt.Fprintf(&b, "  websecure:\n    address: \":%d\"\n", httpsPort)
	writeTrustedIPs(&b, "proxyProtocol", edgeTrustedIPs)
	b.WriteString("    transport:\n      respondingTimeouts:\n        # Ingress HTTP/2 control and data requests are long-lived full-duplex\n        # streams. Traefik's 60 s default read timeout resets the whole tunnel.\n        readTimeout: 0s\n    http3: {}\n")
	// One entrypoint per TCP-proxied database. Traefik cannot add a listener at
	// runtime, which is exactly why the port lives here and not on the database
	// container: changing it recreates the PROXY (seconds, no data), not the
	// database (a restart, and every open connection dropped).
	ports := append([]int(nil), tcpPorts...)
	sort.Ints(ports)
	for _, p := range ports {
		fmt.Fprintf(&b, "  %s:\n    address: \":%d\"\n", TCPEntryPoint(p), p)
	}
	b.WriteString("\n")
	b.WriteString("providers:\n  file:\n    directory: /dynamic\n    watch: true\n\n")
	fmt.Fprintf(&b, "certificatesResolvers:\n  http01:\n    acme:\n      email: %q\n      storage: /acme/acme.json\n      httpChallenge:\n        entryPoint: web\n", acmeEmail)
	if dnsProvider != "" {
		fmt.Fprintf(&b, "  %s:\n    acme:\n      email: %q\n      storage: /acme/acme.json\n      dnsChallenge:\n        provider: %s\n", DNSResolverName(dnsProvider), acmeEmail, dnsProvider)
	}
	b.WriteString("\n")
	b.WriteString("log:\n  level: INFO\naccessLog: {}\n")
	return b.String()
}

// writeTrustedIPs emits an entrypoint-level trust stanza (ADR-077): kind is
// "proxyProtocol" (the 443 hop, raw TCP with a PROXY header) or
// "forwardedHeaders" (the 80 hop, plain HTTP with X-Forwarded-*).
func writeTrustedIPs(b *strings.Builder, kind string, ips []string) {
	if len(ips) == 0 {
		return
	}
	fmt.Fprintf(b, "    %s:\n      trustedIPs:\n", kind)
	for _, ip := range ips {
		fmt.Fprintf(b, "        - %q\n", ip)
	}
}

// EdgeScopePrefix is the reserved revision-scope prefix of the ADR-077 relay
// files an edge server carries — reserved the way ControlPlaneScope is:
// application scopes are bare UUIDs, so the prefix cannot collide.
const EdgeScopePrefix = "01-edge-"

// EdgeScope names the edge-side dynamic file relaying one origin server.
func EdgeScope(originServerUUID string) string { return EdgeScopePrefix + originServerUUID }

// GenerateEdge renders the relay file an edge server carries for ONE origin
// server (ADR-077): per public FQDN placed on the origin, a TCP router
// matching the SNI in the ClientHello — read in clear, before any
// cryptography, which is why the edge needs no certificate and no key — with
// `passthrough: true`, plus a plain HTTP router on 80 so ACME HTTP-01
// challenges and the origin's own HTTP→HTTPS redirect traverse. The TCP
// service prepends PROXY protocol v2, which the origin's entrypoints are
// configured to trust from this edge alone (GenerateStatic). The HTTP relay
// service is deliberately named exactly like the scope: the apply
// verification polls /api/http/services for the scope string, and TCP
// services are listed elsewhere.
func GenerateEdge(originServerUUID, originHost string, originHTTPPort, originHTTPSPort int, fqdns []string, revision int64) string {
	scope := EdgeScope(originServerUUID)
	sorted := append([]string(nil), fqdns...)
	sort.Strings(sorted)

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — edge relay for server %s (ADR-077) — revision %d — DO NOT EDIT\n",
		originServerUUID, revision)
	b.WriteString("http:\n  routers:\n")
	for n, fqdn := range sorted {
		fmt.Fprintf(&b, "    %s-r%d-web:\n", scope, n)
		b.WriteString("      entryPoints: [web]\n")
		fmt.Fprintf(&b, "      rule: Host(`%s`)\n", fqdn)
		fmt.Fprintf(&b, "      service: %s\n", scope)
	}
	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s:\n      loadBalancer:\n        servers:\n          - url: \"http://%s\"\n",
		scope, net.JoinHostPort(originHost, strconv.Itoa(originHTTPPort)))
	b.WriteString("tcp:\n  routers:\n")
	for n, fqdn := range sorted {
		fmt.Fprintf(&b, "    %s-r%d:\n", scope, n)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(&b, "      rule: HostSNI(`%s`)\n", fqdn)
		fmt.Fprintf(&b, "      service: %s-tls\n", scope)
		b.WriteString("      tls:\n        passthrough: true\n")
	}
	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s-tls:\n      loadBalancer:\n        proxyProtocol:\n          version: 2\n        servers:\n          - address: %q\n",
		scope, net.JoinHostPort(originHost, strconv.Itoa(originHTTPSPort)))
	return b.String()
}

// ContainerName is the managed proxy container (§1.3).
const ContainerName = "akerdock-proxy"

// Image is the Traefik version pinned by this AkerDock release (§1.3).
const Image = "traefik:v3.5"

// underWildcard reports whether fqdn is covered by *.domain — one level down,
// which is what a wildcard certificate actually covers. `a.b.example.com` is
// NOT covered by `*.example.com`, and issuing it as if it were would serve a
// certificate the browser rejects.
func underWildcard(fqdn, domain string) bool {
	if domain == "" || !strings.HasSuffix(fqdn, "."+domain) {
		return false
	}
	label := strings.TrimSuffix(fqdn, "."+domain)
	return label != "" && !strings.Contains(label, ".")
}
