// Package proxy implements the intermediate representation of
// docs/specs/proxy-contract.md and its Traefik generation (P0). The IR is
// provider-agnostic: priorities are computed here, never delegated to
// proxy heuristics (§3.1).
package proxy

import (
	"fmt"
	"sort"
	"strings"

	"github.com/deepteams/akerdock/internal/accessroute"
)

// Route is one (fqdn, path) → internal port HTTP route of a RouteGroup.
type Route struct {
	FQDN       string
	Path       string // normalized, starts with "/"
	TargetPort int    // internal container port
	// Endpoint overrides the group endpoint for this route: the container
	// of one compose component (compose-spec §6). Empty = group endpoint.
	Endpoint     string
	PublicRoutes []accessroute.Route
}

// AccessPolicy is the resource-wide wall attached to protected routers.
// PublicRoutes omit only this middleware; other route behavior is preserved.
type AccessPolicy struct {
	Mode           string // basic_auth | sso
	BasicAuthHash  string
	ForwardAuthURL string
	CallbackURL    string
}

// RouteGroup is the routing of one application (§2.3).
type RouteGroup struct {
	AppUUID string
	// WildcardDomain and DNSProvider describe the server's wildcard, when it
	// has one. With a DNSProvider, a route under the wildcard rides the single
	// DNS-01 wildcard certificate. Without one, the wildcard is only a naming
	// template: every route — under the wildcard or not — gets its own
	// per-router HTTP-01 certificate (§7.2), which is why the resolver choice
	// below checks BOTH fields.
	WildcardDomain string
	DNSProvider    string
	// Endpoint is the service target: the container name in the stable
	// form, or the candidate IP during a rolling switch (§7.2). Empty
	// defaults to the container name.
	Endpoint   string
	Routes     []Route
	ForceHTTPS bool
	Access     *AccessPolicy
}

// Priority implements the §3.1 formula: 1000 × segments(path) + len(path).
// The most specific path always wins, whatever the declaration order.
func Priority(path string) int {
	segments := 0
	for _, s := range strings.Split(path, "/") {
		if s != "" {
			segments++
		}
	}
	return 1000*segments + len(path)
}

// GenerateDynamic renders the per-application Traefik dynamic file
// (§5.3): deterministic router/service/middleware names derived from the
// application UUID (INV-011), routes sorted by (fqdn, path).
func GenerateDynamic(rg RouteGroup, revision int64) string {
	routes := append([]Route(nil), rg.Routes...)
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].FQDN != routes[j].FQDN {
			return routes[i].FQDN < routes[j].FQDN
		}
		return routes[i].Path < routes[j].Path
	})

	var b strings.Builder
	forceHTTPS := rg.ForceHTTPS || rg.Access != nil
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("http:\n  routers:\n")
	for n, route := range routes {
		rule := fmt.Sprintf("Host(`%s`) && PathPrefix(`%s`)", route.FQDN, route.Path)
		priority := Priority(route.Path)

		fmt.Fprintf(&b, "    %s-r%d-web:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [web]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		if forceHTTPS {
			fmt.Fprintf(&b, "      middlewares: [%s-https-redirect]\n", rg.AppUUID)
		}
		fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)

		fmt.Fprintf(&b, "    %s-r%d:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		if rg.Access != nil {
			fmt.Fprintf(&b, "      middlewares: [%s-access]\n", rg.AppUUID)
		}
		fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)
		writeTLS(&b, rg, route.FQDN)

		if rg.Access != nil {
			for publicN, public := range route.PublicRoutes {
				if !accessroute.Covers(route.Path, public) {
					continue
				}
				fmt.Fprintf(&b, "    %s-r%d-public-%d:\n", rg.AppUUID, n, publicN)
				b.WriteString("      entryPoints: [websecure]\n")
				fmt.Fprintf(&b, "      rule: Host(`%s`) && %s && %s\n", route.FQDN,
					accessroute.PathExpression(public), accessroute.MethodExpression(public.Methods))
				fmt.Fprintf(&b, "      priority: %d\n", publicPriority(route.Path))
				fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)
				writeTLS(&b, rg, route.FQDN)
			}
		}
	}
	writeAccessCallbackRouters(&b, rg, routes)
	if forceHTTPS || rg.Access != nil {
		b.WriteString("  middlewares:\n")
	}
	if forceHTTPS {
		fmt.Fprintf(&b, "    %s-https-redirect:\n", rg.AppUUID)
		b.WriteString("      redirectScheme:\n        scheme: https\n        permanent: true\n")
	}
	writeAccessMiddleware(&b, rg)
	// One service per distinct target port. The contract's single-service
	// form (§5.1) holds when every route targets the same port; per-route
	// services keep domain:port targeting correct in the meantime.
	endpoint := rg.Endpoint
	if endpoint == "" {
		endpoint = rg.AppUUID
	}
	b.WriteString("  services:\n")
	for n, route := range routes {
		target := endpoint
		if route.Endpoint != "" {
			target = route.Endpoint
		}
		fmt.Fprintf(&b, "    %s-s%d:\n", rg.AppUUID, n)
		b.WriteString("      loadBalancer:\n        servers:\n")
		fmt.Fprintf(&b, "          - url: \"http://%s:%d\"\n", target, route.TargetPort)
	}
	writeAccessCallbackService(&b, rg)
	return b.String()
}

// WakerContainerName is the scale-to-zero helper container (ADR-036, §8.1): a
// mode of the AkerDock binary run from the same image, on the server's internal
// network, never published. It is the reverse-proxy in front of every
// scale_to_zero resource — it wakes the target on the first request and dates
// activity for the control plane.
const WakerContainerName = "akerdock-waker"

// WakerPort is the internal HTTP port the waker listens on (§8.2).
const WakerPort = 8080

// WakeHeader carries the resource UUID from the dynamic file to the waker so it
// knows which container to start and forward to (§8.2). The waker's own routing
// table maps that UUID to the container and port; the proxy only tags the
// request.
const WakeHeader = "X-AkerDock-Wake"

// GenerateWaker renders the dynamic file of a scale-to-zero resource (ADR-036):
// same hosts, priorities and TLS as GenerateDynamic, but every service points at
// the waker and each router adds a middleware stamping WakeHeader with the
// resource UUID. Unlike proxy-contract §8.2's two-variant swap, this single
// file stays in place asleep OR awake — the waker forwards to the app when it is
// running and wakes it when it is stopped — so the waker sees all traffic and
// can measure inactivity without parsing access logs.
func GenerateWaker(rg RouteGroup, resourceUUID string, revision int64) string {
	routes := append([]Route(nil), rg.Routes...)
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].FQDN != routes[j].FQDN {
			return routes[i].FQDN < routes[j].FQDN
		}
		return routes[i].Path < routes[j].Path
	})

	wakeMW := rg.AppUUID + "-wake"
	forceHTTPS := rg.ForceHTTPS || rg.Access != nil

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("http:\n  routers:\n")
	for n, route := range routes {
		rule := fmt.Sprintf("Host(`%s`) && PathPrefix(`%s`)", route.FQDN, route.Path)
		priority := Priority(route.Path)

		fmt.Fprintf(&b, "    %s-r%d-web:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [web]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		if forceHTTPS {
			fmt.Fprintf(&b, "      middlewares: [%s-https-redirect]\n", rg.AppUUID)
		} else {
			fmt.Fprintf(&b, "      middlewares: [%s]\n", wakeMW)
		}
		fmt.Fprintf(&b, "      service: %s-waker\n", rg.AppUUID)

		fmt.Fprintf(&b, "    %s-r%d:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		protectedMiddlewares := []string{wakeMW}
		if rg.Access != nil {
			protectedMiddlewares = append(protectedMiddlewares, rg.AppUUID+"-access")
		}
		fmt.Fprintf(&b, "      middlewares: [%s]\n", strings.Join(protectedMiddlewares, ", "))
		fmt.Fprintf(&b, "      service: %s-waker\n", rg.AppUUID)
		writeTLS(&b, rg, route.FQDN)

		if rg.Access != nil {
			for publicN, public := range route.PublicRoutes {
				if !accessroute.Covers(route.Path, public) {
					continue
				}
				fmt.Fprintf(&b, "    %s-r%d-public-%d:\n", rg.AppUUID, n, publicN)
				b.WriteString("      entryPoints: [websecure]\n")
				fmt.Fprintf(&b, "      rule: Host(`%s`) && %s && %s\n", route.FQDN,
					accessroute.PathExpression(public), accessroute.MethodExpression(public.Methods))
				fmt.Fprintf(&b, "      priority: %d\n", publicPriority(route.Path))
				fmt.Fprintf(&b, "      middlewares: [%s]\n", wakeMW)
				fmt.Fprintf(&b, "      service: %s-waker\n", rg.AppUUID)
				writeTLS(&b, rg, route.FQDN)
			}
		}
	}
	writeAccessCallbackRouters(&b, rg, routes)

	b.WriteString("  middlewares:\n")
	fmt.Fprintf(&b, "    %s:\n", wakeMW)
	fmt.Fprintf(&b, "      headers:\n        customRequestHeaders:\n          %s: %q\n", WakeHeader, resourceUUID)
	if forceHTTPS {
		fmt.Fprintf(&b, "    %s-https-redirect:\n", rg.AppUUID)
		b.WriteString("      redirectScheme:\n        scheme: https\n        permanent: true\n")
	}
	writeAccessMiddleware(&b, rg)

	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s-waker:\n", rg.AppUUID)
	b.WriteString("      loadBalancer:\n        servers:\n")
	fmt.Fprintf(&b, "          - url: \"http://%s:%d\"\n", WakerContainerName, WakerPort)
	writeAccessCallbackService(&b, rg)
	return b.String()
}

const accessCallbackPriority = 2_000_000

func publicPriority(basePath string) int {
	// Win over this route's protected router, but never over a more-specific
	// domain route (possibly owned by another resource on the same host).
	return Priority(basePath) + 1
}

func writeTLS(b *strings.Builder, rg RouteGroup, fqdn string) {
	if rg.DNSProvider != "" && underWildcard(fqdn, rg.WildcardDomain) {
		fmt.Fprintf(b, "      tls:\n        certResolver: %s\n", DNSResolverName(rg.DNSProvider))
		// One wildcard certificate covers every host under the domain.
		fmt.Fprintf(b, "        domains:\n          - main: %q\n            sans: [\"*.%s\"]\n", rg.WildcardDomain, rg.WildcardDomain)
		return
	}
	b.WriteString("      tls:\n        certResolver: http01\n")
}

func writeAccessMiddleware(b *strings.Builder, rg RouteGroup) {
	if rg.Access == nil {
		return
	}
	switch rg.Access.Mode {
	case "basic_auth":
		fmt.Fprintf(b, "    %s-access:\n      basicAuth:\n        users:\n          - %q\n",
			rg.AppUUID, rg.Access.BasicAuthHash)
	case "sso":
		fmt.Fprintf(b, "    %s-access:\n      forwardAuth:\n        address: %q\n",
			rg.AppUUID, rg.Access.ForwardAuthURL)
	}
}

func writeAccessCallbackRouters(b *strings.Builder, rg RouteGroup, routes []Route) {
	if rg.Access == nil || rg.Access.Mode != "sso" || rg.Access.CallbackURL == "" {
		return
	}
	seen := map[string]struct{}{}
	callbackN := 0
	for _, route := range routes {
		if _, ok := seen[route.FQDN]; ok {
			continue
		}
		seen[route.FQDN] = struct{}{}
		fmt.Fprintf(b, "    %s-access-callback-%d:\n", rg.AppUUID, callbackN)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(b, "      rule: Host(`%s`) && Path(`/.akerdock/app-callback`)\n", route.FQDN)
		fmt.Fprintf(b, "      priority: %d\n", accessCallbackPriority)
		fmt.Fprintf(b, "      service: %s-access-callback\n", rg.AppUUID)
		writeTLS(b, rg, route.FQDN)
		callbackN++
	}
}

func writeAccessCallbackService(b *strings.Builder, rg RouteGroup) {
	if rg.Access == nil || rg.Access.Mode != "sso" || rg.Access.CallbackURL == "" {
		return
	}
	fmt.Fprintf(b, "    %s-access-callback:\n", rg.AppUUID)
	b.WriteString("      loadBalancer:\n        passHostHeader: false\n        servers:\n")
	fmt.Fprintf(b, "          - url: %q\n", rg.Access.CallbackURL)
}

// DNSResolverName is the deterministic name of a DNS-01 resolver (§7.2). One
// resolver per provider, named after it, so the dynamic files can reference it
// without knowing anything else about the server.
func DNSResolverName(provider string) string { return "dns01-" + provider }

// ControlPlaneScope is the reserved scope of the dynamic file routing the
// instance FQDN when the server hosts the instance (§1.3, PRD §14.2). Reserved
// means no application can ever claim it: scopes of applications are UUIDs.
const ControlPlaneScope = "00-control-plane"

// ControlPlaneHost is how the proxy container reaches the control plane
// process of its own host. It only resolves because the container is run with
// --add-host=host.docker.internal:host-gateway — the control plane is a
// compose service on another Docker network, unreachable by container name.
const ControlPlaneHost = "host.docker.internal"

// GenerateControlPlane renders the dynamic file serving the AkerDock
// dashboard behind the proxy with an automatic certificate (PRD §14.2), so
// the direct control-plane port can be closed to the outside. Always
// ForceHTTPS: a login page over clear HTTP is not an operator choice.
func GenerateControlPlane(fqdn string, port int, revision int64) string {
	return GenerateDynamic(RouteGroup{
		AppUUID:    ControlPlaneScope,
		Endpoint:   ControlPlaneHost,
		ForceHTTPS: true,
		Routes:     []Route{{FQDN: fqdn, Path: "/", TargetPort: port}},
	}, revision)
}

// TCPRoute exposes a database without publishing a port on its container
// (§2.6): the database never restarts to change its public port — the proxy
// does, which costs seconds and touches no data.
type TCPRoute struct {
	ResourceUUID string
	ListenPort   int
	TargetPort   int
}

// GenerateTCP renders the dynamic file of a TCP route (§5.6). HostSNI(`*`) is
// raw passthrough: the database's own TLS (§6.3) crosses untouched — the proxy
// must not terminate a connection whose certificate it does not own.
func GenerateTCP(t TCPRoute, revision int64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("tcp:\n  routers:\n")
	fmt.Fprintf(&b, "    %s-tcp:\n", t.ResourceUUID)
	fmt.Fprintf(&b, "      entryPoints: [%s]\n", TCPEntryPoint(t.ListenPort))
	b.WriteString("      rule: HostSNI(`*`)\n")
	fmt.Fprintf(&b, "      service: %s-tcp\n", t.ResourceUUID)
	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s-tcp:\n", t.ResourceUUID)
	b.WriteString("      loadBalancer:\n        servers:\n")
	fmt.Fprintf(&b, "          - address: \"%s:%d\"\n", t.ResourceUUID, t.TargetPort)
	return b.String()
}

// TCPEntryPoint is the deterministic name of the entrypoint a TCP route listens
// on (§5.2). Deterministic because the static config and the dynamic file are
// generated by different code paths, at different times: they can only agree if
// neither of them invents the name.
func TCPEntryPoint(port int) string { return fmt.Sprintf("tcp-%d", port) }

// GenerateStatic renders /var/lib/akerdock/proxy/traefik.yaml (§5.2). Any
// change to it requires recreating the proxy container (§1.4).
//
// dnsProvider is the Lego provider identifier of the server's DNS-01 credential
// (empty when the server issues no wildcard). The credential itself NEVER
// appears here: it lives in /var/lib/akerdock/proxy/acme.env (0600), injected into
// the container with --env-file, precisely so it cannot end up in a config file
// that is checksummed, stored as a revision and read back (INV-003).
func GenerateStatic(httpPort, httpsPort int, acmeEmail, dnsProvider string, tcpPorts []int, revision int64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("api:\n  dashboard: false\n  insecure: true\nping: {}\n\n")
	fmt.Fprintf(&b, "entryPoints:\n  web:\n    address: \":%d\"\n  websecure:\n    address: \":%d\"\n", httpPort, httpsPort)
	// One entrypoint per TCP-proxied database. Traefik cannot add a listener at
	// runtime, which is exactly why the port lives here and not on the database
	// container: changing it recreates the PROXY (seconds, no data), not the
	// database (a restart, and every open connection dropped).
	ports := append([]int(nil), tcpPorts...)
	sort.Ints(ports)
	for _, p := range ports {
		fmt.Fprintf(&b, "  %s:\n    address: \":%d\"\n", TCPEntryPoint(p), p)
	}
	b.WriteString("\n")
	b.WriteString("providers:\n  file:\n    directory: /dynamic\n    watch: true\n\n")
	fmt.Fprintf(&b, "certificatesResolvers:\n  http01:\n    acme:\n      email: %q\n      storage: /acme/acme.json\n      httpChallenge:\n        entryPoint: web\n", acmeEmail)
	if dnsProvider != "" {
		fmt.Fprintf(&b, "  %s:\n    acme:\n      email: %q\n      storage: /acme/acme.json\n      dnsChallenge:\n        provider: %s\n", DNSResolverName(dnsProvider), acmeEmail, dnsProvider)
	}
	b.WriteString("\n")
	b.WriteString("log:\n  level: INFO\naccessLog: {}\n")
	return b.String()
}

// ContainerName is the managed proxy container (§1.3).
const ContainerName = "akerdock-proxy"

// Image is the Traefik version pinned by this AkerDock release (§1.3).
const Image = "traefik:v3.5"

// underWildcard reports whether fqdn is covered by *.domain — one level down,
// which is what a wildcard certificate actually covers. `a.b.example.com` is
// NOT covered by `*.example.com`, and issuing it as if it were would serve a
// certificate the browser rejects.
func underWildcard(fqdn, domain string) bool {
	if domain == "" || !strings.HasSuffix(fqdn, "."+domain) {
		return false
	}
	label := strings.TrimSuffix(fqdn, "."+domain)
	return label != "" && !strings.Contains(label, ".")
}
