// Package proxy implements the intermediate representation of
// docs/specs/proxy-contract.md and its Traefik generation (P0). The IR is
// provider-agnostic: priorities are computed here, never delegated to
// proxy heuristics (§3.1).
package proxy

import (
	"fmt"
	"sort"
	"strings"
)

// Route is one (fqdn, path) → internal port HTTP route of a RouteGroup.
type Route struct {
	FQDN       string
	Path       string // normalized, starts with "/"
	TargetPort int    // internal container port
	// Endpoint overrides the group endpoint for this route: the container
	// of one compose component (compose-spec §6). Empty = group endpoint.
	Endpoint string
}

// RouteGroup is the routing of one application (§2.3).
type RouteGroup struct {
	AppUUID string
	// WildcardDomain and DNSProvider describe the server's wildcard, when it
	// has one. With a DNSProvider, a route under the wildcard rides the single
	// DNS-01 wildcard certificate. Without one, the wildcard is only a naming
	// template: every route — under the wildcard or not — gets its own
	// per-router HTTP-01 certificate (§7.2), which is why the resolver choice
	// below checks BOTH fields.
	WildcardDomain string
	DNSProvider    string
	// Endpoint is the service target: the container name in the stable
	// form, or the candidate IP during a rolling switch (§7.2). Empty
	// defaults to the container name.
	Endpoint   string
	Routes     []Route
	ForceHTTPS bool
}

// Priority implements the §3.1 formula: 1000 × segments(path) + len(path).
// The most specific path always wins, whatever the declaration order.
func Priority(path string) int {
	segments := 0
	for _, s := range strings.Split(path, "/") {
		if s != "" {
			segments++
		}
	}
	return 1000*segments + len(path)
}

// GenerateDynamic renders the per-application Traefik dynamic file
// (§5.3): deterministic router/service/middleware names derived from the
// application UUID (INV-011), routes sorted by (fqdn, path).
func GenerateDynamic(rg RouteGroup, revision int64) string {
	routes := append([]Route(nil), rg.Routes...)
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].FQDN != routes[j].FQDN {
			return routes[i].FQDN < routes[j].FQDN
		}
		return routes[i].Path < routes[j].Path
	})

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("http:\n  routers:\n")
	for n, route := range routes {
		rule := fmt.Sprintf("Host(`%s`) && PathPrefix(`%s`)", route.FQDN, route.Path)
		priority := Priority(route.Path)

		fmt.Fprintf(&b, "    %s-r%d-web:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [web]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		if rg.ForceHTTPS {
			fmt.Fprintf(&b, "      middlewares: [%s-https-redirect]\n", rg.AppUUID)
		}
		fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)

		fmt.Fprintf(&b, "    %s-r%d:\n", rg.AppUUID, n)
		b.WriteString("      entryPoints: [websecure]\n")
		fmt.Fprintf(&b, "      rule: %s\n", rule)
		fmt.Fprintf(&b, "      priority: %d\n", priority)
		fmt.Fprintf(&b, "      service: %s-s%d\n", rg.AppUUID, n)
		if rg.DNSProvider != "" && underWildcard(route.FQDN, rg.WildcardDomain) {
			fmt.Fprintf(&b, "      tls:\n        certResolver: %s\n", DNSResolverName(rg.DNSProvider))
			// One wildcard certificate covers every host under the domain: asking
			// per-host would issue one certificate per application and hit the
			// CA's rate limit for nothing.
			fmt.Fprintf(&b, "        domains:\n          - main: %q\n            sans: [\"*.%s\"]\n", rg.WildcardDomain, rg.WildcardDomain)
		} else {
			b.WriteString("      tls:\n        certResolver: http01\n")
		}
	}
	if rg.ForceHTTPS {
		b.WriteString("  middlewares:\n")
		fmt.Fprintf(&b, "    %s-https-redirect:\n", rg.AppUUID)
		b.WriteString("      redirectScheme:\n        scheme: https\n        permanent: true\n")
	}
	// One service per distinct target port. The contract's single-service
	// form (§5.1) holds when every route targets the same port; per-route
	// services keep domain:port targeting correct in the meantime.
	endpoint := rg.Endpoint
	if endpoint == "" {
		endpoint = rg.AppUUID
	}
	b.WriteString("  services:\n")
	for n, route := range routes {
		target := endpoint
		if route.Endpoint != "" {
			target = route.Endpoint
		}
		fmt.Fprintf(&b, "    %s-s%d:\n", rg.AppUUID, n)
		b.WriteString("      loadBalancer:\n        servers:\n")
		fmt.Fprintf(&b, "          - url: \"http://%s:%d\"\n", target, route.TargetPort)
	}
	return b.String()
}

// DNSResolverName is the deterministic name of a DNS-01 resolver (§7.2). One
// resolver per provider, named after it, so the dynamic files can reference it
// without knowing anything else about the server.
func DNSResolverName(provider string) string { return "dns01-" + provider }

// ControlPlaneScope is the reserved scope of the dynamic file routing the
// instance FQDN when the server hosts the instance (§1.3, PRD §14.2). Reserved
// means no application can ever claim it: scopes of applications are UUIDs.
const ControlPlaneScope = "00-control-plane"

// ControlPlaneHost is how the proxy container reaches the control plane
// process of its own host. It only resolves because the container is run with
// --add-host=host.docker.internal:host-gateway — the control plane is a
// compose service on another Docker network, unreachable by container name.
const ControlPlaneHost = "host.docker.internal"

// GenerateControlPlane renders the dynamic file serving the AkerDock
// dashboard behind the proxy with an automatic certificate (PRD §14.2), so
// the direct control-plane port can be closed to the outside. Always
// ForceHTTPS: a login page over clear HTTP is not an operator choice.
func GenerateControlPlane(fqdn string, port int, revision int64) string {
	return GenerateDynamic(RouteGroup{
		AppUUID:    ControlPlaneScope,
		Endpoint:   ControlPlaneHost,
		ForceHTTPS: true,
		Routes:     []Route{{FQDN: fqdn, Path: "/", TargetPort: port}},
	}, revision)
}

// TCPRoute exposes a database without publishing a port on its container
// (§2.6): the database never restarts to change its public port — the proxy
// does, which costs seconds and touches no data.
type TCPRoute struct {
	ResourceUUID string
	ListenPort   int
	TargetPort   int
}

// GenerateTCP renders the dynamic file of a TCP route (§5.6). HostSNI(`*`) is
// raw passthrough: the database's own TLS (§6.3) crosses untouched — the proxy
// must not terminate a connection whose certificate it does not own.
func GenerateTCP(t TCPRoute, revision int64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("tcp:\n  routers:\n")
	fmt.Fprintf(&b, "    %s-tcp:\n", t.ResourceUUID)
	fmt.Fprintf(&b, "      entryPoints: [%s]\n", TCPEntryPoint(t.ListenPort))
	b.WriteString("      rule: HostSNI(`*`)\n")
	fmt.Fprintf(&b, "      service: %s-tcp\n", t.ResourceUUID)
	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s-tcp:\n", t.ResourceUUID)
	b.WriteString("      loadBalancer:\n        servers:\n")
	fmt.Fprintf(&b, "          - address: \"%s:%d\"\n", t.ResourceUUID, t.TargetPort)
	return b.String()
}

// TCPEntryPoint is the deterministic name of the entrypoint a TCP route listens
// on (§5.2). Deterministic because the static config and the dynamic file are
// generated by different code paths, at different times: they can only agree if
// neither of them invents the name.
func TCPEntryPoint(port int) string { return fmt.Sprintf("tcp-%d", port) }

// GenerateStatic renders /var/lib/akerdock/proxy/traefik.yaml (§5.2). Any
// change to it requires recreating the proxy container (§1.4).
//
// dnsProvider is the Lego provider identifier of the server's DNS-01 credential
// (empty when the server issues no wildcard). The credential itself NEVER
// appears here: it lives in /var/lib/akerdock/proxy/acme.env (0600), injected into
// the container with --env-file, precisely so it cannot end up in a config file
// that is checksummed, stored as a revision and read back (INV-003).
func GenerateStatic(httpPort, httpsPort int, acmeEmail, dnsProvider string, tcpPorts []int, revision int64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by AkerDock — revision %d — DO NOT EDIT\n", revision)
	b.WriteString("api:\n  dashboard: false\n  insecure: true\nping: {}\n\n")
	fmt.Fprintf(&b, "entryPoints:\n  web:\n    address: \":%d\"\n  websecure:\n    address: \":%d\"\n", httpPort, httpsPort)
	// One entrypoint per TCP-proxied database. Traefik cannot add a listener at
	// runtime, which is exactly why the port lives here and not on the database
	// container: changing it recreates the PROXY (seconds, no data), not the
	// database (a restart, and every open connection dropped).
	ports := append([]int(nil), tcpPorts...)
	sort.Ints(ports)
	for _, p := range ports {
		fmt.Fprintf(&b, "  %s:\n    address: \":%d\"\n", TCPEntryPoint(p), p)
	}
	b.WriteString("\n")
	b.WriteString("providers:\n  file:\n    directory: /dynamic\n    watch: true\n\n")
	fmt.Fprintf(&b, "certificatesResolvers:\n  http01:\n    acme:\n      email: %q\n      storage: /acme/acme.json\n      httpChallenge:\n        entryPoint: web\n", acmeEmail)
	if dnsProvider != "" {
		fmt.Fprintf(&b, "  %s:\n    acme:\n      email: %q\n      storage: /acme/acme.json\n      dnsChallenge:\n        provider: %s\n", DNSResolverName(dnsProvider), acmeEmail, dnsProvider)
	}
	b.WriteString("\n")
	b.WriteString("log:\n  level: INFO\naccessLog: {}\n")
	return b.String()
}

// ContainerName is the managed proxy container (§1.3).
const ContainerName = "akerdock-proxy"

// Image is the Traefik version pinned by this AkerDock release (§1.3).
const Image = "traefik:v3.5"

// underWildcard reports whether fqdn is covered by *.domain — one level down,
// which is what a wildcard certificate actually covers. `a.b.example.com` is
// NOT covered by `*.example.com`, and issuing it as if it were would serve a
// certificate the browser rejects.
func underWildcard(fqdn, domain string) bool {
	if domain == "" || !strings.HasSuffix(fqdn, "."+domain) {
		return false
	}
	label := strings.TrimSuffix(fqdn, "."+domain)
	return label != "" && !strings.Contains(label, ".")
}
