// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironmentResources = `-- name: CountEnvironmentResources :one
SELECT count(*) FROM resources
WHERE environment_id = $1 AND deleted_at IS NULL
`

// How many deployable resources an environment covers — the weight behind
// "member on billing" in the per-member view.
func (q *Queries) CountEnvironmentResources(ctx context.Context, environmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentResources, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectResources = `-- name: CountProjectResources :one
SELECT count(*) FROM resources r
JOIN environments e ON e.id = r.environment_id
WHERE e.project_id = $1 AND r.deleted_at IS NULL
`

func (q *Queries) CountProjectResources(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectResources, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamResources = `-- name: CountTeamResources :one
SELECT count(*) FROM resources
WHERE team_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTeamResources(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamResources, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamMemberForAccess = `-- name: GetTeamMemberForAccess :one
SELECT m.role, u.uuid AS user_uuid, u.email, u.name, u.is_root,
       cr.uuid AS custom_role_uuid, cr.name AS custom_role_name,
       cr.permissions AS custom_permissions
FROM team_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
LEFT JOIN custom_roles cr ON cr.id = m.custom_role_id
WHERE m.team_id = $1 AND u.uuid = $2
`

type GetTeamMemberForAccessParams struct {
	TeamID int64
	Uuid   pgtype.UUID
}

type GetTeamMemberForAccessRow struct {
	Role              TeamRole
	UserUuid          pgtype.UUID
	Email             string
	Name              string
	IsRoot            bool
	CustomRoleUuid    pgtype.UUID
	CustomRoleName    *string
	CustomPermissions []string
}

func (q *Queries) GetTeamMemberForAccess(ctx context.Context, arg GetTeamMemberForAccessParams) (GetTeamMemberForAccessRow, error) {
	row := q.db.QueryRow(ctx, getTeamMemberForAccess, arg.TeamID, arg.Uuid)
	var i GetTeamMemberForAccessRow
	err := row.Scan(
		&i.Role,
		&i.UserUuid,
		&i.Email,
		&i.Name,
		&i.IsRoot,
		&i.CustomRoleUuid,
		&i.CustomRoleName,
		&i.CustomPermissions,
	)
	return i, err
}

const listApiTokensForAccess = `-- name: ListApiTokensForAccess :many
SELECT t.uuid, t.name, t.permissions, t.expires_at, t.last_used_at,
       u.uuid AS creator_uuid, u.email AS creator_email
FROM api_tokens t
LEFT JOIN users u ON u.id = t.created_by
WHERE t.team_id = $1
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
ORDER BY t.id DESC
`

type ListApiTokensForAccessRow struct {
	Uuid         pgtype.UUID
	Name         string
	Permissions  []string
	ExpiresAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	CreatorUuid  pgtype.UUID
	CreatorEmail *string
}

// Live tokens with their creator: a token's reach is its creator's (ADR-046
// §7), so the creator is who an operator talks to about it. Revoked and expired
// tokens are excluded — they grant nothing, and a review crowded with dead rows
// is a review nobody finishes.
func (q *Queries) ListApiTokensForAccess(ctx context.Context, teamID int64) ([]ListApiTokensForAccessRow, error) {
	rows, err := q.db.Query(ctx, listApiTokensForAccess, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiTokensForAccessRow
	for rows.Next() {
		var i ListApiTokensForAccessRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatorUuid,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceRootsForAccess = `-- name: ListInstanceRootsForAccess :many
SELECT u.uuid, u.email, u.name
FROM users u
WHERE u.is_root AND u.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM team_memberships m WHERE m.user_id = u.id AND m.team_id = $1
  )
ORDER BY u.email
`

type ListInstanceRootsForAccessRow struct {
	Uuid  pgtype.UUID
	Email string
	Name  string
}

// Instance roots that are NOT members of this team: they reach it all the same
// (rbac-matrix §3.9), and a view that omits them lies by exactly the account an
// auditor asks about first.
func (q *Queries) ListInstanceRootsForAccess(ctx context.Context, teamID int64) ([]ListInstanceRootsForAccessRow, error) {
	rows, err := q.db.Query(ctx, listInstanceRootsForAccess, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstanceRootsForAccessRow
	for rows.Next() {
		var i ListInstanceRootsForAccessRow
		if err := rows.Scan(&i.Uuid, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersForAccess = `-- name: ListTeamMembersForAccess :many

SELECT m.role, u.uuid AS user_uuid, u.email, u.name, u.is_root,
       cr.uuid AS custom_role_uuid, cr.name AS custom_role_name,
       cr.permissions AS custom_permissions
FROM team_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
LEFT JOIN custom_roles cr ON cr.id = m.custom_role_id
WHERE m.team_id = $1
ORDER BY u.email
`

type ListTeamMembersForAccessRow struct {
	Role              TeamRole
	UserUuid          pgtype.UUID
	Email             string
	Name              string
	IsRoot            bool
	CustomRoleUuid    pgtype.UUID
	CustomRoleName    *string
	CustomPermissions []string
}

// Access review (ADR-046 §9): the subjects holding platform permissions on a
// resource. Read-only and deliberately un-cached — a denormalized copy of
// who-can-see-what drifts from the rules it summarizes, and a review reading a
// stale copy asserts a safety nobody verified.
// Every member with the material needed to resolve what they hold: the system
// role, the custom role's permissions when one overrides it, and the instance
// root flag (a root reaches everything and must not be silently absent).
func (q *Queries) ListTeamMembersForAccess(ctx context.Context, teamID int64) ([]ListTeamMembersForAccessRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersForAccess, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersForAccessRow
	for rows.Next() {
		var i ListTeamMembersForAccessRow
		if err := rows.Scan(
			&i.Role,
			&i.UserUuid,
			&i.Email,
			&i.Name,
			&i.IsRoot,
			&i.CustomRoleUuid,
			&i.CustomRoleName,
			&i.CustomPermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
