// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adoptionscans.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearResourceAdoption = `-- name: ClearResourceAdoption :exec
UPDATE resources
SET adoption = NULL, updated_at = now()
WHERE id = $1
`

// The normalizing deployment converged the remote objects onto the
// uuid-derived names (§20.7): the pointer is obsolete, the history stays.
func (q *Queries) ClearResourceAdoption(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearResourceAdoption, id)
	return err
}

const completeAdoptionScan = `-- name: CompleteAdoptionScan :exec
UPDATE adoption_scans
SET status = 'completed', candidates = $2, completed_at = now()
WHERE id = $1
`

type CompleteAdoptionScanParams struct {
	ID         int64
	Candidates []byte
}

func (q *Queries) CompleteAdoptionScan(ctx context.Context, arg CompleteAdoptionScanParams) error {
	_, err := q.db.Exec(ctx, completeAdoptionScan, arg.ID, arg.Candidates)
	return err
}

const createAdoptionScan = `-- name: CreateAdoptionScan :one

INSERT INTO adoption_scans (uuid, team_id, server_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, team_id, server_id, status, error, candidates, created_by, created_at, completed_at
`

type CreateAdoptionScanParams struct {
	Uuid      pgtype.UUID
	TeamID    int64
	ServerID  int64
	CreatedBy *int64
}

// Adoption scans (PRD §20.7, ADR-013/ADR-023).
func (q *Queries) CreateAdoptionScan(ctx context.Context, arg CreateAdoptionScanParams) (AdoptionScan, error) {
	row := q.db.QueryRow(ctx, createAdoptionScan,
		arg.Uuid,
		arg.TeamID,
		arg.ServerID,
		arg.CreatedBy,
	)
	var i AdoptionScan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.ServerID,
		&i.Status,
		&i.Error,
		&i.Candidates,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failAdoptionScan = `-- name: FailAdoptionScan :exec
UPDATE adoption_scans
SET status = 'failed', error = $2, completed_at = now()
WHERE id = $1
`

type FailAdoptionScanParams struct {
	ID    int64
	Error *string
}

func (q *Queries) FailAdoptionScan(ctx context.Context, arg FailAdoptionScanParams) error {
	_, err := q.db.Exec(ctx, failAdoptionScan, arg.ID, arg.Error)
	return err
}

const getAdoptionScanByID = `-- name: GetAdoptionScanByID :one
SELECT id, uuid, team_id, server_id, status, error, candidates, created_by, created_at, completed_at FROM adoption_scans WHERE id = $1
`

func (q *Queries) GetAdoptionScanByID(ctx context.Context, id int64) (AdoptionScan, error) {
	row := q.db.QueryRow(ctx, getAdoptionScanByID, id)
	var i AdoptionScan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.ServerID,
		&i.Status,
		&i.Error,
		&i.Candidates,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAdoptionScanByUUIDForTeam = `-- name: GetAdoptionScanByUUIDForTeam :one
SELECT sc.id, sc.uuid, sc.team_id, sc.server_id, sc.status, sc.error, sc.candidates, sc.created_by, sc.created_at, sc.completed_at, s.uuid AS server_uuid
FROM adoption_scans sc
JOIN servers s ON s.id = sc.server_id
WHERE sc.uuid = $1 AND sc.team_id = $2 AND s.deleted_at IS NULL
`

type GetAdoptionScanByUUIDForTeamParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

type GetAdoptionScanByUUIDForTeamRow struct {
	AdoptionScan AdoptionScan
	ServerUuid   pgtype.UUID
}

func (q *Queries) GetAdoptionScanByUUIDForTeam(ctx context.Context, arg GetAdoptionScanByUUIDForTeamParams) (GetAdoptionScanByUUIDForTeamRow, error) {
	row := q.db.QueryRow(ctx, getAdoptionScanByUUIDForTeam, arg.Uuid, arg.TeamID)
	var i GetAdoptionScanByUUIDForTeamRow
	err := row.Scan(
		&i.AdoptionScan.ID,
		&i.AdoptionScan.Uuid,
		&i.AdoptionScan.TeamID,
		&i.AdoptionScan.ServerID,
		&i.AdoptionScan.Status,
		&i.AdoptionScan.Error,
		&i.AdoptionScan.Candidates,
		&i.AdoptionScan.CreatedBy,
		&i.AdoptionScan.CreatedAt,
		&i.AdoptionScan.CompletedAt,
		&i.ServerUuid,
	)
	return i, err
}

const getEnvironmentByUUIDForTeam = `-- name: GetEnvironmentByUUIDForTeam :one
SELECT e.id, e.uuid, e.project_id, e.name, e.slug, e.description, e.created_by, e.updated_by, e.created_at, e.updated_at, e.deleted_at, e.version FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.uuid = $1 AND p.team_id = $2
  AND e.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetEnvironmentByUUIDForTeamParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

// Adoption targets an environment across projects: team isolation only
// (INV-002).
func (q *Queries) GetEnvironmentByUUIDForTeam(ctx context.Context, arg GetEnvironmentByUUIDForTeamParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByUUIDForTeam, arg.Uuid, arg.TeamID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listAdoptionScansForServer = `-- name: ListAdoptionScansForServer :many
SELECT id, uuid, team_id, server_id, status, error, candidates, created_by, created_at, completed_at FROM adoption_scans
WHERE server_id = $1
  AND ($2::bigint IS NULL OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListAdoptionScansForServerParams struct {
	ServerID  int64
	BeforeID  *int64
	PageLimit int32
}

func (q *Queries) ListAdoptionScansForServer(ctx context.Context, arg ListAdoptionScansForServerParams) ([]AdoptionScan, error) {
	rows, err := q.db.Query(ctx, listAdoptionScansForServer, arg.ServerID, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdoptionScan
	for rows.Next() {
		var i AdoptionScan
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.ServerID,
			&i.Status,
			&i.Error,
			&i.Candidates,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveResourceUUIDs = `-- name: ListLiveResourceUUIDs :many
SELECT uuid FROM resources
WHERE uuid = ANY ($1::uuid[]) AND deleted_at IS NULL
`

// Scan exclusion (INV-015): "managed" means tracked by a live row, not just
// labelled — a disowned resource keeps its labels but is adoptable again.
func (q *Queries) ListLiveResourceUUIDs(ctx context.Context, uuids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listLiveResourceUUIDs, uuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var uuid pgtype.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdoptionScanRunning = `-- name: SetAdoptionScanRunning :exec
UPDATE adoption_scans SET status = 'running' WHERE id = $1
`

func (q *Queries) SetAdoptionScanRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setAdoptionScanRunning, id)
	return err
}

const setResourceAdoption = `-- name: SetResourceAdoption :exec
UPDATE resources
SET adopted_at = now(), adoption = $2, updated_at = now()
WHERE id = $1
`

type SetResourceAdoptionParams struct {
	ID       int64
	Adoption []byte
}

// Marks a resource as adopted and not yet normalized: the JSONB points at
// the real remote objects (container name, compose project).
func (q *Queries) SetResourceAdoption(ctx context.Context, arg SetResourceAdoptionParams) error {
	_, err := q.db.Exec(ctx, setResourceAdoption, arg.ID, arg.Adoption)
	return err
}
