// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUnpublishedOutboxEvents = `-- name: ClaimUnpublishedOutboxEvents :many

UPDATE outbox_events SET published_at = now(), publish_attempts = publish_attempts + 1
WHERE id IN (
    SELECT id FROM outbox_events
    WHERE published_at IS NULL
    ORDER BY id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, uuid, event_type, occurred_at, team_uuid, resource_uuid, actor, correlation_id, aggregate_key, payload, published_at, publish_attempts, created_at
`

// Outbox publisher (§18.2, §24.2): events are published in commit order.
func (q *Queries) ClaimUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EventType,
			&i.OccurredAt,
			&i.TeamUuid,
			&i.ResourceUuid,
			&i.Actor,
			&i.CorrelationID,
			&i.AggregateKey,
			&i.Payload,
			&i.PublishedAt,
			&i.PublishAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec

INSERT INTO audit_events (team_id, actor_kind, actor_uuid, actor_display, action, target_kind, target_uuid, target_name, result, ip, user_agent, request_id, correlation_id, diff_redacted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $13, $8, $9, $10, $11, $12, $14)
`

type InsertAuditEventParams struct {
	TeamID        *int64
	ActorKind     ActorKind
	ActorUuid     pgtype.UUID
	ActorDisplay  *string
	Action        string
	TargetKind    *string
	TargetUuid    pgtype.UUID
	Result        AuditResult
	Ip            *netip.Addr
	UserAgent     *string
	RequestID     pgtype.UUID
	CorrelationID pgtype.UUID
	TargetName    *string
	DiffRedacted  []byte
}

// Audit log (§23.4): strictly append-only — no UPDATE or single DELETE
// query must ever exist against this table.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.TeamID,
		arg.ActorKind,
		arg.ActorUuid,
		arg.ActorDisplay,
		arg.Action,
		arg.TargetKind,
		arg.TargetUuid,
		arg.Result,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
		arg.CorrelationID,
		arg.TargetName,
		arg.DiffRedacted,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (uuid, event_type, team_uuid, resource_uuid, actor, aggregate_key, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOutboxEventParams struct {
	Uuid         pgtype.UUID
	EventType    string
	TeamUuid     pgtype.UUID
	ResourceUuid pgtype.UUID
	Actor        []byte
	AggregateKey *string
	Payload      []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.Uuid,
		arg.EventType,
		arg.TeamUuid,
		arg.ResourceUuid,
		arg.Actor,
		arg.AggregateKey,
		arg.Payload,
	)
	return err
}

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT id, uuid, occurred_at, team_id, actor_kind, actor_uuid, actor_display, action, target_kind, target_uuid, result, ip, user_agent, request_id, correlation_id, diff_redacted, created_at, target_name FROM audit_events
WHERE team_id = $1
  AND ($2::bigint = 0 OR id < $2)
  AND ($3::text IS NULL OR action = $3)
  -- A feature's trail spans several action names (open, close, grant, revoke),
  -- so the prefix filter is a list: one story rather than four partial lists.
  AND ($4::text[] IS NULL
       OR action LIKE ANY (SELECT p || '%' FROM unnest($4::text[]) AS p))
  AND ($5::audit_result IS NULL OR result = $5)
  AND ($6::uuid IS NULL OR actor_uuid = $6)
  AND ($7::uuid IS NULL OR target_uuid = $7)
  AND ($8::timestamptz IS NULL OR occurred_at >= $8)
  AND ($9::timestamptz IS NULL OR occurred_at <= $9)
ORDER BY id DESC
LIMIT $10
`

type ListAuditEventsPageParams struct {
	TeamID         *int64
	AfterID        int64
	Action         *string
	ActionPrefixes []string
	Result         *AuditResult
	ActorUuid      pgtype.UUID
	TargetUuid     pgtype.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

// Read side of the audit trail (§23.4: paginé, filtrable, exportable). A SELECT
// does not violate the append-only rule. Team-scoped; optional filters on action,
// result, actor, target and an occurred_at window; cursor by descending id.
func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsPage,
		arg.TeamID,
		arg.AfterID,
		arg.Action,
		arg.ActionPrefixes,
		arg.Result,
		arg.ActorUuid,
		arg.TargetUuid,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OccurredAt,
			&i.TeamID,
			&i.ActorKind,
			&i.ActorUuid,
			&i.ActorDisplay,
			&i.Action,
			&i.TargetKind,
			&i.TargetUuid,
			&i.Result,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.CorrelationID,
			&i.DiffRedacted,
			&i.CreatedAt,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceAuditEventsPage = `-- name: ListInstanceAuditEventsPage :many
SELECT id, uuid, occurred_at, team_id, actor_kind, actor_uuid, actor_display, action, target_kind, target_uuid, result, ip, user_agent, request_id, correlation_id, diff_redacted, created_at, target_name FROM audit_events
WHERE ($1::bigint = 0 OR id < $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::audit_result IS NULL OR result = $3)
  AND ($4::uuid IS NULL OR actor_uuid = $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR occurred_at <= $6)
ORDER BY id DESC
LIMIT $7
`

type ListInstanceAuditEventsPageParams struct {
	AfterID   int64
	Action    *string
	Result    *AuditResult
	ActorUuid pgtype.UUID
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
	PageLimit int32
}

// Instance-wide audit (reserved to the instance root): every team AND the
// system/instance actions that have no team_id (encryption rotation, instance
// settings…), which no team-scoped view can show. Same optional filters.
func (q *Queries) ListInstanceAuditEventsPage(ctx context.Context, arg ListInstanceAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listInstanceAuditEventsPage,
		arg.AfterID,
		arg.Action,
		arg.Result,
		arg.ActorUuid,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OccurredAt,
			&i.TeamID,
			&i.ActorKind,
			&i.ActorUuid,
			&i.ActorDisplay,
			&i.Action,
			&i.TargetKind,
			&i.TargetUuid,
			&i.Result,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.CorrelationID,
			&i.DiffRedacted,
			&i.CreatedAt,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxEventsForTeamAfter = `-- name: ListOutboxEventsForTeamAfter :many
SELECT id, uuid, event_type, occurred_at, team_uuid, resource_uuid, actor, correlation_id, aggregate_key, payload, published_at, publish_attempts, created_at FROM outbox_events
WHERE team_uuid = $1 AND id > $2 AND published_at IS NOT NULL
ORDER BY id
LIMIT $3
`

type ListOutboxEventsForTeamAfterParams struct {
	TeamUuid pgtype.UUID
	ID       int64
	Limit    int32
}

func (q *Queries) ListOutboxEventsForTeamAfter(ctx context.Context, arg ListOutboxEventsForTeamAfterParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsForTeamAfter, arg.TeamUuid, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EventType,
			&i.OccurredAt,
			&i.TeamUuid,
			&i.ResourceUuid,
			&i.Actor,
			&i.CorrelationID,
			&i.AggregateKey,
			&i.Payload,
			&i.PublishedAt,
			&i.PublishAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditEvents = `-- name: PurgeAuditEvents :one
SELECT purge_audit_events($1::integer)
`

// Retention purge (§23.4): removes audit rows older than retention_days. Goes
// through the SQL function (not a direct DELETE) — the function is the only
// sanctioned path past the append-only trigger, and it caps the deletion to
// aged-out rows. retention_days <= 0 keeps everything. Returns rows removed.
func (q *Queries) PurgeAuditEvents(ctx context.Context, retentionDays int32) (int64, error) {
	row := q.db.QueryRow(ctx, purgeAuditEvents, retentionDays)
	var purge_audit_events int64
	err := row.Scan(&purge_audit_events)
	return purge_audit_events, err
}

const purgePublishedOutboxEvents = `-- name: PurgePublishedOutboxEvents :execrows
DELETE FROM outbox_events
WHERE published_at IS NOT NULL AND published_at < now() - interval '7 days'
  AND id <= (SELECT last_outbox_event_id FROM notification_cursor)
`

// Never purge past the notification cursor: an event the dispatcher has not
// read yet would be a notification silently lost (the 7-day window makes this
// unlikely, not impossible — a long outage is exactly when alerts matter).
func (q *Queries) PurgePublishedOutboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgePublishedOutboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveAuditTargetName = `-- name: ResolveAuditTargetName :one
SELECT name FROM (
    SELECT resources.name FROM resources
        WHERE resources.uuid = $1 AND $2::text IN ('application', 'database', 'service', 'resource', 'preview')
    UNION ALL SELECT servers.name FROM servers
        WHERE servers.uuid = $1 AND $2::text = 'server'
    UNION ALL SELECT projects.name FROM projects
        WHERE projects.uuid = $1 AND $2::text = 'project'
    UNION ALL SELECT environments.name FROM environments
        WHERE environments.uuid = $1 AND $2::text = 'environment'
    UNION ALL SELECT teams.name FROM teams
        WHERE teams.uuid = $1 AND $2::text = 'team'
    UNION ALL SELECT users.name FROM users
        WHERE users.uuid = $1 AND $2::text = 'user'
    UNION ALL SELECT notification_channels.name FROM notification_channels
        WHERE notification_channels.uuid = $1 AND $2::text = 'notification_channel'
    UNION ALL SELECT scheduled_tasks.name FROM scheduled_tasks
        WHERE scheduled_tasks.uuid = $1 AND $2::text = 'scheduled_task'
    UNION ALL SELECT custom_roles.name FROM custom_roles
        WHERE custom_roles.uuid = $1 AND $2::text = 'role'
    UNION ALL SELECT registry_credentials.name FROM registry_credentials
        WHERE registry_credentials.uuid = $1 AND $2::text = 'registry_credential'
    UNION ALL SELECT cloud_credentials.name FROM cloud_credentials
        WHERE cloud_credentials.uuid = $1 AND $2::text = 'dns_credential'
    UNION ALL SELECT github_apps.name FROM github_apps
        WHERE github_apps.uuid = $1 AND $2::text = 'github_app'
    UNION ALL SELECT uptime_checks.name FROM uptime_checks
        WHERE uptime_checks.uuid = $1 AND $2::text = 'uptime_check'
    UNION ALL SELECT api_tokens.name FROM api_tokens
        WHERE api_tokens.uuid = $1 AND $2::text = 'api_token'
    UNION ALL SELECT scim_tokens.name FROM scim_tokens
        WHERE scim_tokens.uuid = $1 AND $2::text = 'scim_token'
    UNION ALL SELECT external_endpoints.name FROM external_endpoints
        WHERE external_endpoints.uuid = $1 AND $2::text = 'external_endpoint'
    UNION ALL SELECT service_components.name FROM service_components
        WHERE service_components.uuid = $1 AND $2::text = 'service_component'
    UNION ALL SELECT private_keys.name FROM private_keys
        WHERE private_keys.uuid = $1 AND $2::text = 'private_key'
    UNION ALL SELECT git_sources.name FROM git_sources
        WHERE git_sources.uuid = $1 AND $2::text IN ('git_source', 'source')
    UNION ALL SELECT s3_storages.name FROM s3_storages
        WHERE s3_storages.uuid = $1 AND $2::text IN ('s3_storage', 'storage')
    -- An invitation has no name; the invited address is what a reader needs.
    UNION ALL SELECT invitations.email::text AS name FROM invitations
        WHERE invitations.uuid = $1 AND $2::text = 'invitation'
) AS candidates
LIMIT 1
`

type ResolveAuditTargetNameParams struct {
	TargetUuid pgtype.UUID
	TargetKind string
}

// The display name of what an action touched, read at the moment it is audited
// so the trail keeps the name the resource had THEN (see 00084).
//
// One statement rather than fifteen: each branch is gated by the target kind, so
// PostgreSQL discards the others on a constant one-time filter and only the
// matching table is probed, by its unique index on uuid. Best-effort by
// construction — an unknown kind or a row already gone simply yields nothing,
// and the trail keeps the uuid it already has.
func (q *Queries) ResolveAuditTargetName(ctx context.Context, arg ResolveAuditTargetNameParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveAuditTargetName, arg.TargetUuid, arg.TargetKind)
	var name string
	err := row.Scan(&name)
	return name, err
}
