// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package store

import (
	"context"
)

const countUsers = `-- name: CountUsers :one

SELECT count(*) FROM users
`

// Queries used by the startup sequence (instance-config §6).
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocalhostServerIfAbsent = `-- name: CreateLocalhostServerIfAbsent :execrows
INSERT INTO servers (team_id, name, description, host, port, ssh_user, private_key_id, is_localhost)
VALUES ($1, 'localhost', 'The machine hosting this AkerDock instance, seeded at first start (instance-config §6.2). Validated automatically once the instance public key is authorized on this host.', $2, 22, $3, $4, true)
ON CONFLICT DO NOTHING
`

type CreateLocalhostServerIfAbsentParams struct {
	TeamID       int64
	Host         string
	SshUser      string
	PrivateKeyID int64
}

// ON CONFLICT: the operator may already have a server named "localhost" in
// that team — theirs wins, the seed backs off silently.
func (q *Queries) CreateLocalhostServerIfAbsent(ctx context.Context, arg CreateLocalhostServerIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, createLocalhostServerIfAbsent,
		arg.TeamID,
		arg.Host,
		arg.SshUser,
		arg.PrivateKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, is_root)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, email, name, password_hash, is_root, email_verified_at, failed_login_count, locked_until, created_at, updated_at, deleted_at, version
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash *string
	IsRoot       bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsRoot,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsRoot,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, fqdn, timezone, registration_enabled, api_enabled, dns_validation_server, transactional_email_config_enc, auto_update_enabled, auto_update_cron, onboarding_completed_at, updated_by, created_at, updated_at, version, acme_email, localhost_seeded, otlp_config_enc, mfa_required, password_login_disabled, image_retention_count FROM instance_settings WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.Timezone,
		&i.RegistrationEnabled,
		&i.ApiEnabled,
		&i.DnsValidationServer,
		&i.TransactionalEmailConfigEnc,
		&i.AutoUpdateEnabled,
		&i.AutoUpdateCron,
		&i.OnboardingCompletedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AcmeEmail,
		&i.LocalhostSeeded,
		&i.OtlpConfigEnc,
		&i.MfaRequired,
		&i.PasswordLoginDisabled,
		&i.ImageRetentionCount,
	)
	return i, err
}

const getOldestTeamID = `-- name: GetOldestTeamID :one
SELECT id FROM teams ORDER BY id LIMIT 1
`

// The localhost server lands in the first team of the instance — the root
// user's, by construction (§6.2).
func (q *Queries) GetOldestTeamID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOldestTeamID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertInstanceSettingsIfAbsent = `-- name: InsertInstanceSettingsIfAbsent :execrows
INSERT INTO instance_settings (id, fqdn, timezone, acme_email)
VALUES (1, $1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertInstanceSettingsIfAbsentParams struct {
	Fqdn      *string
	Timezone  string
	AcmeEmail *string
}

func (q *Queries) InsertInstanceSettingsIfAbsent(ctx context.Context, arg InsertInstanceSettingsIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInstanceSettingsIfAbsent, arg.Fqdn, arg.Timezone, arg.AcmeEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAcmeEmailIfAbsent = `-- name: SetAcmeEmailIfAbsent :execrows
UPDATE instance_settings SET acme_email = $1, updated_at = now()
WHERE id = 1 AND acme_email IS NULL
`

// Seeds the ACME contact on an instance that predates the setting. The database
// stays authoritative: an existing value is never overwritten by the variable.
func (q *Queries) SetAcmeEmailIfAbsent(ctx context.Context, acmeEmail *string) (int64, error) {
	result, err := q.db.Exec(ctx, setAcmeEmailIfAbsent, acmeEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLocalhostSeeded = `-- name: SetLocalhostSeeded :execrows
UPDATE instance_settings SET localhost_seeded = true, updated_at = now()
WHERE id = 1 AND NOT localhost_seeded
`

func (q *Queries) SetLocalhostSeeded(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, setLocalhostSeeded)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
