// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, uuid, server_id, kind, main_domain, sans, issuer, not_before, not_after, status, last_error, dns_provider, dns_credential_id, cert_path, key_path, observed_at, created_at, updated_at, expiry_alerted_threshold, expiry_alerted_at FROM certificates WHERE id = $1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id int64) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ServerID,
		&i.Kind,
		&i.MainDomain,
		&i.Sans,
		&i.Issuer,
		&i.NotBefore,
		&i.NotAfter,
		&i.Status,
		&i.LastError,
		&i.DnsProvider,
		&i.DnsCredentialID,
		&i.CertPath,
		&i.KeyPath,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiryAlertedThreshold,
		&i.ExpiryAlertedAt,
	)
	return i, err
}

const getCertificateByUUIDForTeam = `-- name: GetCertificateByUUIDForTeam :one
SELECT c.id, c.uuid, c.server_id, c.kind, c.main_domain, c.sans, c.issuer, c.not_before, c.not_after, c.status, c.last_error, c.dns_provider, c.dns_credential_id, c.cert_path, c.key_path, c.observed_at, c.created_at, c.updated_at, c.expiry_alerted_threshold, c.expiry_alerted_at, s.uuid AS server_uuid FROM certificates c
JOIN servers s ON s.id = c.server_id
WHERE c.uuid = $1 AND s.team_id = $2 AND s.deleted_at IS NULL
`

type GetCertificateByUUIDForTeamParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

type GetCertificateByUUIDForTeamRow struct {
	Certificate Certificate
	ServerUuid  pgtype.UUID
}

func (q *Queries) GetCertificateByUUIDForTeam(ctx context.Context, arg GetCertificateByUUIDForTeamParams) (GetCertificateByUUIDForTeamRow, error) {
	row := q.db.QueryRow(ctx, getCertificateByUUIDForTeam, arg.Uuid, arg.TeamID)
	var i GetCertificateByUUIDForTeamRow
	err := row.Scan(
		&i.Certificate.ID,
		&i.Certificate.Uuid,
		&i.Certificate.ServerID,
		&i.Certificate.Kind,
		&i.Certificate.MainDomain,
		&i.Certificate.Sans,
		&i.Certificate.Issuer,
		&i.Certificate.NotBefore,
		&i.Certificate.NotAfter,
		&i.Certificate.Status,
		&i.Certificate.LastError,
		&i.Certificate.DnsProvider,
		&i.Certificate.DnsCredentialID,
		&i.Certificate.CertPath,
		&i.Certificate.KeyPath,
		&i.Certificate.ObservedAt,
		&i.Certificate.CreatedAt,
		&i.Certificate.UpdatedAt,
		&i.Certificate.ExpiryAlertedThreshold,
		&i.Certificate.ExpiryAlertedAt,
		&i.ServerUuid,
	)
	return i, err
}

const listCertificatesForServer = `-- name: ListCertificatesForServer :many
SELECT id, uuid, server_id, kind, main_domain, sans, issuer, not_before, not_after, status, last_error, dns_provider, dns_credential_id, cert_path, key_path, observed_at, created_at, updated_at, expiry_alerted_threshold, expiry_alerted_at FROM certificates
WHERE server_id = $1
  AND ($2::int IS NULL
       OR (not_after IS NOT NULL AND not_after <= now() + make_interval(days => $2::int)))
ORDER BY not_after NULLS LAST, main_domain
`

type ListCertificatesForServerParams struct {
	ServerID           int64
	ExpiringWithinDays *int32
}

func (q *Queries) ListCertificatesForServer(ctx context.Context, arg ListCertificatesForServerParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesForServer, arg.ServerID, arg.ExpiringWithinDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ServerID,
			&i.Kind,
			&i.MainDomain,
			&i.Sans,
			&i.Issuer,
			&i.NotBefore,
			&i.NotAfter,
			&i.Status,
			&i.LastError,
			&i.DnsProvider,
			&i.DnsCredentialID,
			&i.CertPath,
			&i.KeyPath,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiryAlertedThreshold,
			&i.ExpiryAlertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesToAlert = `-- name: ListCertificatesToAlert :many
SELECT c.id, c.uuid, c.server_id, c.kind, c.main_domain, c.sans, c.issuer, c.not_before, c.not_after, c.status, c.last_error, c.dns_provider, c.dns_credential_id, c.cert_path, c.key_path, c.observed_at, c.created_at, c.updated_at, c.expiry_alerted_threshold, c.expiry_alerted_at, s.uuid AS server_uuid, t.uuid AS team_uuid
FROM certificates c
JOIN servers s ON s.id = c.server_id
JOIN teams t ON t.id = s.team_id
WHERE c.status IN ('issued', 'expired')
  AND c.not_after IS NOT NULL
  AND c.not_after < now() + make_interval(days => $1::int)
  AND (c.expiry_alerted_threshold IS NULL OR c.expiry_alerted_threshold > $1::int)
ORDER BY c.not_after
`

type ListCertificatesToAlertRow struct {
	ID                     int64
	Uuid                   pgtype.UUID
	ServerID               int64
	Kind                   CertificateKind
	MainDomain             string
	Sans                   []string
	Issuer                 *string
	NotBefore              pgtype.Timestamptz
	NotAfter               pgtype.Timestamptz
	Status                 CertificateStatus
	LastError              *string
	DnsProvider            *string
	DnsCredentialID        *int64
	CertPath               *string
	KeyPath                *string
	ObservedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ExpiryAlertedThreshold *int32
	ExpiryAlertedAt        pgtype.Timestamptz
	ServerUuid             pgtype.UUID
	TeamUuid               pgtype.UUID
}

// Certificates entering a threshold they have not been announced for yet
// (§4.3). A certificate already alerted at J-30 stays silent until it crosses
// J-7 — the alert fires on the transition, not on every pass.
func (q *Queries) ListCertificatesToAlert(ctx context.Context, thresholdDays int32) ([]ListCertificatesToAlertRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesToAlert, thresholdDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificatesToAlertRow
	for rows.Next() {
		var i ListCertificatesToAlertRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ServerID,
			&i.Kind,
			&i.MainDomain,
			&i.Sans,
			&i.Issuer,
			&i.NotBefore,
			&i.NotAfter,
			&i.Status,
			&i.LastError,
			&i.DnsProvider,
			&i.DnsCredentialID,
			&i.CertPath,
			&i.KeyPath,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiryAlertedThreshold,
			&i.ExpiryAlertedAt,
			&i.ServerUuid,
			&i.TeamUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCertificateAlerted = `-- name: MarkCertificateAlerted :exec
UPDATE certificates
SET expiry_alerted_threshold = $2, expiry_alerted_at = now()
WHERE id = $1
`

type MarkCertificateAlertedParams struct {
	ID                     int64
	ExpiryAlertedThreshold *int32
}

func (q *Queries) MarkCertificateAlerted(ctx context.Context, arg MarkCertificateAlertedParams) error {
	_, err := q.db.Exec(ctx, markCertificateAlerted, arg.ID, arg.ExpiryAlertedThreshold)
	return err
}

const setCertificateStatus = `-- name: SetCertificateStatus :exec
UPDATE certificates SET status = $2, last_error = $3, updated_at = now() WHERE id = $1
`

type SetCertificateStatusParams struct {
	ID        int64
	Status    CertificateStatus
	LastError *string
}

func (q *Queries) SetCertificateStatus(ctx context.Context, arg SetCertificateStatusParams) error {
	_, err := q.db.Exec(ctx, setCertificateStatus, arg.ID, arg.Status, arg.LastError)
	return err
}

const upsertCertificate = `-- name: UpsertCertificate :exec

INSERT INTO certificates (server_id, kind, main_domain, sans, issuer, not_before, not_after, status, observed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (server_id, kind, main_domain) DO UPDATE SET
    sans = EXCLUDED.sans, issuer = EXCLUDED.issuer,
    not_before = EXCLUDED.not_before, not_after = EXCLUDED.not_after,
    status = EXCLUDED.status, observed_at = now(), updated_at = now()
`

type UpsertCertificateParams struct {
	ServerID   int64
	Kind       CertificateKind
	MainDomain string
	Sans       []string
	Issuer     *string
	NotBefore  pgtype.Timestamptz
	NotAfter   pgtype.Timestamptz
	Status     CertificateStatus
}

// Certificates: observed reflection of the server state (§18.3).
func (q *Queries) UpsertCertificate(ctx context.Context, arg UpsertCertificateParams) error {
	_, err := q.db.Exec(ctx, upsertCertificate,
		arg.ServerID,
		arg.Kind,
		arg.MainDomain,
		arg.Sans,
		arg.Issuer,
		arg.NotBefore,
		arg.NotAfter,
		arg.Status,
	)
	return err
}
