// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cliauth.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveCliAuthCode = `-- name: ApproveCliAuthCode :execrows
UPDATE cli_authorization_codes
SET status = 'approved', user_id = $2, team_id = $3, permissions = $4
WHERE request_id_hash = $1 AND status = 'pending' AND expires_at > now()
`

type ApproveCliAuthCodeParams struct {
	RequestIDHash string
	UserID        *int64
	TeamID        *int64
	Permissions   []string
}

// Bind the pending request to the approving user/team and permissions.
func (q *Queries) ApproveCliAuthCode(ctx context.Context, arg ApproveCliAuthCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveCliAuthCode,
		arg.RequestIDHash,
		arg.UserID,
		arg.TeamID,
		arg.Permissions,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeCliAuthCode = `-- name: ConsumeCliAuthCode :one
UPDATE cli_authorization_codes
SET status = 'consumed'
WHERE request_id_hash = $1 AND status = 'approved' AND expires_at > now()
RETURNING id, request_id_hash, challenge, user_code, status, user_id, team_id, permissions, client_name, client_ip, expires_at, created_at
`

// Single-use: the token exchange claims the approved request atomically.
func (q *Queries) ConsumeCliAuthCode(ctx context.Context, requestIDHash string) (CliAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeCliAuthCode, requestIDHash)
	var i CliAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.RequestIDHash,
		&i.Challenge,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.TeamID,
		&i.Permissions,
		&i.ClientName,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCliAuthCode = `-- name: CreateCliAuthCode :one

INSERT INTO cli_authorization_codes (
    request_id_hash, challenge, user_code, client_name, client_ip, expires_at
) VALUES ($1, $2, $3, $5, $6, $4)
RETURNING id, request_id_hash, challenge, user_code, status, user_id, team_id, permissions, client_name, client_ip, expires_at, created_at
`

type CreateCliAuthCodeParams struct {
	RequestIDHash string
	Challenge     string
	UserCode      string
	ExpiresAt     pgtype.Timestamptz
	ClientName    *string
	ClientIp      *netip.Addr
}

// CLI login requests (ADR-031, data-dictionary §10.8).
func (q *Queries) CreateCliAuthCode(ctx context.Context, arg CreateCliAuthCodeParams) (CliAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createCliAuthCode,
		arg.RequestIDHash,
		arg.Challenge,
		arg.UserCode,
		arg.ExpiresAt,
		arg.ClientName,
		arg.ClientIp,
	)
	var i CliAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.RequestIDHash,
		&i.Challenge,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.TeamID,
		&i.Permissions,
		&i.ClientName,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCliAuthCodeByRequestHash = `-- name: GetCliAuthCodeByRequestHash :one
SELECT id, request_id_hash, challenge, user_code, status, user_id, team_id, permissions, client_name, client_ip, expires_at, created_at FROM cli_authorization_codes
WHERE request_id_hash = $1 AND expires_at > now()
`

func (q *Queries) GetCliAuthCodeByRequestHash(ctx context.Context, requestIDHash string) (CliAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getCliAuthCodeByRequestHash, requestIDHash)
	var i CliAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.RequestIDHash,
		&i.Challenge,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.TeamID,
		&i.Permissions,
		&i.ClientName,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const purgeCliAuthCodes = `-- name: PurgeCliAuthCodes :execrows
DELETE FROM cli_authorization_codes WHERE expires_at <= now()
`

func (q *Queries) PurgeCliAuthCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeCliAuthCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
