// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: databases.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabaseCredential = `-- name: CreateDatabaseCredential :one
INSERT INTO database_credentials (uuid, database_id, username, password_enc, db_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, database_id, username, password_enc, db_name, created_at, updated_at
`

type CreateDatabaseCredentialParams struct {
	Uuid        pgtype.UUID
	DatabaseID  int64
	Username    string
	PasswordEnc []byte
	DbName      *string
}

func (q *Queries) CreateDatabaseCredential(ctx context.Context, arg CreateDatabaseCredentialParams) (DatabaseCredential, error) {
	row := q.db.QueryRow(ctx, createDatabaseCredential,
		arg.Uuid,
		arg.DatabaseID,
		arg.Username,
		arg.PasswordEnc,
		arg.DbName,
	)
	var i DatabaseCredential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DatabaseID,
		&i.Username,
		&i.PasswordEnc,
		&i.DbName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDatabaseRow = `-- name: CreateDatabaseRow :exec

INSERT INTO databases (id, engine, image, image_tag, custom_config, initdb_args, server_id, is_public, public_access_mode, public_port, ssl_enabled, ssl_mode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateDatabaseRowParams struct {
	ID               int64
	Engine           DbEngine
	Image            *string
	ImageTag         *string
	CustomConfig     *string
	InitdbArgs       *string
	ServerID         int64
	IsPublic         bool
	PublicAccessMode *PublicAccessMode
	PublicPort       *int32
	SslEnabled       bool
	SslMode          *string
}

// Managed databases (§6). Passwords are envelope encrypted; connection
// URLs are rebuilt on the fly, never stored assembled (§6.2).
func (q *Queries) CreateDatabaseRow(ctx context.Context, arg CreateDatabaseRowParams) error {
	_, err := q.db.Exec(ctx, createDatabaseRow,
		arg.ID,
		arg.Engine,
		arg.Image,
		arg.ImageTag,
		arg.CustomConfig,
		arg.InitdbArgs,
		arg.ServerID,
		arg.IsPublic,
		arg.PublicAccessMode,
		arg.PublicPort,
		arg.SslEnabled,
		arg.SslMode,
	)
	return err
}

const getDatabaseByID = `-- name: GetDatabaseByID :one
SELECT r.id, r.uuid, r.team_id, r.environment_id, r.destination_id, r.resource_type, r.name, r.description, r.desired_status, r.observed_status, r.observed_at, r.last_online_at, r.remnants, r.created_by, r.updated_by, r.created_at, r.updated_at, r.deleted_at, r.version, r.adopted_at, r.adoption, d.id, d.engine, d.image, d.image_tag, d.custom_config, d.initdb_args, d.server_id, d.is_public, d.public_access_mode, d.public_port, d.tcp_proxy_timeout_seconds, d.ssl_enabled, d.ssl_mode, d.created_at, d.updated_at, c.id, c.uuid, c.database_id, c.username, c.password_enc, c.db_name, c.created_at, c.updated_at
FROM resources r
JOIN databases d ON d.id = r.id
JOIN database_credentials c ON c.database_id = d.id
WHERE r.id = $1 AND r.deleted_at IS NULL AND r.resource_type = 'database'
`

type GetDatabaseByIDRow struct {
	Resource           Resource
	Database           Database
	DatabaseCredential DatabaseCredential
}

func (q *Queries) GetDatabaseByID(ctx context.Context, id int64) (GetDatabaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getDatabaseByID, id)
	var i GetDatabaseByIDRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Uuid,
		&i.Resource.TeamID,
		&i.Resource.EnvironmentID,
		&i.Resource.DestinationID,
		&i.Resource.ResourceType,
		&i.Resource.Name,
		&i.Resource.Description,
		&i.Resource.DesiredStatus,
		&i.Resource.ObservedStatus,
		&i.Resource.ObservedAt,
		&i.Resource.LastOnlineAt,
		&i.Resource.Remnants,
		&i.Resource.CreatedBy,
		&i.Resource.UpdatedBy,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
		&i.Resource.DeletedAt,
		&i.Resource.Version,
		&i.Resource.AdoptedAt,
		&i.Resource.Adoption,
		&i.Database.ID,
		&i.Database.Engine,
		&i.Database.Image,
		&i.Database.ImageTag,
		&i.Database.CustomConfig,
		&i.Database.InitdbArgs,
		&i.Database.ServerID,
		&i.Database.IsPublic,
		&i.Database.PublicAccessMode,
		&i.Database.PublicPort,
		&i.Database.TcpProxyTimeoutSeconds,
		&i.Database.SslEnabled,
		&i.Database.SslMode,
		&i.Database.CreatedAt,
		&i.Database.UpdatedAt,
		&i.DatabaseCredential.ID,
		&i.DatabaseCredential.Uuid,
		&i.DatabaseCredential.DatabaseID,
		&i.DatabaseCredential.Username,
		&i.DatabaseCredential.PasswordEnc,
		&i.DatabaseCredential.DbName,
		&i.DatabaseCredential.CreatedAt,
		&i.DatabaseCredential.UpdatedAt,
	)
	return i, err
}

const getDatabaseByUUID = `-- name: GetDatabaseByUUID :one
SELECT r.id, r.uuid, r.team_id, r.environment_id, r.destination_id, r.resource_type, r.name, r.description, r.desired_status, r.observed_status, r.observed_at, r.last_online_at, r.remnants, r.created_by, r.updated_by, r.created_at, r.updated_at, r.deleted_at, r.version, r.adopted_at, r.adoption, d.id, d.engine, d.image, d.image_tag, d.custom_config, d.initdb_args, d.server_id, d.is_public, d.public_access_mode, d.public_port, d.tcp_proxy_timeout_seconds, d.ssl_enabled, d.ssl_mode, d.created_at, d.updated_at, c.id, c.uuid, c.database_id, c.username, c.password_enc, c.db_name, c.created_at, c.updated_at,
       e.uuid AS environment_uuid, p.uuid AS project_uuid, srv.uuid AS server_uuid,
       srv.host AS server_host
FROM resources r
JOIN databases d ON d.id = r.id
JOIN database_credentials c ON c.database_id = d.id
JOIN environments e ON e.id = r.environment_id
JOIN projects p ON p.id = e.project_id
JOIN servers srv ON srv.id = d.server_id
WHERE r.uuid = $1 AND r.team_id = $2 AND r.deleted_at IS NULL AND r.resource_type = 'database'
`

type GetDatabaseByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

type GetDatabaseByUUIDRow struct {
	Resource           Resource
	Database           Database
	DatabaseCredential DatabaseCredential
	EnvironmentUuid    pgtype.UUID
	ProjectUuid        pgtype.UUID
	ServerUuid         pgtype.UUID
	ServerHost         string
}

func (q *Queries) GetDatabaseByUUID(ctx context.Context, arg GetDatabaseByUUIDParams) (GetDatabaseByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getDatabaseByUUID, arg.Uuid, arg.TeamID)
	var i GetDatabaseByUUIDRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Uuid,
		&i.Resource.TeamID,
		&i.Resource.EnvironmentID,
		&i.Resource.DestinationID,
		&i.Resource.ResourceType,
		&i.Resource.Name,
		&i.Resource.Description,
		&i.Resource.DesiredStatus,
		&i.Resource.ObservedStatus,
		&i.Resource.ObservedAt,
		&i.Resource.LastOnlineAt,
		&i.Resource.Remnants,
		&i.Resource.CreatedBy,
		&i.Resource.UpdatedBy,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
		&i.Resource.DeletedAt,
		&i.Resource.Version,
		&i.Resource.AdoptedAt,
		&i.Resource.Adoption,
		&i.Database.ID,
		&i.Database.Engine,
		&i.Database.Image,
		&i.Database.ImageTag,
		&i.Database.CustomConfig,
		&i.Database.InitdbArgs,
		&i.Database.ServerID,
		&i.Database.IsPublic,
		&i.Database.PublicAccessMode,
		&i.Database.PublicPort,
		&i.Database.TcpProxyTimeoutSeconds,
		&i.Database.SslEnabled,
		&i.Database.SslMode,
		&i.Database.CreatedAt,
		&i.Database.UpdatedAt,
		&i.DatabaseCredential.ID,
		&i.DatabaseCredential.Uuid,
		&i.DatabaseCredential.DatabaseID,
		&i.DatabaseCredential.Username,
		&i.DatabaseCredential.PasswordEnc,
		&i.DatabaseCredential.DbName,
		&i.DatabaseCredential.CreatedAt,
		&i.DatabaseCredential.UpdatedAt,
		&i.EnvironmentUuid,
		&i.ProjectUuid,
		&i.ServerUuid,
		&i.ServerHost,
	)
	return i, err
}

const listDatabasesPage = `-- name: ListDatabasesPage :many
SELECT r.id, r.uuid, r.team_id, r.environment_id, r.destination_id, r.resource_type, r.name, r.description, r.desired_status, r.observed_status, r.observed_at, r.last_online_at, r.remnants, r.created_by, r.updated_by, r.created_at, r.updated_at, r.deleted_at, r.version, r.adopted_at, r.adoption, d.id, d.engine, d.image, d.image_tag, d.custom_config, d.initdb_args, d.server_id, d.is_public, d.public_access_mode, d.public_port, d.tcp_proxy_timeout_seconds, d.ssl_enabled, d.ssl_mode, d.created_at, d.updated_at, c.id, c.uuid, c.database_id, c.username, c.password_enc, c.db_name, c.created_at, c.updated_at,
       e.uuid AS environment_uuid, p.uuid AS project_uuid, srv.uuid AS server_uuid,
       srv.host AS server_host
FROM resources r
JOIN databases d ON d.id = r.id
JOIN database_credentials c ON c.database_id = d.id
JOIN environments e ON e.id = r.environment_id
JOIN projects p ON p.id = e.project_id
JOIN servers srv ON srv.id = d.server_id
WHERE r.team_id = $1 AND r.deleted_at IS NULL AND r.resource_type = 'database'
  AND ($2::uuid IS NULL OR e.uuid = $2)
  AND ($3::uuid IS NULL OR srv.uuid = $3)
  AND ($4::bigint = 0 OR r.id < $4)
ORDER BY r.id DESC
LIMIT $5
`

type ListDatabasesPageParams struct {
	TeamID          int64
	EnvironmentUuid pgtype.UUID
	ServerUuid      pgtype.UUID
	AfterID         int64
	PageLimit       int32
}

type ListDatabasesPageRow struct {
	Resource           Resource
	Database           Database
	DatabaseCredential DatabaseCredential
	EnvironmentUuid    pgtype.UUID
	ProjectUuid        pgtype.UUID
	ServerUuid         pgtype.UUID
	ServerHost         string
}

func (q *Queries) ListDatabasesPage(ctx context.Context, arg ListDatabasesPageParams) ([]ListDatabasesPageRow, error) {
	rows, err := q.db.Query(ctx, listDatabasesPage,
		arg.TeamID,
		arg.EnvironmentUuid,
		arg.ServerUuid,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDatabasesPageRow
	for rows.Next() {
		var i ListDatabasesPageRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Uuid,
			&i.Resource.TeamID,
			&i.Resource.EnvironmentID,
			&i.Resource.DestinationID,
			&i.Resource.ResourceType,
			&i.Resource.Name,
			&i.Resource.Description,
			&i.Resource.DesiredStatus,
			&i.Resource.ObservedStatus,
			&i.Resource.ObservedAt,
			&i.Resource.LastOnlineAt,
			&i.Resource.Remnants,
			&i.Resource.CreatedBy,
			&i.Resource.UpdatedBy,
			&i.Resource.CreatedAt,
			&i.Resource.UpdatedAt,
			&i.Resource.DeletedAt,
			&i.Resource.Version,
			&i.Resource.AdoptedAt,
			&i.Resource.Adoption,
			&i.Database.ID,
			&i.Database.Engine,
			&i.Database.Image,
			&i.Database.ImageTag,
			&i.Database.CustomConfig,
			&i.Database.InitdbArgs,
			&i.Database.ServerID,
			&i.Database.IsPublic,
			&i.Database.PublicAccessMode,
			&i.Database.PublicPort,
			&i.Database.TcpProxyTimeoutSeconds,
			&i.Database.SslEnabled,
			&i.Database.SslMode,
			&i.Database.CreatedAt,
			&i.Database.UpdatedAt,
			&i.DatabaseCredential.ID,
			&i.DatabaseCredential.Uuid,
			&i.DatabaseCredential.DatabaseID,
			&i.DatabaseCredential.Username,
			&i.DatabaseCredential.PasswordEnc,
			&i.DatabaseCredential.DbName,
			&i.DatabaseCredential.CreatedAt,
			&i.DatabaseCredential.UpdatedAt,
			&i.EnvironmentUuid,
			&i.ProjectUuid,
			&i.ServerUuid,
			&i.ServerHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTCPProxyPorts = `-- name: ListTCPProxyPorts :many
SELECT d.public_port FROM databases d
JOIN resources r ON r.id = d.id
WHERE d.server_id = $1 AND d.is_public AND d.public_access_mode = 'tcp_proxy'
  AND d.public_port IS NOT NULL AND r.deleted_at IS NULL
ORDER BY d.public_port
`

// Every public port routed through the proxy on a server. It is the set the
// static config must declare: Traefik cannot add a listener at runtime.
func (q *Queries) ListTCPProxyPorts(ctx context.Context, serverID int64) ([]*int32, error) {
	rows, err := q.db.Query(ctx, listTCPProxyPorts, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*int32
	for rows.Next() {
		var public_port *int32
		if err := rows.Scan(&public_port); err != nil {
			return nil, err
		}
		items = append(items, public_port)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFreePublicPort = `-- name: NextFreePublicPort :one
SELECT coalesce(max(public_port), 15431) + 1 AS port
FROM databases WHERE server_id = $1 AND is_public
`

// Lowest free port in the dynamic range for a server (§6.2); the unique
// index remains the authority against concurrent allocation.
func (q *Queries) NextFreePublicPort(ctx context.Context, serverID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextFreePublicPort, serverID)
	var port int32
	err := row.Scan(&port)
	return port, err
}

const updateDatabasePassword = `-- name: UpdateDatabasePassword :exec
UPDATE database_credentials SET password_enc = $2, updated_at = now() WHERE database_id = $1
`

type UpdateDatabasePasswordParams struct {
	DatabaseID  int64
	PasswordEnc []byte
}

func (q *Queries) UpdateDatabasePassword(ctx context.Context, arg UpdateDatabasePasswordParams) error {
	_, err := q.db.Exec(ctx, updateDatabasePassword, arg.DatabaseID, arg.PasswordEnc)
	return err
}

const updateDatabaseRow = `-- name: UpdateDatabaseRow :exec
UPDATE databases SET image = $2, image_tag = $3, custom_config = $4,
    is_public = $5, public_access_mode = $6, public_port = $7, ssl_mode = $8, updated_at = now()
WHERE id = $1
`

type UpdateDatabaseRowParams struct {
	ID               int64
	Image            *string
	ImageTag         *string
	CustomConfig     *string
	IsPublic         bool
	PublicAccessMode *PublicAccessMode
	PublicPort       *int32
	SslMode          *string
}

func (q *Queries) UpdateDatabaseRow(ctx context.Context, arg UpdateDatabaseRowParams) error {
	_, err := q.db.Exec(ctx, updateDatabaseRow,
		arg.ID,
		arg.Image,
		arg.ImageTag,
		arg.CustomConfig,
		arg.IsPublic,
		arg.PublicAccessMode,
		arg.PublicPort,
		arg.SslMode,
	)
	return err
}
