// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignDeploymentBuildServerUnlessCleanupRunning = `-- name: AssignDeploymentBuildServerUnlessCleanupRunning :execrows
WITH locked_server AS MATERIALIZED (
    SELECT s.id
    FROM servers s
    WHERE s.id = $2
    FOR UPDATE
)
UPDATE deployments d
SET build_server_id = s.id,
    updated_at = now()
FROM locked_server s
WHERE d.id = $1
  AND NOT EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.job_type = 'server.cleanup'
        AND j.status IN ('leased', 'running')
        AND j.payload->>'server_id' = s.id::text
  )
`

type AssignDeploymentBuildServerUnlessCleanupRunningParams struct {
	DeploymentID  int64
	BuildServerID int64
}

// A build server is another mutation target of the deployment. Reserve it
// through the same reader/writer exclusion as the deployment server, before
// opening SSH or creating its working directory.
func (q *Queries) AssignDeploymentBuildServerUnlessCleanupRunning(ctx context.Context, arg AssignDeploymentBuildServerUnlessCleanupRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignDeploymentBuildServerUnlessCleanupRunning, arg.DeploymentID, arg.BuildServerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelJobsForDeployments = `-- name: CancelJobsForDeployments :exec
UPDATE jobs SET status = 'cancelled', finished_at = now(), updated_at = now()
WHERE job_type = 'deployment.run' AND status = 'queued'
  AND (payload->>'deployment_id')::bigint = ANY($1::bigint[])
`

func (q *Queries) CancelJobsForDeployments(ctx context.Context, deploymentIds []int64) error {
	_, err := q.db.Exec(ctx, cancelJobsForDeployments, deploymentIds)
	return err
}

const cancelQueuedDeployment = `-- name: CancelQueuedDeployment :execrows
UPDATE deployments SET status = 'cancelled', finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) CancelQueuedDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelQueuedDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveDeploymentsForServer = `-- name: CountActiveDeploymentsForServer :one
SELECT count(*) FROM deployments
WHERE server_id = $1 AND status NOT IN ('succeeded', 'failed', 'cancelled', 'superseded')
`

func (q *Queries) CountActiveDeploymentsForServer(ctx context.Context, serverID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDeploymentsForServer, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments (uuid, resource_id, trigger, api_token_id, force_rebuild, image_name, image_tag, server_id, config_snapshot, preview_id, commit_sha)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, uuid, resource_id, status, attempt, retry_of_id, superseded_by_id, is_rollback, trigger, triggered_by, api_token_id, git_branch, commit_sha, is_local_source, context_digest, force_rebuild, image_name, image_tag, image_digest, config_snapshot, config_diff, error_message, server_id, build_server_id, queued_at, started_at, finished_at, created_at, updated_at, preview_id, commit_author, commit_message, skip_build
`

type CreateDeploymentParams struct {
	Uuid           pgtype.UUID
	ResourceID     int64
	Trigger        DeploymentTrigger
	ApiTokenID     *int64
	ForceRebuild   bool
	ImageName      *string
	ImageTag       *string
	ServerID       int64
	ConfigSnapshot []byte
	PreviewID      *int64
	CommitSha      *string
}

// Deployments (state machine §21.1). Transitions are committed before the
// next remote action (write-ahead, deployment-engine §4).
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.Uuid,
		arg.ResourceID,
		arg.Trigger,
		arg.ApiTokenID,
		arg.ForceRebuild,
		arg.ImageName,
		arg.ImageTag,
		arg.ServerID,
		arg.ConfigSnapshot,
		arg.PreviewID,
		arg.CommitSha,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Status,
		&i.Attempt,
		&i.RetryOfID,
		&i.SupersededByID,
		&i.IsRollback,
		&i.Trigger,
		&i.TriggeredBy,
		&i.ApiTokenID,
		&i.GitBranch,
		&i.CommitSha,
		&i.IsLocalSource,
		&i.ContextDigest,
		&i.ForceRebuild,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.ConfigDiff,
		&i.ErrorMessage,
		&i.ServerID,
		&i.BuildServerID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviewID,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.SkipBuild,
	)
	return i, err
}

const createDeploymentArtifact = `-- name: CreateDeploymentArtifact :exec

INSERT INTO deployment_artifacts (deployment_id, kind, image_name, image_tag, image_digest, server_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDeploymentArtifactParams struct {
	DeploymentID int64
	Kind         ArtifactKind
	ImageName    string
	ImageTag     *string
	ImageDigest  *string
	ServerID     *int64
}

// Rollback artifacts (ADR-006, §10.3).
func (q *Queries) CreateDeploymentArtifact(ctx context.Context, arg CreateDeploymentArtifactParams) error {
	_, err := q.db.Exec(ctx, createDeploymentArtifact,
		arg.DeploymentID,
		arg.Kind,
		arg.ImageName,
		arg.ImageTag,
		arg.ImageDigest,
		arg.ServerID,
	)
	return err
}

const createDeploymentStep = `-- name: CreateDeploymentStep :one
INSERT INTO deployment_steps (deployment_id, seq, name, status, started_at)
VALUES ($1, $2, $3, 'running', now())
RETURNING id
`

type CreateDeploymentStepParams struct {
	DeploymentID int64
	Seq          int32
	Name         string
}

func (q *Queries) CreateDeploymentStep(ctx context.Context, arg CreateDeploymentStepParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDeploymentStep, arg.DeploymentID, arg.Seq, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createNoBuildDeployment = `-- name: CreateNoBuildDeployment :one
INSERT INTO deployments (uuid, resource_id, trigger, api_token_id, skip_build, image_name, image_tag, image_digest, server_id, config_snapshot, preview_id, commit_sha)
VALUES ($1, $2, $3, $4, true, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, uuid, resource_id, status, attempt, retry_of_id, superseded_by_id, is_rollback, trigger, triggered_by, api_token_id, git_branch, commit_sha, is_local_source, context_digest, force_rebuild, image_name, image_tag, image_digest, config_snapshot, config_diff, error_message, server_id, build_server_id, queued_at, started_at, finished_at, created_at, updated_at, preview_id, commit_author, commit_message, skip_build
`

type CreateNoBuildDeploymentParams struct {
	Uuid           pgtype.UUID
	ResourceID     int64
	Trigger        DeploymentTrigger
	ApiTokenID     *int64
	ImageName      *string
	ImageTag       *string
	ImageDigest    *string
	ServerID       int64
	ConfigSnapshot []byte
	PreviewID      *int64
	CommitSha      *string
}

// A deployment that rebuilds nothing (ADR-048): the artifact is the one
// already running, the pipeline reruns to apply the current configuration.
// `image_digest` pins it when the artifact carries one, so what comes back up
// is provably the image that was running.
func (q *Queries) CreateNoBuildDeployment(ctx context.Context, arg CreateNoBuildDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createNoBuildDeployment,
		arg.Uuid,
		arg.ResourceID,
		arg.Trigger,
		arg.ApiTokenID,
		arg.ImageName,
		arg.ImageTag,
		arg.ImageDigest,
		arg.ServerID,
		arg.ConfigSnapshot,
		arg.PreviewID,
		arg.CommitSha,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Status,
		&i.Attempt,
		&i.RetryOfID,
		&i.SupersededByID,
		&i.IsRollback,
		&i.Trigger,
		&i.TriggeredBy,
		&i.ApiTokenID,
		&i.GitBranch,
		&i.CommitSha,
		&i.IsLocalSource,
		&i.ContextDigest,
		&i.ForceRebuild,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.ConfigDiff,
		&i.ErrorMessage,
		&i.ServerID,
		&i.BuildServerID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviewID,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.SkipBuild,
	)
	return i, err
}

const createRollbackDeployment = `-- name: CreateRollbackDeployment :one
INSERT INTO deployments (uuid, resource_id, trigger, api_token_id, is_rollback, image_name, image_tag, image_digest, server_id, config_snapshot)
VALUES ($1, $2, $3, $4, true, $5, $6, $7, $8, $9)
RETURNING id, uuid, resource_id, status, attempt, retry_of_id, superseded_by_id, is_rollback, trigger, triggered_by, api_token_id, git_branch, commit_sha, is_local_source, context_digest, force_rebuild, image_name, image_tag, image_digest, config_snapshot, config_diff, error_message, server_id, build_server_id, queued_at, started_at, finished_at, created_at, updated_at, preview_id, commit_author, commit_message, skip_build
`

type CreateRollbackDeploymentParams struct {
	Uuid           pgtype.UUID
	ResourceID     int64
	Trigger        DeploymentTrigger
	ApiTokenID     *int64
	ImageName      *string
	ImageTag       *string
	ImageDigest    *string
	ServerID       int64
	ConfigSnapshot []byte
}

func (q *Queries) CreateRollbackDeployment(ctx context.Context, arg CreateRollbackDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createRollbackDeployment,
		arg.Uuid,
		arg.ResourceID,
		arg.Trigger,
		arg.ApiTokenID,
		arg.ImageName,
		arg.ImageTag,
		arg.ImageDigest,
		arg.ServerID,
		arg.ConfigSnapshot,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Status,
		&i.Attempt,
		&i.RetryOfID,
		&i.SupersededByID,
		&i.IsRollback,
		&i.Trigger,
		&i.TriggeredBy,
		&i.ApiTokenID,
		&i.GitBranch,
		&i.CommitSha,
		&i.IsLocalSource,
		&i.ContextDigest,
		&i.ForceRebuild,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.ConfigDiff,
		&i.ErrorMessage,
		&i.ServerID,
		&i.BuildServerID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviewID,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.SkipBuild,
	)
	return i, err
}

const deleteDeploymentArtifact = `-- name: DeleteDeploymentArtifact :exec
DELETE FROM deployment_artifacts WHERE id = $1
`

// The image it referenced has been reclaimed: drop the now-dangling rollback
// pointer so it is never offered as a target.
func (q *Queries) DeleteDeploymentArtifact(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeploymentArtifact, id)
	return err
}

const finishDeploymentStep = `-- name: FinishDeploymentStep :exec
UPDATE deployment_steps SET status = $2, exit_code = $3, log = $4, finished_at = now()
WHERE id = $1
`

type FinishDeploymentStepParams struct {
	ID       int64
	Status   DeploymentStepStatus
	ExitCode *int32
	Log      *string
}

func (q *Queries) FinishDeploymentStep(ctx context.Context, arg FinishDeploymentStepParams) error {
	_, err := q.db.Exec(ctx, finishDeploymentStep,
		arg.ID,
		arg.Status,
		arg.ExitCode,
		arg.Log,
	)
	return err
}

const getArtifactByDigest = `-- name: GetArtifactByDigest :one
SELECT a.id, a.uuid, a.deployment_id, a.kind, a.image_name, a.image_tag, a.image_digest, a.server_id, a.registry_credential_id, a.protected_from_cleanup, a.created_at FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE a.image_digest = $1 AND d.resource_id = $2
ORDER BY a.id DESC
LIMIT 1
`

type GetArtifactByDigestParams struct {
	ImageDigest *string
	ResourceID  int64
}

func (q *Queries) GetArtifactByDigest(ctx context.Context, arg GetArtifactByDigestParams) (DeploymentArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByDigest, arg.ImageDigest, arg.ResourceID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeploymentID,
		&i.Kind,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ServerID,
		&i.RegistryCredentialID,
		&i.ProtectedFromCleanup,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactForDeployment = `-- name: GetArtifactForDeployment :one
SELECT a.id, a.uuid, a.deployment_id, a.kind, a.image_name, a.image_tag, a.image_digest, a.server_id, a.registry_credential_id, a.protected_from_cleanup, a.created_at FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE d.uuid = $1 AND d.resource_id = $2
`

type GetArtifactForDeploymentParams struct {
	Uuid       pgtype.UUID
	ResourceID int64
}

func (q *Queries) GetArtifactForDeployment(ctx context.Context, arg GetArtifactForDeploymentParams) (DeploymentArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactForDeployment, arg.Uuid, arg.ResourceID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeploymentID,
		&i.Kind,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ServerID,
		&i.RegistryCredentialID,
		&i.ProtectedFromCleanup,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentArtifact = `-- name: GetCurrentArtifact :one
SELECT a.id, a.uuid, a.deployment_id, a.kind, a.image_name, a.image_tag, a.image_digest, a.server_id, a.registry_credential_id, a.protected_from_cleanup, a.created_at FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE d.resource_id = $1 AND d.preview_id IS NULL AND d.status = 'succeeded'
ORDER BY a.id DESC
LIMIT 1
`

// The artifact currently serving traffic: the one of the last succeeded
// deployment. This is what a skip_build deployment redeploys (ADR-048) —
// same image, fresh configuration.
func (q *Queries) GetCurrentArtifact(ctx context.Context, resourceID int64) (DeploymentArtifact, error) {
	row := q.db.QueryRow(ctx, getCurrentArtifact, resourceID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeploymentID,
		&i.Kind,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ServerID,
		&i.RegistryCredentialID,
		&i.ProtectedFromCleanup,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPreviewArtifact = `-- name: GetCurrentPreviewArtifact :one
SELECT a.id, a.uuid, a.deployment_id, a.kind, a.image_name, a.image_tag, a.image_digest, a.server_id, a.registry_credential_id, a.protected_from_cleanup, a.created_at FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE d.preview_id = $1 AND d.status = 'succeeded'
ORDER BY a.id DESC
LIMIT 1
`

// Same, scoped to one PR instance: a preview never redeploys the production
// image (INV-010/INV-011).
func (q *Queries) GetCurrentPreviewArtifact(ctx context.Context, previewID *int64) (DeploymentArtifact, error) {
	row := q.db.QueryRow(ctx, getCurrentPreviewArtifact, previewID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeploymentID,
		&i.Kind,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ServerID,
		&i.RegistryCredentialID,
		&i.ProtectedFromCleanup,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, uuid, resource_id, status, attempt, retry_of_id, superseded_by_id, is_rollback, trigger, triggered_by, api_token_id, git_branch, commit_sha, is_local_source, context_digest, force_rebuild, image_name, image_tag, image_digest, config_snapshot, config_diff, error_message, server_id, build_server_id, queued_at, started_at, finished_at, created_at, updated_at, preview_id, commit_author, commit_message, skip_build FROM deployments WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Status,
		&i.Attempt,
		&i.RetryOfID,
		&i.SupersededByID,
		&i.IsRollback,
		&i.Trigger,
		&i.TriggeredBy,
		&i.ApiTokenID,
		&i.GitBranch,
		&i.CommitSha,
		&i.IsLocalSource,
		&i.ContextDigest,
		&i.ForceRebuild,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.ConfigDiff,
		&i.ErrorMessage,
		&i.ServerID,
		&i.BuildServerID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviewID,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.SkipBuild,
	)
	return i, err
}

const getDeploymentByUUIDForTeam = `-- name: GetDeploymentByUUIDForTeam :one
SELECT d.id, d.uuid, d.resource_id, d.status, d.attempt, d.retry_of_id, d.superseded_by_id, d.is_rollback, d.trigger, d.triggered_by, d.api_token_id, d.git_branch, d.commit_sha, d.is_local_source, d.context_digest, d.force_rebuild, d.image_name, d.image_tag, d.image_digest, d.config_snapshot, d.config_diff, d.error_message, d.server_id, d.build_server_id, d.queued_at, d.started_at, d.finished_at, d.created_at, d.updated_at, d.preview_id, d.commit_author, d.commit_message, d.skip_build, r.uuid AS resource_uuid, p.pr_id,
    a.git_repository_url, gs.provider AS git_provider
FROM deployments d
JOIN resources r ON r.id = d.resource_id
LEFT JOIN previews p ON p.id = d.preview_id
LEFT JOIN applications a ON a.id = d.resource_id
LEFT JOIN git_sources gs ON gs.id = a.git_source_id
WHERE d.uuid = $1 AND r.team_id = $2
`

type GetDeploymentByUUIDForTeamParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

type GetDeploymentByUUIDForTeamRow struct {
	Deployment       Deployment
	ResourceUuid     pgtype.UUID
	PrID             *int32
	GitRepositoryUrl *string
	GitProvider      *GitProvider
}

// The git repository URL and provider ride along (git source only) so the UI can
// link the branch, commit and PR back to the forge.
func (q *Queries) GetDeploymentByUUIDForTeam(ctx context.Context, arg GetDeploymentByUUIDForTeamParams) (GetDeploymentByUUIDForTeamRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentByUUIDForTeam, arg.Uuid, arg.TeamID)
	var i GetDeploymentByUUIDForTeamRow
	err := row.Scan(
		&i.Deployment.ID,
		&i.Deployment.Uuid,
		&i.Deployment.ResourceID,
		&i.Deployment.Status,
		&i.Deployment.Attempt,
		&i.Deployment.RetryOfID,
		&i.Deployment.SupersededByID,
		&i.Deployment.IsRollback,
		&i.Deployment.Trigger,
		&i.Deployment.TriggeredBy,
		&i.Deployment.ApiTokenID,
		&i.Deployment.GitBranch,
		&i.Deployment.CommitSha,
		&i.Deployment.IsLocalSource,
		&i.Deployment.ContextDigest,
		&i.Deployment.ForceRebuild,
		&i.Deployment.ImageName,
		&i.Deployment.ImageTag,
		&i.Deployment.ImageDigest,
		&i.Deployment.ConfigSnapshot,
		&i.Deployment.ConfigDiff,
		&i.Deployment.ErrorMessage,
		&i.Deployment.ServerID,
		&i.Deployment.BuildServerID,
		&i.Deployment.QueuedAt,
		&i.Deployment.StartedAt,
		&i.Deployment.FinishedAt,
		&i.Deployment.CreatedAt,
		&i.Deployment.UpdatedAt,
		&i.Deployment.PreviewID,
		&i.Deployment.CommitAuthor,
		&i.Deployment.CommitMessage,
		&i.Deployment.SkipBuild,
		&i.ResourceUuid,
		&i.PrID,
		&i.GitRepositoryUrl,
		&i.GitProvider,
	)
	return i, err
}

const getDeploymentStatus = `-- name: GetDeploymentStatus :one
SELECT status FROM deployments WHERE id = $1
`

func (q *Queries) GetDeploymentStatus(ctx context.Context, deploymentID int64) (DeploymentStatus, error) {
	row := q.db.QueryRow(ctx, getDeploymentStatus, deploymentID)
	var status DeploymentStatus
	err := row.Scan(&status)
	return status, err
}

const getLastSucceededDeployment = `-- name: GetLastSucceededDeployment :one
SELECT id, uuid, resource_id, status, attempt, retry_of_id, superseded_by_id, is_rollback, trigger, triggered_by, api_token_id, git_branch, commit_sha, is_local_source, context_digest, force_rebuild, image_name, image_tag, image_digest, config_snapshot, config_diff, error_message, server_id, build_server_id, queued_at, started_at, finished_at, created_at, updated_at, preview_id, commit_author, commit_message, skip_build FROM deployments
WHERE resource_id = $1 AND preview_id IS NULL AND status = 'succeeded'
ORDER BY id DESC
LIMIT 1
`

// What the application currently runs. A skip_build deployment (ADR-048)
// inherits its commit: it applies a configuration, never a new commit.
func (q *Queries) GetLastSucceededDeployment(ctx context.Context, resourceID int64) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLastSucceededDeployment, resourceID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Status,
		&i.Attempt,
		&i.RetryOfID,
		&i.SupersededByID,
		&i.IsRollback,
		&i.Trigger,
		&i.TriggeredBy,
		&i.ApiTokenID,
		&i.GitBranch,
		&i.CommitSha,
		&i.IsLocalSource,
		&i.ContextDigest,
		&i.ForceRebuild,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.ConfigDiff,
		&i.ErrorMessage,
		&i.ServerID,
		&i.BuildServerID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviewID,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.SkipBuild,
	)
	return i, err
}

const getLastSucceededPreviewDeployment = `-- name: GetLastSucceededPreviewDeployment :one
SELECT id, uuid, resource_id, status, attempt, retry_of_id, superseded_by_id, is_rollback, trigger, triggered_by, api_token_id, git_branch, commit_sha, is_local_source, context_digest, force_rebuild, image_name, image_tag, image_digest, config_snapshot, config_diff, error_message, server_id, build_server_id, queued_at, started_at, finished_at, created_at, updated_at, preview_id, commit_author, commit_message, skip_build FROM deployments
WHERE preview_id = $1 AND status = 'succeeded'
ORDER BY id DESC
LIMIT 1
`

// Same, for one PR instance — pinned to the head SHA that instance runs.
func (q *Queries) GetLastSucceededPreviewDeployment(ctx context.Context, previewID *int64) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLastSucceededPreviewDeployment, previewID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Status,
		&i.Attempt,
		&i.RetryOfID,
		&i.SupersededByID,
		&i.IsRollback,
		&i.Trigger,
		&i.TriggeredBy,
		&i.ApiTokenID,
		&i.GitBranch,
		&i.CommitSha,
		&i.IsLocalSource,
		&i.ContextDigest,
		&i.ForceRebuild,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.ConfigDiff,
		&i.ErrorMessage,
		&i.ServerID,
		&i.BuildServerID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviewID,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.SkipBuild,
	)
	return i, err
}

const getPreviousArtifact = `-- name: GetPreviousArtifact :one
SELECT a.id, a.uuid, a.deployment_id, a.kind, a.image_name, a.image_tag, a.image_digest, a.server_id, a.registry_credential_id, a.protected_from_cleanup, a.created_at FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE d.resource_id = $1 AND d.status = 'succeeded'
  AND d.id < (SELECT max(id) FROM deployments WHERE resource_id = $1 AND status = 'succeeded')
ORDER BY a.id DESC
LIMIT 1
`

// The most recent artifact of a successful deployment other than the one
// currently serving traffic (the last succeeded deployment).
func (q *Queries) GetPreviousArtifact(ctx context.Context, resourceID int64) (DeploymentArtifact, error) {
	row := q.db.QueryRow(ctx, getPreviousArtifact, resourceID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeploymentID,
		&i.Kind,
		&i.ImageName,
		&i.ImageTag,
		&i.ImageDigest,
		&i.ServerID,
		&i.RegistryCredentialID,
		&i.ProtectedFromCleanup,
		&i.CreatedAt,
	)
	return i, err
}

const listAppArtifactsOnServer = `-- name: ListAppArtifactsOnServer :many
SELECT a.id, a.image_name, a.image_tag
FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE d.resource_id = $1 AND d.preview_id IS NULL AND d.status = 'succeeded'
  AND a.server_id = $2 AND a.image_tag IS NOT NULL
ORDER BY a.id DESC
`

type ListAppArtifactsOnServerParams struct {
	ResourceID int64
	ServerID   *int64
}

type ListAppArtifactsOnServerRow struct {
	ID        int64
	ImageName string
	ImageTag  *string
}

// Every local rollback image of the application (non-preview deployments) on
// one server, newest first — the caller keeps the N most recent and reclaims
// the rest (ADR-006 retention, §29.4). The live image is the newest here, so a
// retention >= 1 always protects it.
func (q *Queries) ListAppArtifactsOnServer(ctx context.Context, arg ListAppArtifactsOnServerParams) ([]ListAppArtifactsOnServerRow, error) {
	rows, err := q.db.Query(ctx, listAppArtifactsOnServer, arg.ResourceID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppArtifactsOnServerRow
	for rows.Next() {
		var i ListAppArtifactsOnServerRow
		if err := rows.Scan(&i.ID, &i.ImageName, &i.ImageTag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentSteps = `-- name: ListDeploymentSteps :many
SELECT id, deployment_id, seq, name, status, exit_code, log, started_at, finished_at, created_at FROM deployment_steps WHERE deployment_id = $1 ORDER BY seq
`

func (q *Queries) ListDeploymentSteps(ctx context.Context, deploymentID int64) ([]DeploymentStep, error) {
	rows, err := q.db.Query(ctx, listDeploymentSteps, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentStep
	for rows.Next() {
		var i DeploymentStep
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Seq,
			&i.Name,
			&i.Status,
			&i.ExitCode,
			&i.Log,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForResource = `-- name: ListDeploymentsForResource :many
SELECT d.id, d.uuid, d.resource_id, d.status, d.attempt, d.retry_of_id, d.superseded_by_id, d.is_rollback, d.trigger, d.triggered_by, d.api_token_id, d.git_branch, d.commit_sha, d.is_local_source, d.context_digest, d.force_rebuild, d.image_name, d.image_tag, d.image_digest, d.config_snapshot, d.config_diff, d.error_message, d.server_id, d.build_server_id, d.queued_at, d.started_at, d.finished_at, d.created_at, d.updated_at, d.preview_id, d.commit_author, d.commit_message, d.skip_build, p.pr_id FROM deployments d
LEFT JOIN previews p ON p.id = d.preview_id
WHERE d.resource_id = $1
  AND ($2::deployment_status IS NULL OR d.status = $2)
  AND ($3::bigint = 0 OR d.id < $3)
ORDER BY d.id DESC
LIMIT $4
`

type ListDeploymentsForResourceParams struct {
	ResourceID int64
	Status     *DeploymentStatus
	AfterID    int64
	PageLimit  int32
}

type ListDeploymentsForResourceRow struct {
	Deployment Deployment
	PrID       *int32
}

// The preview's PR number (NULL for a production deployment) rides along so the
// UI can say "preview #N" instead of a bare "preview".
func (q *Queries) ListDeploymentsForResource(ctx context.Context, arg ListDeploymentsForResourceParams) ([]ListDeploymentsForResourceRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForResource,
		arg.ResourceID,
		arg.Status,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsForResourceRow
	for rows.Next() {
		var i ListDeploymentsForResourceRow
		if err := rows.Scan(
			&i.Deployment.ID,
			&i.Deployment.Uuid,
			&i.Deployment.ResourceID,
			&i.Deployment.Status,
			&i.Deployment.Attempt,
			&i.Deployment.RetryOfID,
			&i.Deployment.SupersededByID,
			&i.Deployment.IsRollback,
			&i.Deployment.Trigger,
			&i.Deployment.TriggeredBy,
			&i.Deployment.ApiTokenID,
			&i.Deployment.GitBranch,
			&i.Deployment.CommitSha,
			&i.Deployment.IsLocalSource,
			&i.Deployment.ContextDigest,
			&i.Deployment.ForceRebuild,
			&i.Deployment.ImageName,
			&i.Deployment.ImageTag,
			&i.Deployment.ImageDigest,
			&i.Deployment.ConfigSnapshot,
			&i.Deployment.ConfigDiff,
			&i.Deployment.ErrorMessage,
			&i.Deployment.ServerID,
			&i.Deployment.BuildServerID,
			&i.Deployment.QueuedAt,
			&i.Deployment.StartedAt,
			&i.Deployment.FinishedAt,
			&i.Deployment.CreatedAt,
			&i.Deployment.UpdatedAt,
			&i.Deployment.PreviewID,
			&i.Deployment.CommitAuthor,
			&i.Deployment.CommitMessage,
			&i.Deployment.SkipBuild,
			&i.PrID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewArtifactsOnServer = `-- name: ListPreviewArtifactsOnServer :many
SELECT a.id, a.image_name, a.image_tag
FROM deployment_artifacts a
JOIN deployments d ON d.id = a.deployment_id
WHERE d.preview_id = $1 AND d.status = 'succeeded'
  AND a.server_id = $2 AND a.image_tag IS NOT NULL
ORDER BY a.id DESC
`

type ListPreviewArtifactsOnServerParams struct {
	PreviewID *int64
	ServerID  *int64
}

type ListPreviewArtifactsOnServerRow struct {
	ID        int64
	ImageName string
	ImageTag  *string
}

// Same, scoped to one preview: its images live under akerdock/<preview_uuid>,
// a namespace distinct from production (deployment engine §5.7).
func (q *Queries) ListPreviewArtifactsOnServer(ctx context.Context, arg ListPreviewArtifactsOnServerParams) ([]ListPreviewArtifactsOnServerRow, error) {
	rows, err := q.db.Query(ctx, listPreviewArtifactsOnServer, arg.PreviewID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreviewArtifactsOnServerRow
	for rows.Next() {
		var i ListPreviewArtifactsOnServerRow
		if err := rows.Scan(&i.ID, &i.ImageName, &i.ImageTag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDeploymentStepSeq = `-- name: MaxDeploymentStepSeq :one
SELECT coalesce(max(seq), 0)::int AS max_seq FROM deployment_steps WHERE deployment_id = $1
`

// A resumed deployment continues the step numbering of the attempt that
// crashed: restarting at 1 would collide with the steps already recorded, and
// would also erase the history of what the dead worker had done.
func (q *Queries) MaxDeploymentStepSeq(ctx context.Context, deploymentID int64) (int32, error) {
	row := q.db.QueryRow(ctx, maxDeploymentStepSeq, deploymentID)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const setDeploymentCommit = `-- name: SetDeploymentCommit :exec
UPDATE deployments SET commit_sha = $2, git_branch = $3, updated_at = now() WHERE id = $1
`

type SetDeploymentCommitParams struct {
	ID        int64
	CommitSha *string
	GitBranch *string
}

func (q *Queries) SetDeploymentCommit(ctx context.Context, arg SetDeploymentCommitParams) error {
	_, err := q.db.Exec(ctx, setDeploymentCommit, arg.ID, arg.CommitSha, arg.GitBranch)
	return err
}

const setDeploymentCommitMeta = `-- name: SetDeploymentCommitMeta :exec
UPDATE deployments SET
    commit_author = COALESCE($2, commit_author),
    commit_message = COALESCE($3, commit_message),
    updated_at = now()
WHERE id = $1
`

type SetDeploymentCommitMetaParams struct {
	ID            int64
	CommitAuthor  *string
	CommitMessage *string
}

// Author name and subject of the resolved commit, read on the build server
// after checkout — surfaces "who last pushed" in the deployment view. Best
// effort: a missing value leaves the column untouched.
func (q *Queries) SetDeploymentCommitMeta(ctx context.Context, arg SetDeploymentCommitMetaParams) error {
	_, err := q.db.Exec(ctx, setDeploymentCommitMeta, arg.ID, arg.CommitAuthor, arg.CommitMessage)
	return err
}

const setDeploymentError = `-- name: SetDeploymentError :exec
UPDATE deployments SET error_message = $2, updated_at = now() WHERE id = $1
`

type SetDeploymentErrorParams struct {
	ID           int64
	ErrorMessage *string
}

func (q *Queries) SetDeploymentError(ctx context.Context, arg SetDeploymentErrorParams) error {
	_, err := q.db.Exec(ctx, setDeploymentError, arg.ID, arg.ErrorMessage)
	return err
}

const setDeploymentImage = `-- name: SetDeploymentImage :exec
UPDATE deployments SET image_name = $2, image_tag = $3, updated_at = now() WHERE id = $1
`

type SetDeploymentImageParams struct {
	ID        int64
	ImageName *string
	ImageTag  *string
}

func (q *Queries) SetDeploymentImage(ctx context.Context, arg SetDeploymentImageParams) error {
	_, err := q.db.Exec(ctx, setDeploymentImage, arg.ID, arg.ImageName, arg.ImageTag)
	return err
}

const setDeploymentImageDigest = `-- name: SetDeploymentImageDigest :exec
UPDATE deployments SET image_digest = $2, updated_at = now() WHERE id = $1
`

type SetDeploymentImageDigestParams struct {
	ID          int64
	ImageDigest *string
}

func (q *Queries) SetDeploymentImageDigest(ctx context.Context, arg SetDeploymentImageDigestParams) error {
	_, err := q.db.Exec(ctx, setDeploymentImageDigest, arg.ID, arg.ImageDigest)
	return err
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments SET status = $2,
    started_at = CASE WHEN started_at IS NULL AND $2 <> 'queued'::deployment_status THEN now() ELSE started_at END,
    finished_at = CASE WHEN $2 IN ('succeeded'::deployment_status, 'failed'::deployment_status, 'cancelled'::deployment_status) THEN now() ELSE finished_at END,
    updated_at = now()
WHERE id = $1
`

type SetDeploymentStatusParams struct {
	ID     int64
	Status DeploymentStatus
}

func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, setDeploymentStatus, arg.ID, arg.Status)
	return err
}

const setDeploymentStepLog = `-- name: SetDeploymentStepLog :exec
UPDATE deployment_steps SET log = $2 WHERE id = $1
`

type SetDeploymentStepLogParams struct {
	ID  int64
	Log *string
}

// Live output of a RUNNING step (docker build, container start): the SSE log
// stream polls the steps every second, so refreshing the log as the command
// runs is what turns "step build: started … (silence)" into a console.
func (q *Queries) SetDeploymentStepLog(ctx context.Context, arg SetDeploymentStepLogParams) error {
	_, err := q.db.Exec(ctx, setDeploymentStepLog, arg.ID, arg.Log)
	return err
}

const startDeploymentUnlessCleanupRunning = `-- name: StartDeploymentUnlessCleanupRunning :execrows
WITH locked_server AS MATERIALIZED (
    SELECT s.id
    FROM servers s
    JOIN deployments d ON d.server_id = s.id
    WHERE d.id = $1
    FOR UPDATE OF s
)
UPDATE deployments d
SET status = 'preparing',
    started_at = coalesce(started_at, now()),
    updated_at = now()
FROM locked_server s
WHERE d.id = $1
  AND d.status = 'queued'
  AND NOT EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.job_type = 'server.cleanup'
        AND j.status IN ('leased', 'running')
        AND j.payload->>'server_id' = s.id::text
  )
`

// Atomic counterpart of CanStartServerCleanup. The first deployment
// transition and the cleanup guard serialize on the same server row. A
// cleanup is identified from the durable job itself, so a worker crash keeps
// deployments out until its lease is reaped; no in-memory mutex can provide
// that guarantee across replicas.
func (q *Queries) StartDeploymentUnlessCleanupRunning(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, startDeploymentUnlessCleanupRunning, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeQueuedDeployments = `-- name: SupersedeQueuedDeployments :many
UPDATE deployments SET status = 'superseded', superseded_by_id = $2,
    finished_at = now(), updated_at = now()
WHERE resource_id = $1 AND status = 'queued' AND trigger = 'webhook' AND id <> $2
RETURNING id
`

type SupersedeQueuedDeploymentsParams struct {
	ResourceID     int64
	SupersededByID *int64
}

// Coalescing (§3.4): a queued webhook deployment for the same application
// is superseded by a newer one; an already leased/running deployment is
// never coalesced.
func (q *Queries) SupersedeQueuedDeployments(ctx context.Context, arg SupersedeQueuedDeploymentsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, supersedeQueuedDeployments, arg.ResourceID, arg.SupersededByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
