// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: env_vars.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvVar = `-- name: CreateEnvVar :one

INSERT INTO environment_variables (uuid, resource_id, key, value_enc, is_build_time, is_literal, is_multiline, is_locked, is_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at
`

type CreateEnvVarParams struct {
	Uuid        pgtype.UUID
	ResourceID  int64
	Key         string
	ValueEnc    []byte
	IsBuildTime bool
	IsLiteral   bool
	IsMultiline bool
	IsLocked    bool
	IsSecret    bool
}

// Environment variables (§5.4): the production set (is_preview = false)
// for the v1 endpoints; the preview set lands with previews.
func (q *Queries) CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, createEnvVar,
		arg.Uuid,
		arg.ResourceID,
		arg.Key,
		arg.ValueEnc,
		arg.IsBuildTime,
		arg.IsLiteral,
		arg.IsMultiline,
		arg.IsLocked,
		arg.IsSecret,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Key,
		&i.ValueEnc,
		&i.IsSecret,
		&i.IsBuildTime,
		&i.IsLiteral,
		&i.IsMultiline,
		&i.IsLocked,
		&i.IsPreview,
		&i.IsGenerated,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGeneratedEnvVar = `-- name: CreateGeneratedEnvVar :execrows
INSERT INTO environment_variables (uuid, resource_id, key, value_enc, is_secret, is_generated)
VALUES ($1, $2, $3, $4, $5, true)
ON CONFLICT (resource_id, key, is_preview) DO NOTHING
`

type CreateGeneratedEnvVarParams struct {
	Uuid       pgtype.UUID
	ResourceID int64
	Key        string
	ValueEnc   []byte
	IsSecret   bool
}

// Magic variables (compose-spec §4.3): written at first use, is_generated,
// never regenerated while the row exists — the conflict target guarantees it.
func (q *Queries) CreateGeneratedEnvVar(ctx context.Context, arg CreateGeneratedEnvVarParams) (int64, error) {
	result, err := q.db.Exec(ctx, createGeneratedEnvVar,
		arg.Uuid,
		arg.ResourceID,
		arg.Key,
		arg.ValueEnc,
		arg.IsSecret,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGeneratedPreviewEnvVar = `-- name: CreateGeneratedPreviewEnvVar :execrows
INSERT INTO environment_variables (uuid, resource_id, key, value_enc, is_secret, is_generated, is_preview)
VALUES ($1, $2, $3, $4, true, true, true)
ON CONFLICT (resource_id, key, is_preview) DO NOTHING
`

type CreateGeneratedPreviewEnvVarParams struct {
	Uuid       pgtype.UUID
	ResourceID int64
	Key        string
	ValueEnc   []byte
}

// Generated secret of the PREVIEW variable set (§20.4.4) — e.g. the basic
// auth credential. Same one-shot semantics as the magic variables.
func (q *Queries) CreateGeneratedPreviewEnvVar(ctx context.Context, arg CreateGeneratedPreviewEnvVarParams) (int64, error) {
	result, err := q.db.Exec(ctx, createGeneratedPreviewEnvVar,
		arg.Uuid,
		arg.ResourceID,
		arg.Key,
		arg.ValueEnc,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEnvVar = `-- name: DeleteEnvVar :execrows
DELETE FROM environment_variables WHERE id = $1
`

func (q *Queries) DeleteEnvVar(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvVar, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEnvVarsNotInKeys = `-- name: DeleteEnvVarsNotInKeys :exec
DELETE FROM environment_variables
WHERE resource_id = $1 AND is_preview = false AND NOT is_locked
  AND key <> ALL($2::text[])
`

type DeleteEnvVarsNotInKeysParams struct {
	ResourceID int64
	Keys       []string
}

func (q *Queries) DeleteEnvVarsNotInKeys(ctx context.Context, arg DeleteEnvVarsNotInKeysParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVarsNotInKeys, arg.ResourceID, arg.Keys)
	return err
}

const getEnvVarByKey = `-- name: GetEnvVarByKey :one
SELECT id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at FROM environment_variables
WHERE resource_id = $1 AND key = $2 AND is_preview = false
`

type GetEnvVarByKeyParams struct {
	ResourceID int64
	Key        string
}

func (q *Queries) GetEnvVarByKey(ctx context.Context, arg GetEnvVarByKeyParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, getEnvVarByKey, arg.ResourceID, arg.Key)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Key,
		&i.ValueEnc,
		&i.IsSecret,
		&i.IsBuildTime,
		&i.IsLiteral,
		&i.IsMultiline,
		&i.IsLocked,
		&i.IsPreview,
		&i.IsGenerated,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvVarByUUID = `-- name: GetEnvVarByUUID :one
SELECT id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at FROM environment_variables WHERE uuid = $1 AND resource_id = $2
`

type GetEnvVarByUUIDParams struct {
	Uuid       pgtype.UUID
	ResourceID int64
}

func (q *Queries) GetEnvVarByUUID(ctx context.Context, arg GetEnvVarByUUIDParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, getEnvVarByUUID, arg.Uuid, arg.ResourceID)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Key,
		&i.ValueEnc,
		&i.IsSecret,
		&i.IsBuildTime,
		&i.IsLiteral,
		&i.IsMultiline,
		&i.IsLocked,
		&i.IsPreview,
		&i.IsGenerated,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvVarsForDeploy = `-- name: ListEnvVarsForDeploy :many
SELECT id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at FROM environment_variables
WHERE resource_id = $1 AND is_preview = false
ORDER BY key
`

func (q *Queries) ListEnvVarsForDeploy(ctx context.Context, resourceID int64) ([]EnvironmentVariable, error) {
	rows, err := q.db.Query(ctx, listEnvVarsForDeploy, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentVariable
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ResourceID,
			&i.Key,
			&i.ValueEnc,
			&i.IsSecret,
			&i.IsBuildTime,
			&i.IsLiteral,
			&i.IsMultiline,
			&i.IsLocked,
			&i.IsPreview,
			&i.IsGenerated,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarsPage = `-- name: ListEnvVarsPage :many
SELECT id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at FROM environment_variables
WHERE resource_id = $1 AND is_preview = $2
  AND ($3::bigint = 0 OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListEnvVarsPageParams struct {
	ResourceID int64
	IsPreview  bool
	AfterID    int64
	PageLimit  int32
}

// The production set by default; the dedicated preview set on demand (§5.6):
// the platform-generated preview credentials live there, and an operator who
// cannot read them cannot open their own protected preview.
func (q *Queries) ListEnvVarsPage(ctx context.Context, arg ListEnvVarsPageParams) ([]EnvironmentVariable, error) {
	rows, err := q.db.Query(ctx, listEnvVarsPage,
		arg.ResourceID,
		arg.IsPreview,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentVariable
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ResourceID,
			&i.Key,
			&i.ValueEnc,
			&i.IsSecret,
			&i.IsBuildTime,
			&i.IsLiteral,
			&i.IsMultiline,
			&i.IsLocked,
			&i.IsPreview,
			&i.IsGenerated,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvVar = `-- name: UpdateEnvVar :one
UPDATE environment_variables
SET value_enc = $2, is_build_time = $3, is_literal = $4, is_multiline = $5, is_locked = $6, updated_at = now()
WHERE id = $1
RETURNING id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at
`

type UpdateEnvVarParams struct {
	ID          int64
	ValueEnc    []byte
	IsBuildTime bool
	IsLiteral   bool
	IsMultiline bool
	IsLocked    bool
}

func (q *Queries) UpdateEnvVar(ctx context.Context, arg UpdateEnvVarParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, updateEnvVar,
		arg.ID,
		arg.ValueEnc,
		arg.IsBuildTime,
		arg.IsLiteral,
		arg.IsMultiline,
		arg.IsLocked,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Key,
		&i.ValueEnc,
		&i.IsSecret,
		&i.IsBuildTime,
		&i.IsLiteral,
		&i.IsMultiline,
		&i.IsLocked,
		&i.IsPreview,
		&i.IsGenerated,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
