// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: externalendpoints.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpointPortForwardSession = `-- name: CreateEndpointPortForwardSession :one
INSERT INTO port_forward_sessions (
    team_id, user_id, server_id, external_endpoint_id, grant_id, target_name,
    target_port, client_ip, token_hash, token_expires_at, authorized_until
) VALUES (
    $1, $8, $2, $3, $9, $4,
    $5, $10, $6, $7, $11
)
RETURNING id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at, external_endpoint_id, grant_id, authorized_until, last_heartbeat_at, attach_key_hash, attach_seq
`

type CreateEndpointPortForwardSessionParams struct {
	TeamID             int64
	ServerID           *int64
	ExternalEndpointID *int64
	TargetName         string
	TargetPort         int32
	TokenHash          string
	TokenExpiresAt     pgtype.Timestamptz
	UserID             *int64
	GrantID            *int64
	ClientIp           *netip.Addr
	AuthorizedUntil    pgtype.Timestamptz
}

// The endpoint variant of CreatePortForwardSession: no resource, no preview,
// and an explicit `authorized_until` — the instant the session is actually cut,
// which the CLI is told at open and reminded of before it lands.
func (q *Queries) CreateEndpointPortForwardSession(ctx context.Context, arg CreateEndpointPortForwardSessionParams) (PortForwardSession, error) {
	row := q.db.QueryRow(ctx, createEndpointPortForwardSession,
		arg.TeamID,
		arg.ServerID,
		arg.ExternalEndpointID,
		arg.TargetName,
		arg.TargetPort,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.UserID,
		arg.GrantID,
		arg.ClientIp,
		arg.AuthorizedUntil,
	)
	var i PortForwardSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.ServerID,
		&i.ResourceID,
		&i.PreviewID,
		&i.TargetName,
		&i.TargetComponent,
		&i.TargetPort,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
		&i.ExternalEndpointID,
		&i.GrantID,
		&i.AuthorizedUntil,
		&i.LastHeartbeatAt,
		&i.AttachKeyHash,
		&i.AttachSeq,
	)
	return i, err
}

const createExternalEndpoint = `-- name: CreateExternalEndpoint :one

INSERT INTO external_endpoints (
    team_id, name, description, host, port, server_id,
    project_id, environment_id, criticality, max_grant_minutes, created_by
) VALUES (
    $1, $2, $8, $3, $4, $5,
    $9, $10, $6, $7, $11
)
RETURNING id, uuid, team_id, name, description, host, port, server_id, project_id, environment_id, criticality, max_grant_minutes, created_by, updated_by, created_at, updated_at, version
`

type CreateExternalEndpointParams struct {
	TeamID          int64
	Name            string
	Host            string
	Port            int32
	ServerID        int64
	Criticality     ExternalEndpointCriticality
	MaxGrantMinutes int32
	Description     *string
	ProjectID       *int64
	EnvironmentID   *int64
	CreatedBy       *int64
}

// External endpoints and their access grants (ADR-045): declared bastion
// targets, and the bounded re-authenticated windows during which a user may
// mint tunnels to them.
func (q *Queries) CreateExternalEndpoint(ctx context.Context, arg CreateExternalEndpointParams) (ExternalEndpoint, error) {
	row := q.db.QueryRow(ctx, createExternalEndpoint,
		arg.TeamID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.ServerID,
		arg.Criticality,
		arg.MaxGrantMinutes,
		arg.Description,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.CreatedBy,
	)
	var i ExternalEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.ServerID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Criticality,
		&i.MaxGrantMinutes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createExternalEndpointGrant = `-- name: CreateExternalEndpointGrant :one
INSERT INTO external_endpoint_grants (
    endpoint_id, user_id, reason, factor, granted_by, renewed_from, expires_at
) VALUES (
    $1, $2, $3, $4, $6, $7, $5
)
RETURNING id, uuid, endpoint_id, user_id, reason, factor, granted_by, renewed_from, requested_at, expires_at, revoked_at, revoked_by, created_at
`

type CreateExternalEndpointGrantParams struct {
	EndpointID  int64
	UserID      int64
	Reason      string
	Factor      string
	ExpiresAt   pgtype.Timestamptz
	GrantedBy   *int64
	RenewedFrom *int64
}

// A grant is only ever created behind a fresh second factor; `factor` records
// which one was consumed, and `renewed_from` chains a renewal to the grant it
// extended so a long chain stays visible in the audit trail.
func (q *Queries) CreateExternalEndpointGrant(ctx context.Context, arg CreateExternalEndpointGrantParams) (ExternalEndpointGrant, error) {
	row := q.db.QueryRow(ctx, createExternalEndpointGrant,
		arg.EndpointID,
		arg.UserID,
		arg.Reason,
		arg.Factor,
		arg.ExpiresAt,
		arg.GrantedBy,
		arg.RenewedFrom,
	)
	var i ExternalEndpointGrant
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EndpointID,
		&i.UserID,
		&i.Reason,
		&i.Factor,
		&i.GrantedBy,
		&i.RenewedFrom,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExternalEndpoint = `-- name: DeleteExternalEndpoint :execrows
DELETE FROM external_endpoints WHERE id = $1 AND team_id = $2
`

type DeleteExternalEndpointParams struct {
	ID     int64
	TeamID int64
}

func (q *Queries) DeleteExternalEndpoint(ctx context.Context, arg DeleteExternalEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExternalEndpoint, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendExternalEndpointGrant = `-- name: ExtendExternalEndpointGrant :one
UPDATE external_endpoint_grants
SET expires_at = $2, reason = $3, factor = $4, requested_at = now()
WHERE id = $1 AND revoked_at IS NULL AND expires_at > now()
RETURNING id, uuid, endpoint_id, user_id, reason, factor, granted_by, renewed_from, requested_at, expires_at, revoked_at, revoked_by, created_at
`

type ExtendExternalEndpointGrantParams struct {
	ID        int64
	ExpiresAt pgtype.Timestamptz
	Reason    string
	Factor    string
}

// Renewal pushes back an existing window in place. Guarded on the row still
// being live: a grant that expired between the ceremony and this statement is
// not renewable, it is a new request (ADR-045 §5).
func (q *Queries) ExtendExternalEndpointGrant(ctx context.Context, arg ExtendExternalEndpointGrantParams) (ExternalEndpointGrant, error) {
	row := q.db.QueryRow(ctx, extendExternalEndpointGrant,
		arg.ID,
		arg.ExpiresAt,
		arg.Reason,
		arg.Factor,
	)
	var i ExternalEndpointGrant
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EndpointID,
		&i.UserID,
		&i.Reason,
		&i.Factor,
		&i.GrantedBy,
		&i.RenewedFrom,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalEndpointByID = `-- name: GetExternalEndpointByID :one
SELECT id, uuid, team_id, name, description, host, port, server_id, project_id, environment_id, criticality, max_grant_minutes, created_by, updated_by, created_at, updated_at, version FROM external_endpoints WHERE id = $1
`

func (q *Queries) GetExternalEndpointByID(ctx context.Context, id int64) (ExternalEndpoint, error) {
	row := q.db.QueryRow(ctx, getExternalEndpointByID, id)
	var i ExternalEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.ServerID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Criticality,
		&i.MaxGrantMinutes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getExternalEndpointByUUID = `-- name: GetExternalEndpointByUUID :one
SELECT id, uuid, team_id, name, description, host, port, server_id, project_id, environment_id, criticality, max_grant_minutes, created_by, updated_by, created_at, updated_at, version FROM external_endpoints WHERE uuid = $1 AND team_id = $2
`

type GetExternalEndpointByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetExternalEndpointByUUID(ctx context.Context, arg GetExternalEndpointByUUIDParams) (ExternalEndpoint, error) {
	row := q.db.QueryRow(ctx, getExternalEndpointByUUID, arg.Uuid, arg.TeamID)
	var i ExternalEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.ServerID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Criticality,
		&i.MaxGrantMinutes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getExternalEndpointGrantByUUID = `-- name: GetExternalEndpointGrantByUUID :one
SELECT id, uuid, endpoint_id, user_id, reason, factor, granted_by, renewed_from, requested_at, expires_at, revoked_at, revoked_by, created_at FROM external_endpoint_grants WHERE uuid = $1
`

func (q *Queries) GetExternalEndpointGrantByUUID(ctx context.Context, uuid pgtype.UUID) (ExternalEndpointGrant, error) {
	row := q.db.QueryRow(ctx, getExternalEndpointGrantByUUID, uuid)
	var i ExternalEndpointGrant
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EndpointID,
		&i.UserID,
		&i.Reason,
		&i.Factor,
		&i.GrantedBy,
		&i.RenewedFrom,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLiveExternalEndpointGrant = `-- name: GetLiveExternalEndpointGrant :one
SELECT id, uuid, endpoint_id, user_id, reason, factor, granted_by, renewed_from, requested_at, expires_at, revoked_at, revoked_by, created_at FROM external_endpoint_grants
WHERE endpoint_id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY expires_at DESC
LIMIT 1
`

type GetLiveExternalEndpointGrantParams struct {
	EndpointID int64
	UserID     int64
}

// The hot path on every mint: the caller's own live grant on this endpoint.
// Revoked and expired rows are invisible here, which is what makes revocation
// and expiry take effect without a sweep.
func (q *Queries) GetLiveExternalEndpointGrant(ctx context.Context, arg GetLiveExternalEndpointGrantParams) (ExternalEndpointGrant, error) {
	row := q.db.QueryRow(ctx, getLiveExternalEndpointGrant, arg.EndpointID, arg.UserID)
	var i ExternalEndpointGrant
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EndpointID,
		&i.UserID,
		&i.Reason,
		&i.Factor,
		&i.GrantedBy,
		&i.RenewedFrom,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listExternalEndpointGrantsPage = `-- name: ListExternalEndpointGrantsPage :many
SELECT g.id, g.uuid, g.endpoint_id, g.user_id, g.reason, g.factor, g.granted_by, g.renewed_from, g.requested_at, g.expires_at, g.revoked_at, g.revoked_by, g.created_at, u.email AS user_email
FROM external_endpoint_grants g
JOIN users u ON u.id = g.user_id
WHERE g.endpoint_id = $1 AND g.id < $2::bigint
ORDER BY g.id DESC
LIMIT $3::int
`

type ListExternalEndpointGrantsPageParams struct {
	EndpointID int64
	BeforeID   int64
	PageLimit  int32
}

type ListExternalEndpointGrantsPageRow struct {
	ID          int64
	Uuid        pgtype.UUID
	EndpointID  int64
	UserID      int64
	Reason      string
	Factor      string
	GrantedBy   *int64
	RenewedFrom *int64
	RequestedAt pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	RevokedBy   *int64
	CreatedAt   pgtype.Timestamptz
	UserEmail   string
}

// Newest first: the audit question is almost always "who has access right
// now", so the cursor walks ids downwards.
func (q *Queries) ListExternalEndpointGrantsPage(ctx context.Context, arg ListExternalEndpointGrantsPageParams) ([]ListExternalEndpointGrantsPageRow, error) {
	rows, err := q.db.Query(ctx, listExternalEndpointGrantsPage, arg.EndpointID, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExternalEndpointGrantsPageRow
	for rows.Next() {
		var i ListExternalEndpointGrantsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EndpointID,
			&i.UserID,
			&i.Reason,
			&i.Factor,
			&i.GrantedBy,
			&i.RenewedFrom,
			&i.RequestedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalEndpointsPage = `-- name: ListExternalEndpointsPage :many
SELECT id, uuid, team_id, name, description, host, port, server_id, project_id, environment_id, criticality, max_grant_minutes, created_by, updated_by, created_at, updated_at, version FROM external_endpoints
WHERE team_id = $1 AND id > $2::bigint
ORDER BY id
LIMIT $3::int
`

type ListExternalEndpointsPageParams struct {
	TeamID    int64
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListExternalEndpointsPage(ctx context.Context, arg ListExternalEndpointsPageParams) ([]ExternalEndpoint, error) {
	rows, err := q.db.Query(ctx, listExternalEndpointsPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalEndpoint
	for rows.Next() {
		var i ExternalEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Host,
			&i.Port,
			&i.ServerID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Criticality,
			&i.MaxGrantMinutes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePortForwardSessionsByGrant = `-- name: ListLivePortForwardSessionsByGrant :many
SELECT id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at, external_endpoint_id, grant_id, authorized_until, last_heartbeat_at, attach_key_hash, attach_seq FROM port_forward_sessions
WHERE grant_id = $1 AND ended_at IS NULL
`

// Revoking a grant tears down the sessions it opened; this is that set.
func (q *Queries) ListLivePortForwardSessionsByGrant(ctx context.Context, grantID *int64) ([]PortForwardSession, error) {
	rows, err := q.db.Query(ctx, listLivePortForwardSessionsByGrant, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortForwardSession
	for rows.Next() {
		var i PortForwardSession
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.UserID,
			&i.ServerID,
			&i.ResourceID,
			&i.PreviewID,
			&i.TargetName,
			&i.TargetComponent,
			&i.TargetPort,
			&i.ClientIp,
			&i.TokenHash,
			&i.TokenExpiresAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.CreatedAt,
			&i.ExternalEndpointID,
			&i.GrantID,
			&i.AuthorizedUntil,
			&i.LastHeartbeatAt,
			&i.AttachKeyHash,
			&i.AttachSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeExternalEndpointGrant = `-- name: RevokeExternalEndpointGrant :one
UPDATE external_endpoint_grants
SET revoked_at = now(), revoked_by = $2
WHERE uuid = $1 AND revoked_at IS NULL
RETURNING id, uuid, endpoint_id, user_id, reason, factor, granted_by, renewed_from, requested_at, expires_at, revoked_at, revoked_by, created_at
`

type RevokeExternalEndpointGrantParams struct {
	Uuid      pgtype.UUID
	RevokedBy *int64
}

func (q *Queries) RevokeExternalEndpointGrant(ctx context.Context, arg RevokeExternalEndpointGrantParams) (ExternalEndpointGrant, error) {
	row := q.db.QueryRow(ctx, revokeExternalEndpointGrant, arg.Uuid, arg.RevokedBy)
	var i ExternalEndpointGrant
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EndpointID,
		&i.UserID,
		&i.Reason,
		&i.Factor,
		&i.GrantedBy,
		&i.RenewedFrom,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const setPortForwardAuthorizedUntil = `-- name: SetPortForwardAuthorizedUntil :exec
UPDATE port_forward_sessions
SET authorized_until = $2
WHERE id = $1 AND ended_at IS NULL
`

type SetPortForwardAuthorizedUntilParams struct {
	ID              int64
	AuthorizedUntil pgtype.Timestamptz
}

// A renewed grant pushes back the deadline of the sessions it opened, so a
// transfer in flight survives instead of restarting from zero (ADR-045 §5).
func (q *Queries) SetPortForwardAuthorizedUntil(ctx context.Context, arg SetPortForwardAuthorizedUntilParams) error {
	_, err := q.db.Exec(ctx, setPortForwardAuthorizedUntil, arg.ID, arg.AuthorizedUntil)
	return err
}

const setSessionTotpVerified = `-- name: SetSessionTotpVerified :exec
UPDATE sessions SET totp_verified_at = now() WHERE id = $1
`

// TOTP step-up (ADR-045 §5). Deliberately a SEPARATE column from the passkey
// marker: `mfa_verified_at` means "recent passkey", the root terminal requires
// that ritual, and letting a TOTP set it would hand every TOTP-only user a root
// shell.
func (q *Queries) SetSessionTotpVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setSessionTotpVerified, id)
	return err
}

const updateExternalEndpoint = `-- name: UpdateExternalEndpoint :one
UPDATE external_endpoints
SET name = $2,
    description = $8,
    host = $3,
    port = $4,
    server_id = $5,
    project_id = $9,
    environment_id = $10,
    criticality = $6,
    max_grant_minutes = $7,
    updated_by = $11,
    updated_at = now(),
    version = version + 1
WHERE id = $1
RETURNING id, uuid, team_id, name, description, host, port, server_id, project_id, environment_id, criticality, max_grant_minutes, created_by, updated_by, created_at, updated_at, version
`

type UpdateExternalEndpointParams struct {
	ID              int64
	Name            string
	Host            string
	Port            int32
	ServerID        int64
	Criticality     ExternalEndpointCriticality
	MaxGrantMinutes int32
	Description     *string
	ProjectID       *int64
	EnvironmentID   *int64
	UpdatedBy       *int64
}

func (q *Queries) UpdateExternalEndpoint(ctx context.Context, arg UpdateExternalEndpointParams) (ExternalEndpoint, error) {
	row := q.db.QueryRow(ctx, updateExternalEndpoint,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.ServerID,
		arg.Criticality,
		arg.MaxGrantMinutes,
		arg.Description,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.UpdatedBy,
	)
	var i ExternalEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.ServerID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Criticality,
		&i.MaxGrantMinutes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
