// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitsources.sql

package store

import (
	"context"
)

const countApplicationsUsingPrivateKey = `-- name: CountApplicationsUsingPrivateKey :one
SELECT count(*) FROM applications a
JOIN git_sources gs ON gs.id = a.git_source_id
JOIN resources r ON r.id = a.id
WHERE gs.private_key_id = $1 AND r.deleted_at IS NULL
`

// Applications cloning through a deploy key backed by this key. A key still
// in use is not deletable (§19.2) — reported as a conflict, not as a foreign
// key error.
func (q *Queries) CountApplicationsUsingPrivateKey(ctx context.Context, privateKeyID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsUsingPrivateKey, privateKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGitSource = `-- name: CreateGitSource :one
INSERT INTO git_sources (team_id, name, kind, provider, private_key_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, team_id, name, kind, provider, api_url, html_url, private_key_id, github_app_id, created_by, updated_by, created_at, updated_at, version
`

type CreateGitSourceParams struct {
	TeamID       int64
	Name         string
	Kind         GitSourceKind
	Provider     GitProvider
	PrivateKeyID *int64
	CreatedBy    *int64
}

func (q *Queries) CreateGitSource(ctx context.Context, arg CreateGitSourceParams) (GitSource, error) {
	row := q.db.QueryRow(ctx, createGitSource,
		arg.TeamID,
		arg.Name,
		arg.Kind,
		arg.Provider,
		arg.PrivateKeyID,
		arg.CreatedBy,
	)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Kind,
		&i.Provider,
		&i.ApiUrl,
		&i.HtmlUrl,
		&i.PrivateKeyID,
		&i.GithubAppID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDeployKeySource = `-- name: GetDeployKeySource :one

SELECT id, uuid, team_id, name, kind, provider, api_url, html_url, private_key_id, github_app_id, created_by, updated_by, created_at, updated_at, version FROM git_sources
WHERE team_id = $1 AND kind = 'deploy_key' AND private_key_id = $2
`

type GetDeployKeySourceParams struct {
	TeamID       int64
	PrivateKeyID *int64
}

// Git sources (§5.1, data-dictionary §7.1).
// One source per (team, deploy key): the API references keys, not sources, so
// reusing the same key for several applications must not multiply the rows.
func (q *Queries) GetDeployKeySource(ctx context.Context, arg GetDeployKeySourceParams) (GitSource, error) {
	row := q.db.QueryRow(ctx, getDeployKeySource, arg.TeamID, arg.PrivateKeyID)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Kind,
		&i.Provider,
		&i.ApiUrl,
		&i.HtmlUrl,
		&i.PrivateKeyID,
		&i.GithubAppID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getGitSourceByID = `-- name: GetGitSourceByID :one
SELECT id, uuid, team_id, name, kind, provider, api_url, html_url, private_key_id, github_app_id, created_by, updated_by, created_at, updated_at, version FROM git_sources WHERE id = $1
`

func (q *Queries) GetGitSourceByID(ctx context.Context, id int64) (GitSource, error) {
	row := q.db.QueryRow(ctx, getGitSourceByID, id)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Kind,
		&i.Provider,
		&i.ApiUrl,
		&i.HtmlUrl,
		&i.PrivateKeyID,
		&i.GithubAppID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listPrivateKeyIDsInUse = `-- name: ListPrivateKeyIDsInUse :many
SELECT k.id FROM private_keys k
WHERE k.id = ANY($1::bigint[])
  AND (
    EXISTS (SELECT 1 FROM servers s WHERE s.private_key_id = k.id AND s.deleted_at IS NULL)
    OR EXISTS (
      SELECT 1 FROM git_sources gs
      JOIN applications a ON a.git_source_id = gs.id
      JOIN resources r ON r.id = a.id AND r.deleted_at IS NULL
      WHERE gs.private_key_id = k.id)
  )
`

// Which of these keys are actually referenced — by a server or as an
// application's deploy key. Answered in one round trip so a key listing does
// not fan out into one query per row.
func (q *Queries) ListPrivateKeyIDsInUse(ctx context.Context, keyIds []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPrivateKeyIDsInUse, keyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
