// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitwebhooks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (provider, delivery_id, webhook_endpoint_id, event_type,
                                signature_valid, status, payload, team_id, application_id)
VALUES ($1, $2, $5, $6,
        $3, $4, $7, $8, $9)
ON CONFLICT (provider, delivery_id) DO NOTHING
RETURNING id, uuid, provider, delivery_id, webhook_endpoint_id, event_type, signature_valid, status, ignore_reason, payload, team_id, application_id, received_at, processed_at, created_at
`

type CreateWebhookDeliveryParams struct {
	Provider          WebhookProvider
	DeliveryID        string
	SignatureValid    bool
	Status            WebhookDeliveryStatus
	WebhookEndpointID *int64
	EventType         *string
	Payload           []byte
	TeamID            *int64
	ApplicationID     *int64
}

// ON CONFLICT DO NOTHING: a redelivery keeps the provider's delivery id, so the
// unique constraint absorbs it — no second row, no second deployment.
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.Provider,
		arg.DeliveryID,
		arg.SignatureValid,
		arg.Status,
		arg.WebhookEndpointID,
		arg.EventType,
		arg.Payload,
		arg.TeamID,
		arg.ApplicationID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Provider,
		&i.DeliveryID,
		&i.WebhookEndpointID,
		&i.EventType,
		&i.SignatureValid,
		&i.Status,
		&i.IgnoreReason,
		&i.Payload,
		&i.TeamID,
		&i.ApplicationID,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one

INSERT INTO webhook_endpoints (uuid, application_id, provider, secret_enc)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, application_id, provider, secret_enc, enabled, created_by, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	Uuid          pgtype.UUID
	ApplicationID int64
	Provider      WebhookProvider
	SecretEnc     []byte
}

// Incoming Git webhooks (§20.3, INV-009).
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.Uuid,
		arg.ApplicationID,
		arg.Provider,
		arg.SecretEnc,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.SecretEnc,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :execrows
DELETE FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEndpoint, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishWebhookDelivery = `-- name: FinishWebhookDelivery :exec
UPDATE webhook_deliveries
SET status = $2, ignore_reason = $3, processed_at = now()
WHERE id = $1
`

type FinishWebhookDeliveryParams struct {
	ID           int64
	Status       WebhookDeliveryStatus
	IgnoreReason *string
}

func (q *Queries) FinishWebhookDelivery(ctx context.Context, arg FinishWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, finishWebhookDelivery, arg.ID, arg.Status, arg.IgnoreReason)
	return err
}

const getWebhookDeliveryByID = `-- name: GetWebhookDeliveryByID :one
SELECT id, uuid, provider, delivery_id, webhook_endpoint_id, event_type, signature_valid, status, ignore_reason, payload, team_id, application_id, received_at, processed_at, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDeliveryByID(ctx context.Context, id int64) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Provider,
		&i.DeliveryID,
		&i.WebhookEndpointID,
		&i.EventType,
		&i.SignatureValid,
		&i.Status,
		&i.IgnoreReason,
		&i.Payload,
		&i.TeamID,
		&i.ApplicationID,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEndpointByUUID = `-- name: GetWebhookEndpointByUUID :one
SELECT e.id, e.uuid, e.application_id, e.provider, e.secret_enc, e.enabled, e.created_by, e.created_at, e.updated_at, r.team_id, r.uuid AS application_uuid
FROM webhook_endpoints e
JOIN applications a ON a.id = e.application_id
JOIN resources r ON r.id = a.id
WHERE e.uuid = $1 AND e.enabled AND r.deleted_at IS NULL
`

type GetWebhookEndpointByUUIDRow struct {
	ID              int64
	Uuid            pgtype.UUID
	ApplicationID   int64
	Provider        WebhookProvider
	SecretEnc       []byte
	Enabled         bool
	CreatedBy       *int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	TeamID          int64
	ApplicationUuid pgtype.UUID
}

// Resolution at reception: the endpoint carries everything needed to verify
// the signature and route the delivery.
func (q *Queries) GetWebhookEndpointByUUID(ctx context.Context, uuid pgtype.UUID) (GetWebhookEndpointByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByUUID, uuid)
	var i GetWebhookEndpointByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.SecretEnc,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.ApplicationUuid,
	)
	return i, err
}

const getWebhookEndpointForApplication = `-- name: GetWebhookEndpointForApplication :one
SELECT id, uuid, application_id, provider, secret_enc, enabled, created_by, created_at, updated_at FROM webhook_endpoints WHERE application_id = $1 AND provider = $2
`

type GetWebhookEndpointForApplicationParams struct {
	ApplicationID int64
	Provider      WebhookProvider
}

func (q *Queries) GetWebhookEndpointForApplication(ctx context.Context, arg GetWebhookEndpointForApplicationParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointForApplication, arg.ApplicationID, arg.Provider)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.SecretEnc,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookEndpointsToRotate = `-- name: ListWebhookEndpointsToRotate :many
SELECT id, uuid, secret_enc FROM webhook_endpoints
WHERE (get_byte(secret_enc, 0) << 24 | get_byte(secret_enc, 1) << 16 | get_byte(secret_enc, 2) << 8 | get_byte(secret_enc, 3)) <> $2::int
ORDER BY id
LIMIT $1
`

type ListWebhookEndpointsToRotateParams struct {
	Limit         int32
	ActiveVersion int32
}

type ListWebhookEndpointsToRotateRow struct {
	ID        int64
	Uuid      pgtype.UUID
	SecretEnc []byte
}

func (q *Queries) ListWebhookEndpointsToRotate(ctx context.Context, arg ListWebhookEndpointsToRotateParams) ([]ListWebhookEndpointsToRotateRow, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsToRotate, arg.Limit, arg.ActiveVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookEndpointsToRotateRow
	for rows.Next() {
		var i ListWebhookEndpointsToRotateRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.SecretEnc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeWebhookDeliveries = `-- name: PurgeWebhookDeliveries :execrows
DELETE FROM webhook_deliveries WHERE received_at < now() - interval '30 days'
`

// Retention bounds the dedup window: purging too aggressively would reopen the
// replay window (INV-009), hence 30 days minimum.
func (q *Queries) PurgeWebhookDeliveries(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebhookDeliveries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateWebhookEndpointEnc = `-- name: RotateWebhookEndpointEnc :exec
UPDATE webhook_endpoints SET secret_enc = $2 WHERE id = $1
`

type RotateWebhookEndpointEncParams struct {
	ID        int64
	SecretEnc []byte
}

func (q *Queries) RotateWebhookEndpointEnc(ctx context.Context, arg RotateWebhookEndpointEncParams) error {
	_, err := q.db.Exec(ctx, rotateWebhookEndpointEnc, arg.ID, arg.SecretEnc)
	return err
}
