// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one

INSERT INTO idempotency_keys (team_id, key, endpoint, request_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (team_id, key, endpoint) DO UPDATE SET key = EXCLUDED.key
RETURNING id, team_id, key, endpoint, request_hash, status_code, response_body, completed_at, created_at, (xmax = 0) AS is_new
`

type ClaimIdempotencyKeyParams struct {
	TeamID      int64
	Key         string
	Endpoint    string
	RequestHash string
}

type ClaimIdempotencyKeyRow struct {
	ID           int64
	TeamID       int64
	Key          string
	Endpoint     string
	RequestHash  string
	StatusCode   *int32
	ResponseBody []byte
	CompletedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	IsNew        bool
}

// HTTP idempotency (§24.1).
// Inserts the key, or returns the existing row when the key was already
// used: the caller compares the request hash and replays the response.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (ClaimIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.TeamID,
		arg.Key,
		arg.Endpoint,
		arg.RequestHash,
	)
	var i ClaimIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.IsNew,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status_code = $2, response_body = $3, completed_at = now()
WHERE id = $1
`

type CompleteIdempotencyKeyParams struct {
	ID           int64
	StatusCode   *int32
	ResponseBody []byte
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey, arg.ID, arg.StatusCode, arg.ResponseBody)
	return err
}

const purgeIdempotencyKeys = `-- name: PurgeIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) PurgeIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeIdempotencyKeys)
	return err
}
