// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingressendpoints.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenIngressSessions = `-- name: CountOpenIngressSessions :one
SELECT count(*) FROM ingress_tunnel_sessions
WHERE team_id = $1 AND ended_at IS NULL
`

func (q *Queries) CountOpenIngressSessions(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIngressSessions, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngressAccessToken = `-- name: CreateIngressAccessToken :exec
INSERT INTO preview_access_tokens (token_hash, ingress_endpoint_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateIngressAccessTokenParams struct {
	TokenHash         string
	IngressEndpointID *int64
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) CreateIngressAccessToken(ctx context.Context, arg CreateIngressAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createIngressAccessToken, arg.TokenHash, arg.IngressEndpointID, arg.ExpiresAt)
	return err
}

const createIngressDomain = `-- name: CreateIngressDomain :one
INSERT INTO domains (uuid, ingress_endpoint_id, fqdn, path, is_generated)
VALUES ($1, $2, $3, '/', false)
RETURNING id, uuid, application_id, service_component_id, fqdn, path, target_port, is_generated, created_by, created_at, updated_at, ingress_endpoint_id, model_id
`

type CreateIngressDomainParams struct {
	Uuid              pgtype.UUID
	IngressEndpointID *int64
	Fqdn              string
}

func (q *Queries) CreateIngressDomain(ctx context.Context, arg CreateIngressDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createIngressDomain, arg.Uuid, arg.IngressEndpointID, arg.Fqdn)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.ServiceComponentID,
		&i.Fqdn,
		&i.Path,
		&i.TargetPort,
		&i.IsGenerated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IngressEndpointID,
		&i.ModelID,
	)
	return i, err
}

const createIngressEndpoint = `-- name: CreateIngressEndpoint :one

INSERT INTO ingress_endpoints (
    team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by
) VALUES ($1, $2, $6, $3, $4, $5, $7, $8)
RETURNING id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version
`

type CreateIngressEndpointParams struct {
	TeamID        int64
	Name          string
	Fqdn          string
	ServerID      int64
	Access        IngressAccess
	Description   *string
	BasicAuthHash *string
	CreatedBy     *int64
}

// Ingress endpoints and their attach sessions (ADR-060). The mint/claim
// discipline mirrors portforwardsessions.sql, but the claim happens agent-side
// (the control plane only records what the agent reports), so there is no
// ClaimIngressSession here: the row is stamped from observations.
func (q *Queries) CreateIngressEndpoint(ctx context.Context, arg CreateIngressEndpointParams) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, createIngressEndpoint,
		arg.TeamID,
		arg.Name,
		arg.Fqdn,
		arg.ServerID,
		arg.Access,
		arg.Description,
		arg.BasicAuthHash,
		arg.CreatedBy,
	)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createIngressSession = `-- name: CreateIngressSession :one
INSERT INTO ingress_tunnel_sessions (
    team_id, endpoint_id, user_id, client_ip, token_hash, token_expires_at
) VALUES ($1, $2, $5, $6, $3, $4)
RETURNING id, uuid, team_id, endpoint_id, user_id, client_ip, token_hash, token_expires_at, claimed_at, started_at, last_seen_at, ended_at, end_reason, created_at
`

type CreateIngressSessionParams struct {
	TeamID         int64
	EndpointID     *int64
	TokenHash      string
	TokenExpiresAt pgtype.Timestamptz
	UserID         *int64
	ClientIp       *netip.Addr
}

func (q *Queries) CreateIngressSession(ctx context.Context, arg CreateIngressSessionParams) (IngressTunnelSession, error) {
	row := q.db.QueryRow(ctx, createIngressSession,
		arg.TeamID,
		arg.EndpointID,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.UserID,
		arg.ClientIp,
	)
	var i IngressTunnelSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.EndpointID,
		&i.UserID,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIngressEndpoint = `-- name: DeleteIngressEndpoint :one
DELETE FROM ingress_endpoints WHERE uuid = $1 AND team_id = $2 RETURNING id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version
`

type DeleteIngressEndpointParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) DeleteIngressEndpoint(ctx context.Context, arg DeleteIngressEndpointParams) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, deleteIngressEndpoint, arg.Uuid, arg.TeamID)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const endIngressSession = `-- name: EndIngressSession :execrows
UPDATE ingress_tunnel_sessions
SET ended_at = now(), end_reason = $2
WHERE id = $1 AND ended_at IS NULL
`

type EndIngressSessionParams struct {
	ID        int64
	EndReason *TerminalEndReason
}

func (q *Queries) EndIngressSession(ctx context.Context, arg EndIngressSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endIngressSession, arg.ID, arg.EndReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endIngressSessionByUUID = `-- name: EndIngressSessionByUUID :one
UPDATE ingress_tunnel_sessions
SET ended_at = now(), end_reason = $3
WHERE uuid = $1 AND team_id = $2 AND ended_at IS NULL
RETURNING id, uuid, team_id, endpoint_id, user_id, client_ip, token_hash, token_expires_at, claimed_at, started_at, last_seen_at, ended_at, end_reason, created_at
`

type EndIngressSessionByUUIDParams struct {
	Uuid      pgtype.UUID
	TeamID    int64
	EndReason *TerminalEndReason
}

func (q *Queries) EndIngressSessionByUUID(ctx context.Context, arg EndIngressSessionByUUIDParams) (IngressTunnelSession, error) {
	row := q.db.QueryRow(ctx, endIngressSessionByUUID, arg.Uuid, arg.TeamID, arg.EndReason)
	var i IngressTunnelSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.EndpointID,
		&i.UserID,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const getIngressEndpointByFQDN = `-- name: GetIngressEndpointByFQDN :one
SELECT id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version FROM ingress_endpoints WHERE fqdn = $1
`

// The authorize step resolves the redirect host to a declared endpoint — the
// sole anti-open-redirect rule, same as GetResourceByRoutedHost.
func (q *Queries) GetIngressEndpointByFQDN(ctx context.Context, fqdn string) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, getIngressEndpointByFQDN, fqdn)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getIngressEndpointByID = `-- name: GetIngressEndpointByID :one
SELECT id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version FROM ingress_endpoints WHERE id = $1
`

func (q *Queries) GetIngressEndpointByID(ctx context.Context, id int64) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, getIngressEndpointByID, id)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getIngressEndpointByUUID = `-- name: GetIngressEndpointByUUID :one
SELECT id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version FROM ingress_endpoints WHERE uuid = $1 AND team_id = $2
`

type GetIngressEndpointByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetIngressEndpointByUUID(ctx context.Context, arg GetIngressEndpointByUUIDParams) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, getIngressEndpointByUUID, arg.Uuid, arg.TeamID)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getIngressEndpointByUUIDGlobal = `-- name: GetIngressEndpointByUUIDGlobal :one
SELECT id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version FROM ingress_endpoints WHERE uuid = $1
`

// Unscoped by design: the SSO wall's forward-auth is called by Traefik, which
// has no team — the reference travels in the middleware address (ADR-030).
func (q *Queries) GetIngressEndpointByUUIDGlobal(ctx context.Context, uuid pgtype.UUID) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, getIngressEndpointByUUIDGlobal, uuid)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getOpenIngressSessionByUUID = `-- name: GetOpenIngressSessionByUUID :one
SELECT id, uuid, team_id, endpoint_id, user_id, client_ip, token_hash, token_expires_at, claimed_at, started_at, last_seen_at, ended_at, end_reason, created_at FROM ingress_tunnel_sessions WHERE uuid = $1 AND ended_at IS NULL
`

func (q *Queries) GetOpenIngressSessionByUUID(ctx context.Context, uuid pgtype.UUID) (IngressTunnelSession, error) {
	row := q.db.QueryRow(ctx, getOpenIngressSessionByUUID, uuid)
	var i IngressTunnelSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.EndpointID,
		&i.UserID,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenIngressSessionForEndpoint = `-- name: GetOpenIngressSessionForEndpoint :one
SELECT s.id, s.uuid, s.team_id, s.endpoint_id, s.user_id, s.client_ip, s.token_hash, s.token_expires_at, s.claimed_at, s.started_at, s.last_seen_at, s.ended_at, s.end_reason, s.created_at, u.email AS user_email
FROM ingress_tunnel_sessions s
LEFT JOIN users u ON u.id = s.user_id
WHERE s.endpoint_id = $1 AND s.ended_at IS NULL
`

type GetOpenIngressSessionForEndpointRow struct {
	ID             int64
	Uuid           pgtype.UUID
	TeamID         int64
	EndpointID     *int64
	UserID         *int64
	ClientIp       *netip.Addr
	TokenHash      string
	TokenExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	EndedAt        pgtype.Timestamptz
	EndReason      *TerminalEndReason
	CreatedAt      pgtype.Timestamptz
	UserEmail      *string
}

// The occupancy probe (ADR-060 §6): the partial unique index makes at most one
// row match. "Open" means not ended — an unclaimed, unexpired mint occupies.
func (q *Queries) GetOpenIngressSessionForEndpoint(ctx context.Context, endpointID *int64) (GetOpenIngressSessionForEndpointRow, error) {
	row := q.db.QueryRow(ctx, getOpenIngressSessionForEndpoint, endpointID)
	var i GetOpenIngressSessionForEndpointRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.EndpointID,
		&i.UserID,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
		&i.UserEmail,
	)
	return i, err
}

const listIngressEndpoints = `-- name: ListIngressEndpoints :many
SELECT e.id, e.uuid, e.team_id, e.name, e.description, e.fqdn, e.server_id, e.access, e.basic_auth_hash, e.created_by, e.updated_by, e.created_at, e.updated_at, e.version, s.uuid AS server_uuid, s.name AS server_name
FROM ingress_endpoints e
JOIN servers s ON s.id = e.server_id
WHERE e.team_id = $1
ORDER BY lower(e.name)
`

type ListIngressEndpointsRow struct {
	ID            int64
	Uuid          pgtype.UUID
	TeamID        int64
	Name          string
	Description   *string
	Fqdn          string
	ServerID      int64
	Access        IngressAccess
	BasicAuthHash *string
	CreatedBy     *int64
	UpdatedBy     *int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	ServerUuid    pgtype.UUID
	ServerName    string
}

func (q *Queries) ListIngressEndpoints(ctx context.Context, teamID int64) ([]ListIngressEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listIngressEndpoints, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngressEndpointsRow
	for rows.Next() {
		var i ListIngressEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Fqdn,
			&i.ServerID,
			&i.Access,
			&i.BasicAuthHash,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.ServerUuid,
			&i.ServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngressSessionsPage = `-- name: ListIngressSessionsPage :many
SELECT s.id, s.uuid, s.team_id, s.endpoint_id, s.user_id, s.client_ip, s.token_hash, s.token_expires_at, s.claimed_at, s.started_at, s.last_seen_at, s.ended_at, s.end_reason, s.created_at, u.email AS user_email, e.uuid AS endpoint_uuid, e.name AS endpoint_name, e.fqdn AS endpoint_fqdn
FROM ingress_tunnel_sessions s
LEFT JOIN users u ON u.id = s.user_id
LEFT JOIN ingress_endpoints e ON e.id = s.endpoint_id
WHERE s.team_id = $1
  AND s.id < $3::bigint
  AND ($4::bigint IS NULL OR s.endpoint_id = $4)
  AND (NOT $5::boolean
       OR (s.ended_at IS NULL
           AND ((s.claimed_at IS NULL AND s.token_expires_at > now())
                OR (s.claimed_at IS NOT NULL
                    AND (s.last_seen_at IS NULL OR s.last_seen_at > now() - interval '90 seconds')))))
ORDER BY s.id DESC
LIMIT $2
`

type ListIngressSessionsPageParams struct {
	TeamID     int64
	Limit      int32
	BeforeID   int64
	EndpointID *int64
	ActiveOnly bool
}

type ListIngressSessionsPageRow struct {
	ID             int64
	Uuid           pgtype.UUID
	TeamID         int64
	EndpointID     *int64
	UserID         *int64
	ClientIp       *netip.Addr
	TokenHash      string
	TokenExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	EndedAt        pgtype.Timestamptz
	EndReason      *TerminalEndReason
	CreatedAt      pgtype.Timestamptz
	UserEmail      *string
	EndpointUuid   pgtype.UUID
	EndpointName   *string
	EndpointFqdn   *string
}

func (q *Queries) ListIngressSessionsPage(ctx context.Context, arg ListIngressSessionsPageParams) ([]ListIngressSessionsPageRow, error) {
	rows, err := q.db.Query(ctx, listIngressSessionsPage,
		arg.TeamID,
		arg.Limit,
		arg.BeforeID,
		arg.EndpointID,
		arg.ActiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngressSessionsPageRow
	for rows.Next() {
		var i ListIngressSessionsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.EndpointID,
			&i.UserID,
			&i.ClientIp,
			&i.TokenHash,
			&i.TokenExpiresAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.EndReason,
			&i.CreatedAt,
			&i.UserEmail,
			&i.EndpointUuid,
			&i.EndpointName,
			&i.EndpointFqdn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIngressSessionClaimed = `-- name: MarkIngressSessionClaimed :execrows
UPDATE ingress_tunnel_sessions
SET claimed_at = now(), started_at = now(), last_seen_at = now()
WHERE uuid = $1 AND claimed_at IS NULL AND ended_at IS NULL
`

// Stamped from the agent's claim observation, never from an HTTP redeem: the
// socket lives agent-side. Idempotent against replayed observations.
func (q *Queries) MarkIngressSessionClaimed(ctx context.Context, uuid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markIngressSessionClaimed, uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeIngressSessions = `-- name: PurgeIngressSessions :execrows
DELETE FROM ingress_tunnel_sessions
WHERE ended_at IS NOT NULL AND ended_at < now() - interval '30 days'
`

func (q *Queries) PurgeIngressSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIngressSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepIngressSessions = `-- name: SweepIngressSessions :many
UPDATE ingress_tunnel_sessions
SET ended_at = now(),
    end_reason = CASE
        WHEN claimed_at IS NULL THEN 'user_close'::terminal_end_reason
        WHEN started_at <= now() - interval '12 hours' THEN 'max_duration'::terminal_end_reason
        ELSE 'disconnect'::terminal_end_reason
    END
WHERE ended_at IS NULL
  AND (
    (claimed_at IS NULL AND token_expires_at <= now())
    OR (claimed_at IS NOT NULL AND started_at <= now() - interval '12 hours')
    OR (claimed_at IS NOT NULL AND last_seen_at IS NOT NULL AND last_seen_at <= now() - interval '90 seconds')
  )
RETURNING id, uuid, team_id, endpoint_id, user_id, client_ip, token_hash, token_expires_at, claimed_at, started_at, last_seen_at, ended_at, end_reason, created_at
`

// Leader-side finalization of rows whose socket can no longer answer for
// itself: an unclaimed token past its TTL, a claimed session whose agent went
// silent (no report for 90 s), or one past the 12 h ceiling (ADR-060 §6).
// The derived reason keeps the audit line and the CLI message coherent.
func (q *Queries) SweepIngressSessions(ctx context.Context) ([]IngressTunnelSession, error) {
	rows, err := q.db.Query(ctx, sweepIngressSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngressTunnelSession
	for rows.Next() {
		var i IngressTunnelSession
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.EndpointID,
			&i.UserID,
			&i.ClientIp,
			&i.TokenHash,
			&i.TokenExpiresAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.EndReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchIngressSession = `-- name: TouchIngressSession :execrows
UPDATE ingress_tunnel_sessions
SET last_seen_at = now()
WHERE uuid = $1 AND claimed_at IS NOT NULL AND ended_at IS NULL
`

// Agent-reported liveness. Zero rows means the durable session was finalized
// (operator close, sweep) and the caller must cut the socket.
func (q *Queries) TouchIngressSession(ctx context.Context, uuid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchIngressSession, uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIngressEndpoint = `-- name: UpdateIngressEndpoint :one
UPDATE ingress_endpoints
SET name = $3,
    description = $5,
    access = $4,
    basic_auth_hash = $6,
    updated_by = $7,
    updated_at = now(),
    version = version + 1
WHERE uuid = $1 AND team_id = $2
RETURNING id, uuid, team_id, name, description, fqdn, server_id, access, basic_auth_hash, created_by, updated_by, created_at, updated_at, version
`

type UpdateIngressEndpointParams struct {
	Uuid          pgtype.UUID
	TeamID        int64
	Name          string
	Access        IngressAccess
	Description   *string
	BasicAuthHash *string
	UpdatedBy     *int64
}

// The FQDN and the server are immutable after declaration: both are baked into
// the issued certificate and the deposited router. Renaming the URL is a
// delete + declare, which is what it costs everywhere else in the product.
func (q *Queries) UpdateIngressEndpoint(ctx context.Context, arg UpdateIngressEndpointParams) (IngressEndpoint, error) {
	row := q.db.QueryRow(ctx, updateIngressEndpoint,
		arg.Uuid,
		arg.TeamID,
		arg.Name,
		arg.Access,
		arg.Description,
		arg.BasicAuthHash,
		arg.UpdatedBy,
	)
	var i IngressEndpoint
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Fqdn,
		&i.ServerID,
		&i.Access,
		&i.BasicAuthHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
