// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package store

import (
	"context"
)

const setTransactionalEmailConfig = `-- name: SetTransactionalEmailConfig :exec
UPDATE instance_settings SET transactional_email_config_enc = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) SetTransactionalEmailConfig(ctx context.Context, transactionalEmailConfigEnc []byte) error {
	_, err := q.db.Exec(ctx, setTransactionalEmailConfig, transactionalEmailConfigEnc)
	return err
}
