// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMcpAccessToken = `-- name: CreateMcpAccessToken :one
INSERT INTO mcp_access_tokens (token_hash, client_id, client_name, user_id, team_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, token_hash, client_id, client_name, user_id, team_id, expires_at, last_used_at, revoked_at, created_at
`

type CreateMcpAccessTokenParams struct {
	TokenHash  string
	ClientID   string
	ClientName string
	UserID     int64
	TeamID     int64
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateMcpAccessToken(ctx context.Context, arg CreateMcpAccessTokenParams) (McpAccessToken, error) {
	row := q.db.QueryRow(ctx, createMcpAccessToken,
		arg.TokenHash,
		arg.ClientID,
		arg.ClientName,
		arg.UserID,
		arg.TeamID,
		arg.ExpiresAt,
	)
	var i McpAccessToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TokenHash,
		&i.ClientID,
		&i.ClientName,
		&i.UserID,
		&i.TeamID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMcpOauthCode = `-- name: CreateMcpOauthCode :exec
INSERT INTO mcp_oauth_codes (code_hash, client_id, user_id, team_id, redirect_uri, code_challenge, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateMcpOauthCodeParams struct {
	CodeHash      string
	ClientID      string
	UserID        int64
	TeamID        int64
	RedirectUri   string
	CodeChallenge string
	ExpiresAt     pgtype.Timestamptz
}

// Single-use authorization code, PKCE challenge attached (ADR-043 §3).
func (q *Queries) CreateMcpOauthCode(ctx context.Context, arg CreateMcpOauthCodeParams) error {
	_, err := q.db.Exec(ctx, createMcpOauthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.TeamID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredMcpOauthCodes = `-- name: DeleteExpiredMcpOauthCodes :exec
DELETE FROM mcp_oauth_codes WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredMcpOauthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMcpOauthCodes)
	return err
}

const getMcpAccessTokenByHash = `-- name: GetMcpAccessTokenByHash :one
SELECT id, uuid, token_hash, client_id, client_name, user_id, team_id, expires_at, last_used_at, revoked_at, created_at FROM mcp_access_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetMcpAccessTokenByHash(ctx context.Context, tokenHash string) (McpAccessToken, error) {
	row := q.db.QueryRow(ctx, getMcpAccessTokenByHash, tokenHash)
	var i McpAccessToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TokenHash,
		&i.ClientID,
		&i.ClientName,
		&i.UserID,
		&i.TeamID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMcpOauthClient = `-- name: GetMcpOauthClient :one
SELECT id, client_id, client_name, redirect_uris, created_at FROM mcp_oauth_clients WHERE client_id = $1
`

func (q *Queries) GetMcpOauthClient(ctx context.Context, clientID string) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, getMcpOauthClient, clientID)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const listMcpAccessTokensForTeam = `-- name: ListMcpAccessTokensForTeam :many
SELECT id, uuid, token_hash, client_id, client_name, user_id, team_id, expires_at, last_used_at, revoked_at, created_at FROM mcp_access_tokens
WHERE team_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListMcpAccessTokensForTeam(ctx context.Context, teamID int64) ([]McpAccessToken, error) {
	rows, err := q.db.Query(ctx, listMcpAccessTokensForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpAccessToken
	for rows.Next() {
		var i McpAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TokenHash,
			&i.ClientID,
			&i.ClientName,
			&i.UserID,
			&i.TeamID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerMcpOauthClient = `-- name: RegisterMcpOauthClient :one

INSERT INTO mcp_oauth_clients (client_id, client_name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING id, client_id, client_name, redirect_uris, created_at
`

type RegisterMcpOauthClientParams struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
}

// Built-in MCP server (ADR-043): OAuth 2.1 for remote clients. Everything
// here is read-only in effect — a grant only ever reads one team's inventory.
func (q *Queries) RegisterMcpOauthClient(ctx context.Context, arg RegisterMcpOauthClientParams) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, registerMcpOauthClient, arg.ClientID, arg.ClientName, arg.RedirectUris)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const revokeMcpAccessToken = `-- name: RevokeMcpAccessToken :execrows
UPDATE mcp_access_tokens SET revoked_at = now()
WHERE uuid = $1 AND team_id = $2 AND revoked_at IS NULL
`

type RevokeMcpAccessTokenParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) RevokeMcpAccessToken(ctx context.Context, arg RevokeMcpAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMcpAccessToken, arg.Uuid, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstanceMcpDcrEnabled = `-- name: SetInstanceMcpDcrEnabled :exec
UPDATE instance_settings SET mcp_dcr_enabled = $1, updated_at = now() WHERE id = true
`

func (q *Queries) SetInstanceMcpDcrEnabled(ctx context.Context, mcpDcrEnabled bool) error {
	_, err := q.db.Exec(ctx, setInstanceMcpDcrEnabled, mcpDcrEnabled)
	return err
}

const setInstanceMcpEnabled = `-- name: SetInstanceMcpEnabled :exec
UPDATE instance_settings SET mcp_enabled = $1, updated_at = now() WHERE id = true
`

func (q *Queries) SetInstanceMcpEnabled(ctx context.Context, mcpEnabled bool) error {
	_, err := q.db.Exec(ctx, setInstanceMcpEnabled, mcpEnabled)
	return err
}

const takeMcpOauthCode = `-- name: TakeMcpOauthCode :one
DELETE FROM mcp_oauth_codes WHERE code_hash = $1 AND expires_at > now()
RETURNING id, code_hash, client_id, user_id, team_id, redirect_uri, code_challenge, expires_at, created_at
`

// Consumes the code: a replay finds nothing (DELETE … RETURNING).
func (q *Queries) TakeMcpOauthCode(ctx context.Context, codeHash string) (McpOauthCode, error) {
	row := q.db.QueryRow(ctx, takeMcpOauthCode, codeHash)
	var i McpOauthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.TeamID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchMcpAccessToken = `-- name: TouchMcpAccessToken :exec
UPDATE mcp_access_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchMcpAccessToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchMcpAccessToken, id)
	return err
}
