// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSuppressedSince = `-- name: CountSuppressedSince :one
SELECT count(*) FROM notification_deliveries
WHERE rule_id = $1 AND status = 'suppressed' AND created_at > coalesce($2::timestamptz, '-infinity')
`

type CountSuppressedSinceParams struct {
	RuleID int64
	Since  pgtype.Timestamptz
}

// How many events this rule swallowed since its last send — an aggregated
// alert must be able to say "and 12 others" rather than hide them (ADR-019).
func (q *Queries) CountSuppressedSince(ctx context.Context, arg CountSuppressedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressedSince, arg.RuleID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (uuid, team_id, kind, name, config_enc, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, team_id, kind, name, config_enc, use_instance_email, enabled, created_by, updated_by, created_at, updated_at, version
`

type CreateNotificationChannelParams struct {
	Uuid      pgtype.UUID
	TeamID    int64
	Kind      NotificationChannelKind
	Name      string
	ConfigEnc []byte
	Enabled   bool
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.Uuid,
		arg.TeamID,
		arg.Kind,
		arg.Name,
		arg.ConfigEnc,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Kind,
		&i.Name,
		&i.ConfigEnc,
		&i.UseInstanceEmail,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (rule_id, channel_id, outbox_event_id)
VALUES ($1, $2, $3)
ON CONFLICT (rule_id, outbox_event_id) DO NOTHING
RETURNING id, uuid, rule_id, channel_id, outbox_event_id, status, attempts, last_error, suppressed_reason, sent_at, created_at
`

type CreateNotificationDeliveryParams struct {
	RuleID        int64
	ChannelID     int64
	OutboxEventID int64
}

// ON CONFLICT DO NOTHING: re-reading an outbox event must never notify twice.
func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery, arg.RuleID, arg.ChannelID, arg.OutboxEventID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.RuleID,
		&i.ChannelID,
		&i.OutboxEventID,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.SuppressedReason,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationRule = `-- name: CreateNotificationRule :one
INSERT INTO notification_rules (uuid, channel_id, event_type, enabled, project_id, environment_id,
                                min_severity, debounce_seconds, quiet_hours_start, quiet_hours_end,
                                digest_enabled, digest_interval_minutes)
VALUES ($1, $2, $3, $4, $9, $10,
        $5, $6, $11, $12, $7, $8)
RETURNING id, uuid, channel_id, event_type, enabled, project_id, environment_id, min_severity, debounce_seconds, quiet_hours_start, quiet_hours_end, digest_enabled, created_at, updated_at, digest_interval_minutes, last_digest_at
`

type CreateNotificationRuleParams struct {
	Uuid                  pgtype.UUID
	ChannelID             int64
	EventType             string
	Enabled               bool
	MinSeverity           NotificationSeverity
	DebounceSeconds       int32
	DigestEnabled         bool
	DigestIntervalMinutes int32
	ProjectID             *int64
	EnvironmentID         *int64
	QuietHoursStart       pgtype.Time
	QuietHoursEnd         pgtype.Time
}

func (q *Queries) CreateNotificationRule(ctx context.Context, arg CreateNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, createNotificationRule,
		arg.Uuid,
		arg.ChannelID,
		arg.EventType,
		arg.Enabled,
		arg.MinSeverity,
		arg.DebounceSeconds,
		arg.DigestEnabled,
		arg.DigestIntervalMinutes,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ChannelID,
		&i.EventType,
		&i.Enabled,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.MinSeverity,
		&i.DebounceSeconds,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.DigestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DigestIntervalMinutes,
		&i.LastDigestAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationRule = `-- name: DeleteNotificationRule :execrows
DELETE FROM notification_rules WHERE id = $1
`

func (q *Queries) DeleteNotificationRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotificationDelivery = `-- name: FinishNotificationDelivery :exec
UPDATE notification_deliveries
SET status = $2, attempts = attempts + 1, last_error = $3, suppressed_reason = $4,
    sent_at = CASE WHEN $2 = 'sent' THEN now() ELSE sent_at END
WHERE id = $1
`

type FinishNotificationDeliveryParams struct {
	ID               int64
	Status           NotificationDeliveryStatus
	LastError        *string
	SuppressedReason *string
}

func (q *Queries) FinishNotificationDelivery(ctx context.Context, arg FinishNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, finishNotificationDelivery,
		arg.ID,
		arg.Status,
		arg.LastError,
		arg.SuppressedReason,
	)
	return err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, uuid, project_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM environments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getNotificationChannelByID = `-- name: GetNotificationChannelByID :one
SELECT id, uuid, team_id, kind, name, config_enc, use_instance_email, enabled, created_by, updated_by, created_at, updated_at, version FROM notification_channels WHERE id = $1
`

func (q *Queries) GetNotificationChannelByID(ctx context.Context, id int64) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Kind,
		&i.Name,
		&i.ConfigEnc,
		&i.UseInstanceEmail,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getNotificationChannelByUUID = `-- name: GetNotificationChannelByUUID :one
SELECT id, uuid, team_id, kind, name, config_enc, use_instance_email, enabled, created_by, updated_by, created_at, updated_at, version FROM notification_channels WHERE uuid = $1 AND team_id = $2
`

type GetNotificationChannelByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetNotificationChannelByUUID(ctx context.Context, arg GetNotificationChannelByUUIDParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByUUID, arg.Uuid, arg.TeamID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Kind,
		&i.Name,
		&i.ConfigEnc,
		&i.UseInstanceEmail,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getNotificationCursor = `-- name: GetNotificationCursor :one
SELECT last_outbox_event_id FROM notification_cursor WHERE id
`

func (q *Queries) GetNotificationCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNotificationCursor)
	var last_outbox_event_id int64
	err := row.Scan(&last_outbox_event_id)
	return last_outbox_event_id, err
}

const getNotificationRuleByUUID = `-- name: GetNotificationRuleByUUID :one
SELECT r.id, r.uuid, r.channel_id, r.event_type, r.enabled, r.project_id, r.environment_id, r.min_severity, r.debounce_seconds, r.quiet_hours_start, r.quiet_hours_end, r.digest_enabled, r.created_at, r.updated_at, r.digest_interval_minutes, r.last_digest_at FROM notification_rules r WHERE r.uuid = $1 AND r.channel_id = $2
`

type GetNotificationRuleByUUIDParams struct {
	Uuid      pgtype.UUID
	ChannelID int64
}

func (q *Queries) GetNotificationRuleByUUID(ctx context.Context, arg GetNotificationRuleByUUIDParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, getNotificationRuleByUUID, arg.Uuid, arg.ChannelID)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ChannelID,
		&i.EventType,
		&i.Enabled,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.MinSeverity,
		&i.DebounceSeconds,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.DigestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DigestIntervalMinutes,
		&i.LastDigestAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, uuid, team_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM projects WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const lastSentDelivery = `-- name: LastSentDelivery :one
SELECT sent_at FROM notification_deliveries
WHERE rule_id = $1 AND status = 'sent' AND sent_at IS NOT NULL
ORDER BY sent_at DESC
LIMIT 1
`

func (q *Queries) LastSentDelivery(ctx context.Context, ruleID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastSentDelivery, ruleID)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const listDigestRulesDue = `-- name: ListDigestRulesDue :many

SELECT r.id, r.uuid, r.channel_id, r.event_type, r.enabled, r.project_id, r.environment_id, r.min_severity, r.debounce_seconds, r.quiet_hours_start, r.quiet_hours_end, r.digest_enabled, r.created_at, r.updated_at, r.digest_interval_minutes, r.last_digest_at, c.kind, c.team_id FROM notification_rules r
JOIN notification_channels c ON c.id = r.channel_id
WHERE r.enabled AND c.enabled AND r.digest_enabled
  AND EXISTS (
    SELECT 1 FROM notification_deliveries d
    WHERE d.rule_id = r.id AND d.status = 'pending'
      AND d.created_at < now() - make_interval(mins => r.digest_interval_minutes)
  )
ORDER BY r.id
`

type ListDigestRulesDueRow struct {
	ID                    int64
	Uuid                  pgtype.UUID
	ChannelID             int64
	EventType             string
	Enabled               bool
	ProjectID             *int64
	EnvironmentID         *int64
	MinSeverity           NotificationSeverity
	DebounceSeconds       int32
	QuietHoursStart       pgtype.Time
	QuietHoursEnd         pgtype.Time
	DigestEnabled         bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DigestIntervalMinutes int32
	LastDigestAt          pgtype.Timestamptz
	Kind                  NotificationChannelKind
	TeamID                int64
}

// --- deferred digest (ADR-019 §4) --------------------------------------------
// Digest rules whose window has elapsed and that have something to say. A rule
// with nothing pending is not woken up: an empty digest is noise.
func (q *Queries) ListDigestRulesDue(ctx context.Context) ([]ListDigestRulesDueRow, error) {
	rows, err := q.db.Query(ctx, listDigestRulesDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDigestRulesDueRow
	for rows.Next() {
		var i ListDigestRulesDueRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ChannelID,
			&i.EventType,
			&i.Enabled,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.MinSeverity,
			&i.DebounceSeconds,
			&i.QuietHoursStart,
			&i.QuietHoursEnd,
			&i.DigestEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DigestIntervalMinutes,
			&i.LastDigestAt,
			&i.Kind,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsPage = `-- name: ListNotificationChannelsPage :many

SELECT id, uuid, team_id, kind, name, config_enc, use_instance_email, enabled, created_by, updated_by, created_at, updated_at, version FROM notification_channels
WHERE team_id = $1 AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListNotificationChannelsPageParams struct {
	TeamID    int64
	AfterID   int64
	PageLimit int32
}

// Notifications (§11, ADR-019).
func (q *Queries) ListNotificationChannelsPage(ctx context.Context, arg ListNotificationChannelsPageParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Kind,
			&i.Name,
			&i.ConfigEnc,
			&i.UseInstanceEmail,
			&i.Enabled,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRules = `-- name: ListNotificationRules :many
SELECT id, uuid, channel_id, event_type, enabled, project_id, environment_id, min_severity, debounce_seconds, quiet_hours_start, quiet_hours_end, digest_enabled, created_at, updated_at, digest_interval_minutes, last_digest_at FROM notification_rules WHERE channel_id = $1 ORDER BY id
`

func (q *Queries) ListNotificationRules(ctx context.Context, channelID int64) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, listNotificationRules, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationRule
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ChannelID,
			&i.EventType,
			&i.Enabled,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.MinSeverity,
			&i.DebounceSeconds,
			&i.QuietHoursStart,
			&i.QuietHoursEnd,
			&i.DigestEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DigestIntervalMinutes,
			&i.LastDigestAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxEventsAfter = `-- name: ListOutboxEventsAfter :many
SELECT id, uuid, event_type, occurred_at, team_uuid, resource_uuid, actor, correlation_id, aggregate_key, payload, published_at, publish_attempts, created_at FROM outbox_events
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListOutboxEventsAfterParams struct {
	ID    int64
	Limit int32
}

// Every event, whatever its team: the rules decide who hears about it.
func (q *Queries) ListOutboxEventsAfter(ctx context.Context, arg ListOutboxEventsAfterParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EventType,
			&i.OccurredAt,
			&i.TeamUuid,
			&i.ResourceUuid,
			&i.Actor,
			&i.CorrelationID,
			&i.AggregateKey,
			&i.Payload,
			&i.PublishedAt,
			&i.PublishAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDigestDeliveries = `-- name: ListPendingDigestDeliveries :many
SELECT d.id, d.outbox_event_id, e.event_type, e.resource_uuid, e.occurred_at
FROM notification_deliveries d
JOIN outbox_events e ON e.id = d.outbox_event_id
WHERE d.rule_id = $1 AND d.status = 'pending'
ORDER BY d.id
`

type ListPendingDigestDeliveriesRow struct {
	ID            int64
	OutboxEventID int64
	EventType     string
	ResourceUuid  pgtype.UUID
	OccurredAt    pgtype.Timestamptz
}

// What the digest of this rule stands for.
func (q *Queries) ListPendingDigestDeliveries(ctx context.Context, ruleID int64) ([]ListPendingDigestDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingDigestDeliveries, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingDigestDeliveriesRow
	for rows.Next() {
		var i ListPendingDigestDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OutboxEventID,
			&i.EventType,
			&i.ResourceUuid,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDigestDeliveriesFailed = `-- name: MarkDigestDeliveriesFailed :exec
UPDATE notification_deliveries
SET status = 'failed', attempts = attempts + 1, last_error = $1
WHERE id = ANY($2::bigint[])
`

type MarkDigestDeliveriesFailedParams struct {
	LastError   *string
	DeliveryIds []int64
}

func (q *Queries) MarkDigestDeliveriesFailed(ctx context.Context, arg MarkDigestDeliveriesFailedParams) error {
	_, err := q.db.Exec(ctx, markDigestDeliveriesFailed, arg.LastError, arg.DeliveryIds)
	return err
}

const markDigestDeliveriesSent = `-- name: MarkDigestDeliveriesSent :exec
UPDATE notification_deliveries
SET status = 'sent', attempts = attempts + 1, sent_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkDigestDeliveriesSent(ctx context.Context, deliveryIds []int64) error {
	_, err := q.db.Exec(ctx, markDigestDeliveriesSent, deliveryIds)
	return err
}

const matchNotificationRules = `-- name: MatchNotificationRules :many
SELECT r.id, r.uuid, r.channel_id, r.event_type, r.enabled, r.project_id, r.environment_id, r.min_severity, r.debounce_seconds, r.quiet_hours_start, r.quiet_hours_end, r.digest_enabled, r.created_at, r.updated_at, r.digest_interval_minutes, r.last_digest_at, c.kind, c.team_id FROM notification_rules r
JOIN notification_channels c ON c.id = r.channel_id
JOIN teams t ON t.id = c.team_id
WHERE r.enabled AND c.enabled
  AND r.event_type = $1
  AND t.uuid = $2
  AND (r.project_id IS NULL OR r.project_id = $3)
  AND (r.environment_id IS NULL OR r.environment_id = $4)
ORDER BY r.id
`

type MatchNotificationRulesParams struct {
	EventType     string
	TeamUuid      pgtype.UUID
	ProjectID     *int64
	EnvironmentID *int64
}

type MatchNotificationRulesRow struct {
	ID                    int64
	Uuid                  pgtype.UUID
	ChannelID             int64
	EventType             string
	Enabled               bool
	ProjectID             *int64
	EnvironmentID         *int64
	MinSeverity           NotificationSeverity
	DebounceSeconds       int32
	QuietHoursStart       pgtype.Time
	QuietHoursEnd         pgtype.Time
	DigestEnabled         bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DigestIntervalMinutes int32
	LastDigestAt          pgtype.Timestamptz
	Kind                  NotificationChannelKind
	TeamID                int64
}

// The rules that hear this event type, for this team, honouring the
// project/environment scoping (NULL = the whole team).
func (q *Queries) MatchNotificationRules(ctx context.Context, arg MatchNotificationRulesParams) ([]MatchNotificationRulesRow, error) {
	rows, err := q.db.Query(ctx, matchNotificationRules,
		arg.EventType,
		arg.TeamUuid,
		arg.ProjectID,
		arg.EnvironmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchNotificationRulesRow
	for rows.Next() {
		var i MatchNotificationRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ChannelID,
			&i.EventType,
			&i.Enabled,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.MinSeverity,
			&i.DebounceSeconds,
			&i.QuietHoursStart,
			&i.QuietHoursEnd,
			&i.DigestEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DigestIntervalMinutes,
			&i.LastDigestAt,
			&i.Kind,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProjectEnvironmentOfResource = `-- name: ResolveProjectEnvironmentOfResource :one
SELECT e.id AS environment_id, p.id AS project_id FROM resources r
JOIN environments e ON e.id = r.environment_id
JOIN projects p ON p.id = e.project_id
WHERE r.uuid = $1
`

type ResolveProjectEnvironmentOfResourceRow struct {
	EnvironmentID int64
	ProjectID     int64
}

// Which project/environment a resource belongs to, for rule scoping.
func (q *Queries) ResolveProjectEnvironmentOfResource(ctx context.Context, uuid pgtype.UUID) (ResolveProjectEnvironmentOfResourceRow, error) {
	row := q.db.QueryRow(ctx, resolveProjectEnvironmentOfResource, uuid)
	var i ResolveProjectEnvironmentOfResourceRow
	err := row.Scan(&i.EnvironmentID, &i.ProjectID)
	return i, err
}

const setNotificationCursor = `-- name: SetNotificationCursor :exec
UPDATE notification_cursor SET last_outbox_event_id = $1 WHERE id
`

func (q *Queries) SetNotificationCursor(ctx context.Context, lastOutboxEventID int64) error {
	_, err := q.db.Exec(ctx, setNotificationCursor, lastOutboxEventID)
	return err
}

const setRuleDigestFlushed = `-- name: SetRuleDigestFlushed :exec
UPDATE notification_rules SET last_digest_at = now() WHERE id = $1
`

func (q *Queries) SetRuleDigestFlushed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setRuleDigestFlushed, id)
	return err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :execrows
UPDATE notification_channels
SET name = $2, config_enc = $3, enabled = $4, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $5
`

type UpdateNotificationChannelParams struct {
	ID              int64
	Name            string
	ConfigEnc       []byte
	Enabled         bool
	ExpectedVersion int32
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationChannel,
		arg.ID,
		arg.Name,
		arg.ConfigEnc,
		arg.Enabled,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
