// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasskeyCeremony = `-- name: ConsumePasskeyCeremony :one
DELETE FROM passkey_ceremonies
WHERE token_hash = $1 AND purpose = $2 AND expires_at > now()
RETURNING id, token_hash, purpose, user_id, data, created_at, expires_at
`

type ConsumePasskeyCeremonyParams struct {
	TokenHash string
	Purpose   string
}

// DELETE ... RETURNING makes the ceremony single-use by construction: two
// concurrent finishes cannot both win, whatever the caller does.
func (q *Queries) ConsumePasskeyCeremony(ctx context.Context, arg ConsumePasskeyCeremonyParams) (PasskeyCeremony, error) {
	row := q.db.QueryRow(ctx, consumePasskeyCeremony, arg.TokenHash, arg.Purpose)
	var i PasskeyCeremony
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Purpose,
		&i.UserID,
		&i.Data,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createPasskeyCeremony = `-- name: CreatePasskeyCeremony :exec
INSERT INTO passkey_ceremonies (token_hash, purpose, user_id, data, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePasskeyCeremonyParams struct {
	TokenHash string
	Purpose   string
	UserID    *int64
	Data      []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasskeyCeremony(ctx context.Context, arg CreatePasskeyCeremonyParams) error {
	_, err := q.db.Exec(ctx, createPasskeyCeremony,
		arg.TokenHash,
		arg.Purpose,
		arg.UserID,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const createPasskeyCredential = `-- name: CreatePasskeyCredential :one

INSERT INTO passkey_credentials (user_id, name, credential_id, credential)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, user_id, name, credential_id, credential, created_at, last_used_at
`

type CreatePasskeyCredentialParams struct {
	UserID       int64
	Name         string
	CredentialID []byte
	Credential   []byte
}

// Passkeys (WebAuthn) for the dashboard login.
func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) (PasskeyCredential, error) {
	row := q.db.QueryRow(ctx, createPasskeyCredential,
		arg.UserID,
		arg.Name,
		arg.CredentialID,
		arg.Credential,
	)
	var i PasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.Credential,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deletePasskeyForUser = `-- name: DeletePasskeyForUser :execrows
DELETE FROM passkey_credentials WHERE uuid = $1 AND user_id = $2
`

type DeletePasskeyForUserParams struct {
	Uuid   pgtype.UUID
	UserID int64
}

// Scoped by user: a session must never be able to delete someone else's key.
func (q *Queries) DeletePasskeyForUser(ctx context.Context, arg DeletePasskeyForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskeyForUser, arg.Uuid, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT p.id, p.uuid, p.user_id, p.name, p.credential_id, p.credential, p.created_at, p.last_used_at, u.uuid AS user_uuid, u.email, u.name AS user_name
FROM passkey_credentials p
JOIN users u ON u.id = p.user_id
WHERE p.credential_id = $1 AND u.deleted_at IS NULL
`

type GetPasskeyByCredentialIDRow struct {
	ID           int64
	Uuid         pgtype.UUID
	UserID       int64
	Name         string
	CredentialID []byte
	Credential   []byte
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	UserUuid     pgtype.UUID
	Email        string
	UserName     string
}

// The login ceremony starts from the credential: the authenticator presents a
// credential id, and the user is whoever enrolled it. A deleted user's
// passkeys must not open sessions, hence the join.
func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (GetPasskeyByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getPasskeyByCredentialID, credentialID)
	var i GetPasskeyByCredentialIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.Credential,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserUuid,
		&i.Email,
		&i.UserName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, email, name, password_hash, is_root, email_verified_at, failed_login_count, locked_until, created_at, updated_at, deleted_at, version FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsRoot,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listPasskeysForUser = `-- name: ListPasskeysForUser :many
SELECT id, uuid, user_id, name, credential_id, credential, created_at, last_used_at FROM passkey_credentials WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListPasskeysForUser(ctx context.Context, userID int64) ([]PasskeyCredential, error) {
	rows, err := q.db.Query(ctx, listPasskeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyCredential
	for rows.Next() {
		var i PasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.CredentialID,
			&i.Credential,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredPasskeyCeremonies = `-- name: PurgeExpiredPasskeyCeremonies :execrows
DELETE FROM passkey_ceremonies WHERE expires_at < now()
`

func (q *Queries) PurgeExpiredPasskeyCeremonies(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredPasskeyCeremonies)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasskeyCredential = `-- name: UpdatePasskeyCredential :exec
UPDATE passkey_credentials SET credential = $2, last_used_at = now() WHERE id = $1
`

type UpdatePasskeyCredentialParams struct {
	ID         int64
	Credential []byte
}

// Called after every successful assertion: the sign counter moved, and the
// clone-detection logic downstream depends on it being persisted.
func (q *Queries) UpdatePasskeyCredential(ctx context.Context, arg UpdatePasskeyCredentialParams) error {
	_, err := q.db.Exec(ctx, updatePasskeyCredential, arg.ID, arg.Credential)
	return err
}
