// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portforwardsessions.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPortForwardSession = `-- name: ClaimPortForwardSession :one
UPDATE port_forward_sessions
SET claimed_at = now(), started_at = now(), last_heartbeat_at = now()
WHERE token_hash = $1
  AND claimed_at IS NULL
  AND ended_at IS NULL
  AND token_expires_at > now()
RETURNING id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at, external_endpoint_id, grant_id, authorized_until, last_heartbeat_at
`

// Single-use attach: consumes the token atomically (a replay matches zero rows).
func (q *Queries) ClaimPortForwardSession(ctx context.Context, tokenHash string) (PortForwardSession, error) {
	row := q.db.QueryRow(ctx, claimPortForwardSession, tokenHash)
	var i PortForwardSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.ServerID,
		&i.ResourceID,
		&i.PreviewID,
		&i.TargetName,
		&i.TargetComponent,
		&i.TargetPort,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
		&i.ExternalEndpointID,
		&i.GrantID,
		&i.AuthorizedUntil,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const countOpenPortForwardSessions = `-- name: CountOpenPortForwardSessions :one
SELECT count(*) FROM port_forward_sessions
WHERE team_id = $1
  AND ended_at IS NULL
  AND (
    (claimed_at IS NULL AND token_expires_at > now())
    OR (
      claimed_at IS NOT NULL
      AND started_at > now() - interval '4 hours'
      AND (authorized_until IS NULL OR authorized_until > now())
      -- NULL belongs to an N-1 bridge which cannot heartbeat. Keep it valid
      -- until the four-hour ceiling during rolling upgrades.
      AND (last_heartbeat_at IS NULL OR last_heartbeat_at > now() - interval '90 seconds')
    )
  )
`

func (q *Queries) CountOpenPortForwardSessions(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenPortForwardSessions, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPortForwardSession = `-- name: CreatePortForwardSession :one

INSERT INTO port_forward_sessions (
    team_id, user_id, server_id, resource_id, preview_id, target_name,
    target_component, target_port, client_ip, token_hash, token_expires_at
) VALUES (
    $1, $6, $7, $8,
    $9, $2, $10, $3,
    $11, $4, $5
)
RETURNING id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at, external_endpoint_id, grant_id, authorized_until, last_heartbeat_at
`

type CreatePortForwardSessionParams struct {
	TeamID          int64
	TargetName      string
	TargetPort      int32
	TokenHash       string
	TokenExpiresAt  pgtype.Timestamptz
	UserID          *int64
	ServerID        *int64
	ResourceID      *int64
	PreviewID       *int64
	TargetComponent *string
	ClientIp        *netip.Addr
}

// CLI TCP tunnel sessions (ADR-032, data-dictionary §10.7). Mirrors the
// terminal-session lifecycle.
func (q *Queries) CreatePortForwardSession(ctx context.Context, arg CreatePortForwardSessionParams) (PortForwardSession, error) {
	row := q.db.QueryRow(ctx, createPortForwardSession,
		arg.TeamID,
		arg.TargetName,
		arg.TargetPort,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.UserID,
		arg.ServerID,
		arg.ResourceID,
		arg.PreviewID,
		arg.TargetComponent,
		arg.ClientIp,
	)
	var i PortForwardSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.ServerID,
		&i.ResourceID,
		&i.PreviewID,
		&i.TargetName,
		&i.TargetComponent,
		&i.TargetPort,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
		&i.ExternalEndpointID,
		&i.GrantID,
		&i.AuthorizedUntil,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const endPortForwardSession = `-- name: EndPortForwardSession :execrows
UPDATE port_forward_sessions
SET ended_at = now(), end_reason = $2
WHERE id = $1 AND ended_at IS NULL
`

type EndPortForwardSessionParams struct {
	ID        int64
	EndReason *TerminalEndReason
}

func (q *Queries) EndPortForwardSession(ctx context.Context, arg EndPortForwardSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endPortForwardSession, arg.ID, arg.EndReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPortForwardSessionByUUID = `-- name: GetPortForwardSessionByUUID :one
SELECT id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at, external_endpoint_id, grant_id, authorized_until, last_heartbeat_at FROM port_forward_sessions WHERE uuid = $1 AND team_id = $2
`

type GetPortForwardSessionByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetPortForwardSessionByUUID(ctx context.Context, arg GetPortForwardSessionByUUIDParams) (PortForwardSession, error) {
	row := q.db.QueryRow(ctx, getPortForwardSessionByUUID, arg.Uuid, arg.TeamID)
	var i PortForwardSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.ServerID,
		&i.ResourceID,
		&i.PreviewID,
		&i.TargetName,
		&i.TargetComponent,
		&i.TargetPort,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
		&i.ExternalEndpointID,
		&i.GrantID,
		&i.AuthorizedUntil,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const heartbeatPortForwardSession = `-- name: HeartbeatPortForwardSession :execrows
UPDATE port_forward_sessions
SET last_heartbeat_at = now()
WHERE id = $1
  AND claimed_at IS NOT NULL
  AND ended_at IS NULL
`

// The WebSocket already pings every 20 s. Persisting one successful beat lets
// another replica, or the process that starts after a crash, reject a ghost.
func (q *Queries) HeartbeatPortForwardSession(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatPortForwardSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPortForwardSessionsPage = `-- name: ListPortForwardSessionsPage :many
SELECT s.id, s.uuid, s.team_id, s.user_id, s.server_id, s.resource_id, s.preview_id, s.target_name, s.target_component, s.target_port, s.client_ip, s.token_hash, s.token_expires_at, s.claimed_at, s.started_at, s.ended_at, s.end_reason, s.created_at, s.external_endpoint_id, s.grant_id, s.authorized_until, s.last_heartbeat_at, u.email AS user_email, e.uuid AS endpoint_uuid
FROM port_forward_sessions s
LEFT JOIN users u ON u.id = s.user_id
LEFT JOIN external_endpoints e ON e.id = s.external_endpoint_id
WHERE s.team_id = $1
  AND s.id < $2::bigint
  AND ($3::bigint IS NULL OR s.external_endpoint_id = $3)
  -- Same definition of "open" as the team cap, so the list and the 409 never
  -- disagree about how many sessions exist.
  AND (NOT $4::boolean
       OR (
         s.ended_at IS NULL
         AND (
           (s.claimed_at IS NULL AND s.token_expires_at > now())
           OR (
             s.claimed_at IS NOT NULL
             AND s.started_at > now() - interval '4 hours'
             AND (s.authorized_until IS NULL OR s.authorized_until > now())
             AND (s.last_heartbeat_at IS NULL OR s.last_heartbeat_at > now() - interval '90 seconds')
           )
         )
       ))
ORDER BY s.id DESC
LIMIT $5::int
`

type ListPortForwardSessionsPageParams struct {
	TeamID     int64
	BeforeID   int64
	EndpointID *int64
	ActiveOnly bool
	PageLimit  int32
}

type ListPortForwardSessionsPageRow struct {
	ID                 int64
	Uuid               pgtype.UUID
	TeamID             int64
	UserID             *int64
	ServerID           *int64
	ResourceID         *int64
	PreviewID          *int64
	TargetName         string
	TargetComponent    *string
	TargetPort         int32
	ClientIp           *netip.Addr
	TokenHash          string
	TokenExpiresAt     pgtype.Timestamptz
	ClaimedAt          pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	EndReason          *TerminalEndReason
	CreatedAt          pgtype.Timestamptz
	ExternalEndpointID *int64
	GrantID            *int64
	AuthorizedUntil    pgtype.Timestamptz
	LastHeartbeatAt    pgtype.Timestamptz
	UserEmail          *string
	EndpointUuid       pgtype.UUID
}

// The operator's view of the team's tunnels. Newest first, like the grant list:
// the question asked is almost always "what is forwarded right now". The joins
// are LEFT because a session outlives its user and its endpoint — a row whose
// target was deleted still has to be readable, or the audit trail has holes
// exactly where something was removed.
func (q *Queries) ListPortForwardSessionsPage(ctx context.Context, arg ListPortForwardSessionsPageParams) ([]ListPortForwardSessionsPageRow, error) {
	rows, err := q.db.Query(ctx, listPortForwardSessionsPage,
		arg.TeamID,
		arg.BeforeID,
		arg.EndpointID,
		arg.ActiveOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortForwardSessionsPageRow
	for rows.Next() {
		var i ListPortForwardSessionsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.UserID,
			&i.ServerID,
			&i.ResourceID,
			&i.PreviewID,
			&i.TargetName,
			&i.TargetComponent,
			&i.TargetPort,
			&i.ClientIp,
			&i.TokenHash,
			&i.TokenExpiresAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.CreatedAt,
			&i.ExternalEndpointID,
			&i.GrantID,
			&i.AuthorizedUntil,
			&i.LastHeartbeatAt,
			&i.UserEmail,
			&i.EndpointUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgePortForwardSessions = `-- name: PurgePortForwardSessions :execrows
DELETE FROM port_forward_sessions
WHERE ended_at IS NOT NULL
  AND ended_at < now() - make_interval(days => $1::int)
`

func (q *Queries) PurgePortForwardSessions(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgePortForwardSessions, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepPortForwardSessions = `-- name: SweepPortForwardSessions :many
UPDATE port_forward_sessions
SET ended_at = now(),
    end_reason = CASE
      WHEN claimed_at IS NULL THEN 'revoked'::terminal_end_reason
      WHEN authorized_until IS NOT NULL AND authorized_until <= now()
        THEN 'grant_expired'::terminal_end_reason
      WHEN started_at <= now() - interval '4 hours'
        THEN 'max_duration'::terminal_end_reason
      ELSE 'disconnect'::terminal_end_reason
    END
WHERE ended_at IS NULL
  AND (
    (claimed_at IS NULL AND token_expires_at <= now())
    OR (
      claimed_at IS NOT NULL
      AND (
        started_at <= now() - interval '4 hours'
        OR (authorized_until IS NOT NULL AND authorized_until <= now())
        OR (last_heartbeat_at IS NOT NULL
            AND last_heartbeat_at <= now() - interval '90 seconds')
      )
    )
  )
RETURNING team_id, uuid
`

type SweepPortForwardSessionsRow struct {
	TeamID int64
	Uuid   pgtype.UUID
}

// Finalize rows whose socket cannot still be alive. A non-NULL heartbeat names
// a bridge from this release or later; legacy NULL rows are left alone until
// the protocol's hard four-hour ceiling so an N-1 replica remains compatible.
func (q *Queries) SweepPortForwardSessions(ctx context.Context) ([]SweepPortForwardSessionsRow, error) {
	rows, err := q.db.Query(ctx, sweepPortForwardSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepPortForwardSessionsRow
	for rows.Next() {
		var i SweepPortForwardSessionsRow
		if err := rows.Scan(&i.TeamID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
