// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portforwardsessions.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPortForwardSession = `-- name: ClaimPortForwardSession :one
UPDATE port_forward_sessions
SET claimed_at = now(), started_at = now()
WHERE token_hash = $1
  AND claimed_at IS NULL
  AND ended_at IS NULL
  AND token_expires_at > now()
RETURNING id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at
`

// Single-use attach: consumes the token atomically (a replay matches zero rows).
func (q *Queries) ClaimPortForwardSession(ctx context.Context, tokenHash string) (PortForwardSession, error) {
	row := q.db.QueryRow(ctx, claimPortForwardSession, tokenHash)
	var i PortForwardSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.ServerID,
		&i.ResourceID,
		&i.PreviewID,
		&i.TargetName,
		&i.TargetComponent,
		&i.TargetPort,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const countOpenPortForwardSessions = `-- name: CountOpenPortForwardSessions :one
SELECT count(*) FROM port_forward_sessions
WHERE team_id = $1
  AND ended_at IS NULL
  AND (claimed_at IS NOT NULL OR token_expires_at > now())
`

func (q *Queries) CountOpenPortForwardSessions(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenPortForwardSessions, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPortForwardSession = `-- name: CreatePortForwardSession :one

INSERT INTO port_forward_sessions (
    team_id, user_id, server_id, resource_id, preview_id, target_name,
    target_component, target_port, client_ip, token_hash, token_expires_at
) VALUES (
    $1, $6, $7, $8,
    $9, $2, $10, $3,
    $11, $4, $5
)
RETURNING id, uuid, team_id, user_id, server_id, resource_id, preview_id, target_name, target_component, target_port, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at
`

type CreatePortForwardSessionParams struct {
	TeamID          int64
	TargetName      string
	TargetPort      int32
	TokenHash       string
	TokenExpiresAt  pgtype.Timestamptz
	UserID          *int64
	ServerID        *int64
	ResourceID      *int64
	PreviewID       *int64
	TargetComponent *string
	ClientIp        *netip.Addr
}

// CLI TCP tunnel sessions (ADR-032, data-dictionary §10.7). Mirrors the
// terminal-session lifecycle.
func (q *Queries) CreatePortForwardSession(ctx context.Context, arg CreatePortForwardSessionParams) (PortForwardSession, error) {
	row := q.db.QueryRow(ctx, createPortForwardSession,
		arg.TeamID,
		arg.TargetName,
		arg.TargetPort,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.UserID,
		arg.ServerID,
		arg.ResourceID,
		arg.PreviewID,
		arg.TargetComponent,
		arg.ClientIp,
	)
	var i PortForwardSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.ServerID,
		&i.ResourceID,
		&i.PreviewID,
		&i.TargetName,
		&i.TargetComponent,
		&i.TargetPort,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const endPortForwardSession = `-- name: EndPortForwardSession :execrows
UPDATE port_forward_sessions
SET ended_at = now(), end_reason = $2
WHERE id = $1 AND ended_at IS NULL
`

type EndPortForwardSessionParams struct {
	ID        int64
	EndReason *TerminalEndReason
}

func (q *Queries) EndPortForwardSession(ctx context.Context, arg EndPortForwardSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endPortForwardSession, arg.ID, arg.EndReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgePortForwardSessions = `-- name: PurgePortForwardSessions :execrows
DELETE FROM port_forward_sessions
WHERE ended_at IS NOT NULL
  AND ended_at < now() - make_interval(days => $1::int)
`

func (q *Queries) PurgePortForwardSessions(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgePortForwardSessions, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
