// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previews.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePreviewFork = `-- name: ApprovePreviewFork :execrows
UPDATE previews SET fork_approved_by = $2, fork_approved_at = now(), updated_at = now()
WHERE id = $1 AND is_fork AND fork_approved_at IS NULL
`

type ApprovePreviewForkParams struct {
	ID             int64
	ForkApprovedBy *int64
}

func (q *Queries) ApprovePreviewFork(ctx context.Context, arg ApprovePreviewForkParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePreviewFork, arg.ID, arg.ForkApprovedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLivePreviewsForApplication = `-- name: CountLivePreviewsForApplication :one
SELECT count(*) FROM previews
WHERE application_id = $1 AND status IN ('deploying', 'active')
`

// The concurrency cap (§20.4.3) counts everything that consumes the server.
func (q *Queries) CountLivePreviewsForApplication(ctx context.Context, applicationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLivePreviewsForApplication, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPreviewByID = `-- name: GetPreviewByID :one
SELECT id, uuid, application_id, provider, pr_id, source_branch, head_sha, is_fork, fork_approved_by, fork_approved_at, fqdn, status, cleanup_error, last_deployed_at, last_activity_at, destroyed_at, created_at, updated_at FROM previews WHERE id = $1
`

func (q *Queries) GetPreviewByID(ctx context.Context, id int64) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreviewByID, id)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.PrID,
		&i.SourceBranch,
		&i.HeadSha,
		&i.IsFork,
		&i.ForkApprovedBy,
		&i.ForkApprovedAt,
		&i.Fqdn,
		&i.Status,
		&i.CleanupError,
		&i.LastDeployedAt,
		&i.LastActivityAt,
		&i.DestroyedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviewByIdentity = `-- name: GetPreviewByIdentity :one
SELECT id, uuid, application_id, provider, pr_id, source_branch, head_sha, is_fork, fork_approved_by, fork_approved_at, fqdn, status, cleanup_error, last_deployed_at, last_activity_at, destroyed_at, created_at, updated_at FROM previews
WHERE application_id = $1 AND provider = $2 AND pr_id = $3
`

type GetPreviewByIdentityParams struct {
	ApplicationID int64
	Provider      GitProvider
	PrID          int32
}

func (q *Queries) GetPreviewByIdentity(ctx context.Context, arg GetPreviewByIdentityParams) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreviewByIdentity, arg.ApplicationID, arg.Provider, arg.PrID)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.PrID,
		&i.SourceBranch,
		&i.HeadSha,
		&i.IsFork,
		&i.ForkApprovedBy,
		&i.ForkApprovedAt,
		&i.Fqdn,
		&i.Status,
		&i.CleanupError,
		&i.LastDeployedAt,
		&i.LastActivityAt,
		&i.DestroyedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviewByUUIDForTeam = `-- name: GetPreviewByUUIDForTeam :one
SELECT p.id, p.uuid, p.application_id, p.provider, p.pr_id, p.source_branch, p.head_sha, p.is_fork, p.fork_approved_by, p.fork_approved_at, p.fqdn, p.status, p.cleanup_error, p.last_deployed_at, p.last_activity_at, p.destroyed_at, p.created_at, p.updated_at FROM previews p
JOIN resources r ON r.id = p.application_id
WHERE p.uuid = $1 AND r.team_id = $2
`

type GetPreviewByUUIDForTeamParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

// Team ownership travels through the application chain (INV-002).
func (q *Queries) GetPreviewByUUIDForTeam(ctx context.Context, arg GetPreviewByUUIDForTeamParams) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreviewByUUIDForTeam, arg.Uuid, arg.TeamID)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.PrID,
		&i.SourceBranch,
		&i.HeadSha,
		&i.IsFork,
		&i.ForkApprovedBy,
		&i.ForkApprovedAt,
		&i.Fqdn,
		&i.Status,
		&i.CleanupError,
		&i.LastDeployedAt,
		&i.LastActivityAt,
		&i.DestroyedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredPreviews = `-- name: ListExpiredPreviews :many
SELECT p.id, p.uuid, p.application_id, p.provider, p.pr_id, p.source_branch, p.head_sha, p.is_fork, p.fork_approved_by, p.fork_approved_at, p.fqdn, p.status, p.cleanup_error, p.last_deployed_at, p.last_activity_at, p.destroyed_at, p.created_at, p.updated_at FROM previews p
JOIN applications a ON a.id = p.application_id
WHERE p.status = 'active' AND a.preview_ttl_minutes IS NOT NULL
  AND GREATEST(coalesce(p.last_activity_at, p.last_deployed_at), p.last_deployed_at)
      < now() - make_interval(mins => a.preview_ttl_minutes)
`

// TTL of inactivity (§20.4.3): based on the last deployment or activity.
func (q *Queries) ListExpiredPreviews(ctx context.Context) ([]Preview, error) {
	rows, err := q.db.Query(ctx, listExpiredPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preview
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ApplicationID,
			&i.Provider,
			&i.PrID,
			&i.SourceBranch,
			&i.HeadSha,
			&i.IsFork,
			&i.ForkApprovedBy,
			&i.ForkApprovedAt,
			&i.Fqdn,
			&i.Status,
			&i.CleanupError,
			&i.LastDeployedAt,
			&i.LastActivityAt,
			&i.DestroyedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewEnvVars = `-- name: ListPreviewEnvVars :many
SELECT id, uuid, resource_id, key, value_enc, is_secret, is_build_time, is_literal, is_multiline, is_locked, is_preview, is_generated, created_by, updated_by, created_at, updated_at FROM environment_variables
WHERE resource_id = $1 AND is_preview = true
ORDER BY key
`

// The DEDICATED preview variable set (INV-010): production secrets are never
// copied implicitly.
func (q *Queries) ListPreviewEnvVars(ctx context.Context, resourceID int64) ([]EnvironmentVariable, error) {
	rows, err := q.db.Query(ctx, listPreviewEnvVars, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentVariable
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ResourceID,
			&i.Key,
			&i.ValueEnc,
			&i.IsSecret,
			&i.IsBuildTime,
			&i.IsLiteral,
			&i.IsMultiline,
			&i.IsLocked,
			&i.IsPreview,
			&i.IsGenerated,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewsForApplication = `-- name: ListPreviewsForApplication :many
SELECT id, uuid, application_id, provider, pr_id, source_branch, head_sha, is_fork, fork_approved_by, fork_approved_at, fqdn, status, cleanup_error, last_deployed_at, last_activity_at, destroyed_at, created_at, updated_at FROM previews
WHERE application_id = $1 AND status <> 'destroyed'
ORDER BY pr_id
`

func (q *Queries) ListPreviewsForApplication(ctx context.Context, applicationID int64) ([]Preview, error) {
	rows, err := q.db.Query(ctx, listPreviewsForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preview
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ApplicationID,
			&i.Provider,
			&i.PrID,
			&i.SourceBranch,
			&i.HeadSha,
			&i.IsFork,
			&i.ForkApprovedBy,
			&i.ForkApprovedAt,
			&i.Fqdn,
			&i.Status,
			&i.CleanupError,
			&i.LastDeployedAt,
			&i.LastActivityAt,
			&i.DestroyedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedPreviews = `-- name: ListQueuedPreviews :many
SELECT id, uuid, application_id, provider, pr_id, source_branch, head_sha, is_fork, fork_approved_by, fork_approved_at, fqdn, status, cleanup_error, last_deployed_at, last_activity_at, destroyed_at, created_at, updated_at FROM previews WHERE status = 'queued' ORDER BY updated_at
LIMIT 50
`

// Promoted by the scheduler when capacity frees up (§20.4.3).
func (q *Queries) ListQueuedPreviews(ctx context.Context) ([]Preview, error) {
	rows, err := q.db.Query(ctx, listQueuedPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preview
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ApplicationID,
			&i.Provider,
			&i.PrID,
			&i.SourceBranch,
			&i.HeadSha,
			&i.IsFork,
			&i.ForkApprovedBy,
			&i.ForkApprovedAt,
			&i.Fqdn,
			&i.Status,
			&i.CleanupError,
			&i.LastDeployedAt,
			&i.LastActivityAt,
			&i.DestroyedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPreviewDeployed = `-- name: SetPreviewDeployed :exec
UPDATE previews SET status = 'active', last_deployed_at = now(), last_activity_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetPreviewDeployed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setPreviewDeployed, id)
	return err
}

const setPreviewFqdn = `-- name: SetPreviewFqdn :exec
UPDATE previews SET fqdn = $2, updated_at = now() WHERE id = $1
`

type SetPreviewFqdnParams struct {
	ID   int64
	Fqdn *string
}

func (q *Queries) SetPreviewFqdn(ctx context.Context, arg SetPreviewFqdnParams) error {
	_, err := q.db.Exec(ctx, setPreviewFqdn, arg.ID, arg.Fqdn)
	return err
}

const setPreviewStatus = `-- name: SetPreviewStatus :exec
UPDATE previews SET status = $2,
    cleanup_error = $3,
    destroyed_at = CASE WHEN $2 = 'destroyed'::preview_status THEN now() ELSE destroyed_at END,
    updated_at = now()
WHERE id = $1
`

type SetPreviewStatusParams struct {
	ID           int64
	Status       PreviewStatus
	CleanupError *string
}

func (q *Queries) SetPreviewStatus(ctx context.Context, arg SetPreviewStatusParams) error {
	_, err := q.db.Exec(ctx, setPreviewStatus, arg.ID, arg.Status, arg.CleanupError)
	return err
}

const updateApplicationPreviewSettings = `-- name: UpdateApplicationPreviewSettings :exec
UPDATE applications SET
    previews_enabled = COALESCE($2, previews_enabled),
    preview_url_template = COALESCE($3, preview_url_template),
    preview_max_concurrent = CASE WHEN $4::boolean THEN $5 ELSE preview_max_concurrent END,
    preview_ttl_minutes = CASE WHEN $6::boolean THEN $7 ELSE preview_ttl_minutes END,
    preview_protection = COALESCE($8, preview_protection),
    preview_fork_approval_enabled = COALESCE($9, preview_fork_approval_enabled),
    preview_exclude_drafts = COALESCE($10, preview_exclude_drafts)
WHERE id = $1
`

type UpdateApplicationPreviewSettingsParams struct {
	ID                         int64
	PreviewsEnabled            *bool
	PreviewUrlTemplate         *string
	SetMaxConcurrent           bool
	PreviewMaxConcurrent       *int32
	SetTtl                     bool
	PreviewTtlMinutes          *int32
	PreviewProtection          *PreviewProtection
	PreviewForkApprovalEnabled *bool
	PreviewExcludeDrafts       *bool
}

func (q *Queries) UpdateApplicationPreviewSettings(ctx context.Context, arg UpdateApplicationPreviewSettingsParams) error {
	_, err := q.db.Exec(ctx, updateApplicationPreviewSettings,
		arg.ID,
		arg.PreviewsEnabled,
		arg.PreviewUrlTemplate,
		arg.SetMaxConcurrent,
		arg.PreviewMaxConcurrent,
		arg.SetTtl,
		arg.PreviewTtlMinutes,
		arg.PreviewProtection,
		arg.PreviewForkApprovalEnabled,
		arg.PreviewExcludeDrafts,
	)
	return err
}

const upsertPreview = `-- name: UpsertPreview :one

INSERT INTO previews (application_id, provider, pr_id, source_branch, head_sha, is_fork)
VALUES ($1, $2, $3, $5, $6, $4)
ON CONFLICT (application_id, provider, pr_id) DO UPDATE SET
    source_branch = excluded.source_branch,
    head_sha = excluded.head_sha,
    is_fork = excluded.is_fork,
    status = CASE WHEN previews.status IN ('destroyed', 'failed') THEN 'queued'::preview_status ELSE previews.status END,
    destroyed_at = NULL,
    updated_at = now()
RETURNING id, uuid, application_id, provider, pr_id, source_branch, head_sha, is_fork, fork_approved_by, fork_approved_at, fqdn, status, cleanup_error, last_deployed_at, last_activity_at, destroyed_at, created_at, updated_at
`

type UpsertPreviewParams struct {
	ApplicationID int64
	Provider      GitProvider
	PrID          int32
	IsFork        bool
	SourceBranch  *string
	HeadSha       *string
}

// PR previews (data-dictionary §8.9, §20.4).
// New commit on the same PR reuses the identity — the instance redeploys,
// it is never duplicated (§20.4). A destroyed preview row is revived when
// the PR reopens.
func (q *Queries) UpsertPreview(ctx context.Context, arg UpsertPreviewParams) (Preview, error) {
	row := q.db.QueryRow(ctx, upsertPreview,
		arg.ApplicationID,
		arg.Provider,
		arg.PrID,
		arg.IsFork,
		arg.SourceBranch,
		arg.HeadSha,
	)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ApplicationID,
		&i.Provider,
		&i.PrID,
		&i.SourceBranch,
		&i.HeadSha,
		&i.IsFork,
		&i.ForkApprovedBy,
		&i.ForkApprovedAt,
		&i.Fqdn,
		&i.Status,
		&i.CleanupError,
		&i.LastDeployedAt,
		&i.LastActivityAt,
		&i.DestroyedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
