// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: private_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrivateKey = `-- name: CreatePrivateKey :one

INSERT INTO private_keys (uuid, team_id, name, description, fingerprint_sha256, public_key, private_key_enc, is_instance)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, uuid, team_id, name, description, fingerprint_sha256, public_key, private_key_enc, created_by, updated_by, created_at, updated_at, version, is_instance
`

type CreatePrivateKeyParams struct {
	Uuid              pgtype.UUID
	TeamID            *int64
	Name              string
	Description       *string
	FingerprintSha256 string
	PublicKey         string
	PrivateKeyEnc     []byte
	IsInstance        bool
}

// SSH private keys (§3.1, §23.2). The uuid is generated by the application
// so the envelope AAD (table || column || uuid) can bind the ciphertext to
// its row at insert time (data-dictionary §2.7).
func (q *Queries) CreatePrivateKey(ctx context.Context, arg CreatePrivateKeyParams) (PrivateKey, error) {
	row := q.db.QueryRow(ctx, createPrivateKey,
		arg.Uuid,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.FingerprintSha256,
		arg.PublicKey,
		arg.PrivateKeyEnc,
		arg.IsInstance,
	)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.FingerprintSha256,
		&i.PublicKey,
		&i.PrivateKeyEnc,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.IsInstance,
	)
	return i, err
}

const deletePrivateKey = `-- name: DeletePrivateKey :execrows
DELETE FROM private_keys WHERE id = $1
`

func (q *Queries) DeletePrivateKey(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrivateKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstancePrivateKey = `-- name: GetInstancePrivateKey :one
SELECT id, uuid, team_id, name, description, fingerprint_sha256, public_key, private_key_enc, created_by, updated_by, created_at, updated_at, version, is_instance FROM private_keys WHERE is_instance
`

func (q *Queries) GetInstancePrivateKey(ctx context.Context) (PrivateKey, error) {
	row := q.db.QueryRow(ctx, getInstancePrivateKey)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.FingerprintSha256,
		&i.PublicKey,
		&i.PrivateKeyEnc,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.IsInstance,
	)
	return i, err
}

const getPrivateKeyByID = `-- name: GetPrivateKeyByID :one
SELECT id, uuid, team_id, name, description, fingerprint_sha256, public_key, private_key_enc, created_by, updated_by, created_at, updated_at, version, is_instance FROM private_keys WHERE id = $1
`

func (q *Queries) GetPrivateKeyByID(ctx context.Context, id int64) (PrivateKey, error) {
	row := q.db.QueryRow(ctx, getPrivateKeyByID, id)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.FingerprintSha256,
		&i.PublicKey,
		&i.PrivateKeyEnc,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.IsInstance,
	)
	return i, err
}

const getPrivateKeyByUUID = `-- name: GetPrivateKeyByUUID :one
SELECT id, uuid, team_id, name, description, fingerprint_sha256, public_key, private_key_enc, created_by, updated_by, created_at, updated_at, version, is_instance FROM private_keys WHERE uuid = $1 AND team_id = $2
`

type GetPrivateKeyByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID *int64
}

func (q *Queries) GetPrivateKeyByUUID(ctx context.Context, arg GetPrivateKeyByUUIDParams) (PrivateKey, error) {
	row := q.db.QueryRow(ctx, getPrivateKeyByUUID, arg.Uuid, arg.TeamID)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.FingerprintSha256,
		&i.PublicKey,
		&i.PrivateKeyEnc,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.IsInstance,
	)
	return i, err
}

const listPrivateKeysPage = `-- name: ListPrivateKeysPage :many
SELECT id, uuid, team_id, name, description, fingerprint_sha256, public_key, private_key_enc, created_by, updated_by, created_at, updated_at, version, is_instance FROM private_keys
WHERE team_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListPrivateKeysPageParams struct {
	TeamID    *int64
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListPrivateKeysPage(ctx context.Context, arg ListPrivateKeysPageParams) ([]PrivateKey, error) {
	rows, err := q.db.Query(ctx, listPrivateKeysPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivateKey
	for rows.Next() {
		var i PrivateKey
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.FingerprintSha256,
			&i.PublicKey,
			&i.PrivateKeyEnc,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.IsInstance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrivateKey = `-- name: UpdatePrivateKey :execrows
UPDATE private_keys
SET name = $2, description = $3, fingerprint_sha256 = $4, public_key = $5,
    private_key_enc = $6, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $7
`

type UpdatePrivateKeyParams struct {
	ID                int64
	Name              string
	Description       *string
	FingerprintSha256 string
	PublicKey         string
	PrivateKeyEnc     []byte
	ExpectedVersion   int32
}

func (q *Queries) UpdatePrivateKey(ctx context.Context, arg UpdatePrivateKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePrivateKey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.FingerprintSha256,
		arg.PublicKey,
		arg.PrivateKeyEnc,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
