// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResourcesByEnvironment = `-- name: CountResourcesByEnvironment :many
SELECT environment_id, count(*) AS resources
FROM resources
WHERE environment_id = ANY($1::bigint[]) AND deleted_at IS NULL
GROUP BY environment_id
`

type CountResourcesByEnvironmentRow struct {
	EnvironmentID int64
	Resources     int64
}

// Live resources per environment, in one round trip: a per-row count would fan
// out into one query per environment on every project listing.
func (q *Queries) CountResourcesByEnvironment(ctx context.Context, environmentIds []int64) ([]CountResourcesByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, countResourcesByEnvironment, environmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountResourcesByEnvironmentRow
	for rows.Next() {
		var i CountResourcesByEnvironmentRow
		if err := rows.Scan(&i.EnvironmentID, &i.Resources); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, project_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version
`

type CreateEnvironmentParams struct {
	ProjectID   int64
	Name        string
	Slug        string
	Description *string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (team_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, team_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version
`

type CreateProjectParams struct {
	TeamID      int64
	Name        string
	Slug        string
	Description *string
}

// Projects and environments (§2, §19.2). All access is scoped by the
// authenticated team (INV-001); slugs are internal, derived from names.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TeamID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getEnvironmentByUUID = `-- name: GetEnvironmentByUUID :one
SELECT id, uuid, project_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM environments
WHERE uuid = $1 AND project_id = $2 AND deleted_at IS NULL
`

type GetEnvironmentByUUIDParams struct {
	Uuid      pgtype.UUID
	ProjectID int64
}

func (q *Queries) GetEnvironmentByUUID(ctx context.Context, arg GetEnvironmentByUUIDParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByUUID, arg.Uuid, arg.ProjectID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getProjectByUUID = `-- name: GetProjectByUUID :one
SELECT id, uuid, team_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM projects
WHERE uuid = $1 AND team_id = $2 AND deleted_at IS NULL
`

type GetProjectByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetProjectByUUID(ctx context.Context, arg GetProjectByUUIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUUID, arg.Uuid, arg.TeamID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listEnvironmentsPage = `-- name: ListEnvironmentsPage :many
SELECT id, uuid, project_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM environments
WHERE project_id = $1 AND deleted_at IS NULL
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListEnvironmentsPageParams struct {
	ProjectID int64
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListEnvironmentsPage(ctx context.Context, arg ListEnvironmentsPageParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsPage, arg.ProjectID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsSummary = `-- name: ListEnvironmentsSummary :many
SELECT id, uuid, project_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM environments
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListEnvironmentsSummary(ctx context.Context, projectID int64) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsSummary, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsPage = `-- name: ListProjectsPage :many
SELECT id, uuid, team_id, name, slug, description, created_by, updated_by, created_at, updated_at, deleted_at, version FROM projects
WHERE team_id = $1 AND deleted_at IS NULL
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListProjectsPageParams struct {
	TeamID    int64
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListProjectsPage(ctx context.Context, arg ListProjectsPageParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEnvironment = `-- name: SoftDeleteEnvironment :execrows
UPDATE environments SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEnvironment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEnvironment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProjectEnvironments = `-- name: SoftDeleteProjectEnvironments :exec
UPDATE environments SET deleted_at = now(), updated_at = now()
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProjectEnvironments(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, softDeleteProjectEnvironments, projectID)
	return err
}

const updateEnvironment = `-- name: UpdateEnvironment :execrows
UPDATE environments
SET name = $2, slug = $3, description = $4, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $5 AND deleted_at IS NULL
`

type UpdateEnvironmentParams struct {
	ID              int64
	Name            string
	Slug            string
	Description     *string
	ExpectedVersion int32
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEnvironment,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects
SET name = $2, slug = $3, description = $4, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $5 AND deleted_at IS NULL
`

type UpdateProjectParams struct {
	ID              int64
	Name            string
	Slug            string
	Description     *string
	ExpectedVersion int32
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
