// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: s3storages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBackupPlansUsingS3Storage = `-- name: CountBackupPlansUsingS3Storage :one
SELECT count(*) FROM database_backup_plans
WHERE s3_storage_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountBackupPlansUsingS3Storage(ctx context.Context, s3StorageID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBackupPlansUsingS3Storage, s3StorageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createS3Storage = `-- name: CreateS3Storage :one
INSERT INTO s3_storages (uuid, team_id, name, endpoint, region, bucket, path_prefix,
                         access_key_enc, secret_key_enc, is_usable, last_check_error, sse_algorithm)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, uuid, team_id, name, endpoint, region, bucket, path_prefix, access_key_enc, secret_key_enc, is_usable, last_check_error, created_by, created_at, updated_at, version, sse_algorithm
`

type CreateS3StorageParams struct {
	Uuid           pgtype.UUID
	TeamID         int64
	Name           string
	Endpoint       string
	Region         *string
	Bucket         string
	PathPrefix     *string
	AccessKeyEnc   []byte
	SecretKeyEnc   []byte
	IsUsable       bool
	LastCheckError *string
	SseAlgorithm   *string
}

func (q *Queries) CreateS3Storage(ctx context.Context, arg CreateS3StorageParams) (S3Storage, error) {
	row := q.db.QueryRow(ctx, createS3Storage,
		arg.Uuid,
		arg.TeamID,
		arg.Name,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.PathPrefix,
		arg.AccessKeyEnc,
		arg.SecretKeyEnc,
		arg.IsUsable,
		arg.LastCheckError,
		arg.SseAlgorithm,
	)
	var i S3Storage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.PathPrefix,
		&i.AccessKeyEnc,
		&i.SecretKeyEnc,
		&i.IsUsable,
		&i.LastCheckError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SseAlgorithm,
	)
	return i, err
}

const deleteS3Storage = `-- name: DeleteS3Storage :execrows
DELETE FROM s3_storages WHERE id = $1
`

func (q *Queries) DeleteS3Storage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteS3Storage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getS3StorageByID = `-- name: GetS3StorageByID :one
SELECT id, uuid, team_id, name, endpoint, region, bucket, path_prefix, access_key_enc, secret_key_enc, is_usable, last_check_error, created_by, created_at, updated_at, version, sse_algorithm FROM s3_storages WHERE id = $1
`

func (q *Queries) GetS3StorageByID(ctx context.Context, id int64) (S3Storage, error) {
	row := q.db.QueryRow(ctx, getS3StorageByID, id)
	var i S3Storage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.PathPrefix,
		&i.AccessKeyEnc,
		&i.SecretKeyEnc,
		&i.IsUsable,
		&i.LastCheckError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SseAlgorithm,
	)
	return i, err
}

const getS3StorageByUUID = `-- name: GetS3StorageByUUID :one
SELECT id, uuid, team_id, name, endpoint, region, bucket, path_prefix, access_key_enc, secret_key_enc, is_usable, last_check_error, created_by, created_at, updated_at, version, sse_algorithm FROM s3_storages WHERE uuid = $1 AND team_id = $2
`

type GetS3StorageByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetS3StorageByUUID(ctx context.Context, arg GetS3StorageByUUIDParams) (S3Storage, error) {
	row := q.db.QueryRow(ctx, getS3StorageByUUID, arg.Uuid, arg.TeamID)
	var i S3Storage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.PathPrefix,
		&i.AccessKeyEnc,
		&i.SecretKeyEnc,
		&i.IsUsable,
		&i.LastCheckError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SseAlgorithm,
	)
	return i, err
}

const listS3StoragesPage = `-- name: ListS3StoragesPage :many

SELECT id, uuid, team_id, name, endpoint, region, bucket, path_prefix, access_key_enc, secret_key_enc, is_usable, last_check_error, created_by, created_at, updated_at, version, sse_algorithm FROM s3_storages
WHERE team_id = $1 AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListS3StoragesPageParams struct {
	TeamID    int64
	AfterID   int64
	PageLimit int32
}

// S3 storages (§7.2, data-dictionary §6.6). Credentials are envelope-encrypted
// and never leave the instance (INV-003).
func (q *Queries) ListS3StoragesPage(ctx context.Context, arg ListS3StoragesPageParams) ([]S3Storage, error) {
	rows, err := q.db.Query(ctx, listS3StoragesPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []S3Storage
	for rows.Next() {
		var i S3Storage
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Name,
			&i.Endpoint,
			&i.Region,
			&i.Bucket,
			&i.PathPrefix,
			&i.AccessKeyEnc,
			&i.SecretKeyEnc,
			&i.IsUsable,
			&i.LastCheckError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.SseAlgorithm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listS3StoragesToRotate = `-- name: ListS3StoragesToRotate :many
SELECT id, uuid, access_key_enc, secret_key_enc FROM s3_storages
WHERE (get_byte(access_key_enc, 0) << 24 | get_byte(access_key_enc, 1) << 16 | get_byte(access_key_enc, 2) << 8 | get_byte(access_key_enc, 3)) <> $2::int
   OR (get_byte(secret_key_enc, 0) << 24 | get_byte(secret_key_enc, 1) << 16 | get_byte(secret_key_enc, 2) << 8 | get_byte(secret_key_enc, 3)) <> $2::int
ORDER BY id
LIMIT $1
`

type ListS3StoragesToRotateParams struct {
	Limit         int32
	ActiveVersion int32
}

type ListS3StoragesToRotateRow struct {
	ID           int64
	Uuid         pgtype.UUID
	AccessKeyEnc []byte
	SecretKeyEnc []byte
}

// Rows still encrypted with an older master key version (ADR-003, §23.2). The
// key version is the first 4 bytes of the ciphertext.
func (q *Queries) ListS3StoragesToRotate(ctx context.Context, arg ListS3StoragesToRotateParams) ([]ListS3StoragesToRotateRow, error) {
	rows, err := q.db.Query(ctx, listS3StoragesToRotate, arg.Limit, arg.ActiveVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListS3StoragesToRotateRow
	for rows.Next() {
		var i ListS3StoragesToRotateRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.AccessKeyEnc,
			&i.SecretKeyEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateS3StorageEnc = `-- name: RotateS3StorageEnc :exec
UPDATE s3_storages SET access_key_enc = $2, secret_key_enc = $3 WHERE id = $1
`

type RotateS3StorageEncParams struct {
	ID           int64
	AccessKeyEnc []byte
	SecretKeyEnc []byte
}

func (q *Queries) RotateS3StorageEnc(ctx context.Context, arg RotateS3StorageEncParams) error {
	_, err := q.db.Exec(ctx, rotateS3StorageEnc, arg.ID, arg.AccessKeyEnc, arg.SecretKeyEnc)
	return err
}

const setS3StorageCheck = `-- name: SetS3StorageCheck :exec
UPDATE s3_storages
SET is_usable = $2, last_check_error = $3, updated_at = now()
WHERE id = $1
`

type SetS3StorageCheckParams struct {
	ID             int64
	IsUsable       bool
	LastCheckError *string
}

func (q *Queries) SetS3StorageCheck(ctx context.Context, arg SetS3StorageCheckParams) error {
	_, err := q.db.Exec(ctx, setS3StorageCheck, arg.ID, arg.IsUsable, arg.LastCheckError)
	return err
}

const updateS3Storage = `-- name: UpdateS3Storage :execrows
UPDATE s3_storages
SET name = $2, endpoint = $3, region = $4, bucket = $5, path_prefix = $6,
    access_key_enc = $7, secret_key_enc = $8, is_usable = $9, last_check_error = $10,
    sse_algorithm = $11,
    updated_at = now(), version = version + 1
WHERE id = $1 AND version = $12
`

type UpdateS3StorageParams struct {
	ID              int64
	Name            string
	Endpoint        string
	Region          *string
	Bucket          string
	PathPrefix      *string
	AccessKeyEnc    []byte
	SecretKeyEnc    []byte
	IsUsable        bool
	LastCheckError  *string
	SseAlgorithm    *string
	ExpectedVersion int32
}

func (q *Queries) UpdateS3Storage(ctx context.Context, arg UpdateS3StorageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateS3Storage,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.PathPrefix,
		arg.AccessKeyEnc,
		arg.SecretKeyEnc,
		arg.IsUsable,
		arg.LastCheckError,
		arg.SseAlgorithm,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
