// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduledtasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningTaskExecutions = `-- name: CountRunningTaskExecutions :one
SELECT count(*) FROM task_executions
WHERE scheduled_task_id = $1 AND status = 'running'
`

func (q *Queries) CountRunningTaskExecutions(ctx context.Context, scheduledTaskID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningTaskExecutions, scheduledTaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduledTask = `-- name: CreateScheduledTask :one

INSERT INTO scheduled_tasks (team_id, resource_id, name, command, container, cron_expression, timezone, enabled, overlap_policy, missed_run_policy, timeout_seconds, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, uuid, team_id, resource_id, container, name, command, cron_expression, timezone, enabled, overlap_policy, missed_run_policy, timeout_seconds, next_run_at, last_run_at, created_by, updated_by, created_at, updated_at, deleted_at, version
`

type CreateScheduledTaskParams struct {
	TeamID          int64
	ResourceID      int64
	Name            string
	Command         string
	Container       *string
	CronExpression  string
	Timezone        string
	Enabled         bool
	OverlapPolicy   TaskOverlapPolicy
	MissedRunPolicy TaskMissedRunPolicy
	TimeoutSeconds  int32
	CreatedBy       *int64
}

// Scheduled tasks (§192). The scheduler owns next_run_at, exactly like the
// backup plans: the cron expression alone cannot tell whether an occurrence
// has already fired.
func (q *Queries) CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, createScheduledTask,
		arg.TeamID,
		arg.ResourceID,
		arg.Name,
		arg.Command,
		arg.Container,
		arg.CronExpression,
		arg.Timezone,
		arg.Enabled,
		arg.OverlapPolicy,
		arg.MissedRunPolicy,
		arg.TimeoutSeconds,
		arg.CreatedBy,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.ResourceID,
		&i.Container,
		&i.Name,
		&i.Command,
		&i.CronExpression,
		&i.Timezone,
		&i.Enabled,
		&i.OverlapPolicy,
		&i.MissedRunPolicy,
		&i.TimeoutSeconds,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (scheduled_task_id, status, skip_reason)
VALUES ($1, $2, $3)
RETURNING id, uuid, scheduled_task_id, status, skip_reason, exit_code, output, output_truncated, started_at, finished_at, duration_ms
`

type CreateTaskExecutionParams struct {
	ScheduledTaskID int64
	Status          TaskExecutionStatus
	SkipReason      *string
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, createTaskExecution, arg.ScheduledTaskID, arg.Status, arg.SkipReason)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ScheduledTaskID,
		&i.Status,
		&i.SkipReason,
		&i.ExitCode,
		&i.Output,
		&i.OutputTruncated,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
	)
	return i, err
}

const finishTaskExecution = `-- name: FinishTaskExecution :exec
UPDATE task_executions
SET status = $2, exit_code = $3, output = $4, output_truncated = $5,
    finished_at = now(),
    duration_ms = (EXTRACT(EPOCH FROM (now() - started_at)) * 1000)::int
WHERE id = $1
`

type FinishTaskExecutionParams struct {
	ID              int64
	Status          TaskExecutionStatus
	ExitCode        *int32
	Output          *string
	OutputTruncated bool
}

func (q *Queries) FinishTaskExecution(ctx context.Context, arg FinishTaskExecutionParams) error {
	_, err := q.db.Exec(ctx, finishTaskExecution,
		arg.ID,
		arg.Status,
		arg.ExitCode,
		arg.Output,
		arg.OutputTruncated,
	)
	return err
}

const getScheduledTaskByID = `-- name: GetScheduledTaskByID :one
SELECT t.id, t.uuid, t.team_id, t.resource_id, t.container, t.name, t.command, t.cron_expression, t.timezone, t.enabled, t.overlap_policy, t.missed_run_policy, t.timeout_seconds, t.next_run_at, t.last_run_at, t.created_by, t.updated_by, t.created_at, t.updated_at, t.deleted_at, t.version, r.uuid AS application_uuid
FROM scheduled_tasks t
JOIN resources r ON r.id = t.resource_id
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetScheduledTaskByIDRow struct {
	ScheduledTask   ScheduledTask
	ApplicationUuid pgtype.UUID
}

func (q *Queries) GetScheduledTaskByID(ctx context.Context, id int64) (GetScheduledTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getScheduledTaskByID, id)
	var i GetScheduledTaskByIDRow
	err := row.Scan(
		&i.ScheduledTask.ID,
		&i.ScheduledTask.Uuid,
		&i.ScheduledTask.TeamID,
		&i.ScheduledTask.ResourceID,
		&i.ScheduledTask.Container,
		&i.ScheduledTask.Name,
		&i.ScheduledTask.Command,
		&i.ScheduledTask.CronExpression,
		&i.ScheduledTask.Timezone,
		&i.ScheduledTask.Enabled,
		&i.ScheduledTask.OverlapPolicy,
		&i.ScheduledTask.MissedRunPolicy,
		&i.ScheduledTask.TimeoutSeconds,
		&i.ScheduledTask.NextRunAt,
		&i.ScheduledTask.LastRunAt,
		&i.ScheduledTask.CreatedBy,
		&i.ScheduledTask.UpdatedBy,
		&i.ScheduledTask.CreatedAt,
		&i.ScheduledTask.UpdatedAt,
		&i.ScheduledTask.DeletedAt,
		&i.ScheduledTask.Version,
		&i.ApplicationUuid,
	)
	return i, err
}

const getScheduledTaskByUUID = `-- name: GetScheduledTaskByUUID :one
SELECT t.id, t.uuid, t.team_id, t.resource_id, t.container, t.name, t.command, t.cron_expression, t.timezone, t.enabled, t.overlap_policy, t.missed_run_policy, t.timeout_seconds, t.next_run_at, t.last_run_at, t.created_by, t.updated_by, t.created_at, t.updated_at, t.deleted_at, t.version, r.uuid AS application_uuid
FROM scheduled_tasks t
JOIN resources r ON r.id = t.resource_id
WHERE t.uuid = $1 AND t.team_id = $2 AND t.deleted_at IS NULL
`

type GetScheduledTaskByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

type GetScheduledTaskByUUIDRow struct {
	ScheduledTask   ScheduledTask
	ApplicationUuid pgtype.UUID
}

func (q *Queries) GetScheduledTaskByUUID(ctx context.Context, arg GetScheduledTaskByUUIDParams) (GetScheduledTaskByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getScheduledTaskByUUID, arg.Uuid, arg.TeamID)
	var i GetScheduledTaskByUUIDRow
	err := row.Scan(
		&i.ScheduledTask.ID,
		&i.ScheduledTask.Uuid,
		&i.ScheduledTask.TeamID,
		&i.ScheduledTask.ResourceID,
		&i.ScheduledTask.Container,
		&i.ScheduledTask.Name,
		&i.ScheduledTask.Command,
		&i.ScheduledTask.CronExpression,
		&i.ScheduledTask.Timezone,
		&i.ScheduledTask.Enabled,
		&i.ScheduledTask.OverlapPolicy,
		&i.ScheduledTask.MissedRunPolicy,
		&i.ScheduledTask.TimeoutSeconds,
		&i.ScheduledTask.NextRunAt,
		&i.ScheduledTask.LastRunAt,
		&i.ScheduledTask.CreatedBy,
		&i.ScheduledTask.UpdatedBy,
		&i.ScheduledTask.CreatedAt,
		&i.ScheduledTask.UpdatedAt,
		&i.ScheduledTask.DeletedAt,
		&i.ScheduledTask.Version,
		&i.ApplicationUuid,
	)
	return i, err
}

const listSchedulableTasks = `-- name: ListSchedulableTasks :many
SELECT t.id, t.uuid, t.team_id, t.resource_id, t.container, t.name, t.command, t.cron_expression, t.timezone, t.enabled, t.overlap_policy, t.missed_run_policy, t.timeout_seconds, t.next_run_at, t.last_run_at, t.created_by, t.updated_by, t.created_at, t.updated_at, t.deleted_at, t.version, r.uuid AS application_uuid
FROM scheduled_tasks t
JOIN resources r ON r.id = t.resource_id
WHERE t.enabled AND t.deleted_at IS NULL AND r.deleted_at IS NULL
`

type ListSchedulableTasksRow struct {
	ScheduledTask   ScheduledTask
	ApplicationUuid pgtype.UUID
}

// Every enabled task of a live resource. The scheduler decides what is due:
// a task whose next_run_at is NULL has never been scheduled and must be
// seeded, so it cannot be filtered out here.
func (q *Queries) ListSchedulableTasks(ctx context.Context) ([]ListSchedulableTasksRow, error) {
	rows, err := q.db.Query(ctx, listSchedulableTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulableTasksRow
	for rows.Next() {
		var i ListSchedulableTasksRow
		if err := rows.Scan(
			&i.ScheduledTask.ID,
			&i.ScheduledTask.Uuid,
			&i.ScheduledTask.TeamID,
			&i.ScheduledTask.ResourceID,
			&i.ScheduledTask.Container,
			&i.ScheduledTask.Name,
			&i.ScheduledTask.Command,
			&i.ScheduledTask.CronExpression,
			&i.ScheduledTask.Timezone,
			&i.ScheduledTask.Enabled,
			&i.ScheduledTask.OverlapPolicy,
			&i.ScheduledTask.MissedRunPolicy,
			&i.ScheduledTask.TimeoutSeconds,
			&i.ScheduledTask.NextRunAt,
			&i.ScheduledTask.LastRunAt,
			&i.ScheduledTask.CreatedBy,
			&i.ScheduledTask.UpdatedBy,
			&i.ScheduledTask.CreatedAt,
			&i.ScheduledTask.UpdatedAt,
			&i.ScheduledTask.DeletedAt,
			&i.ScheduledTask.Version,
			&i.ApplicationUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasksPage = `-- name: ListScheduledTasksPage :many
SELECT t.id, t.uuid, t.team_id, t.resource_id, t.container, t.name, t.command, t.cron_expression, t.timezone, t.enabled, t.overlap_policy, t.missed_run_policy, t.timeout_seconds, t.next_run_at, t.last_run_at, t.created_by, t.updated_by, t.created_at, t.updated_at, t.deleted_at, t.version, r.uuid AS application_uuid
FROM scheduled_tasks t
JOIN resources r ON r.id = t.resource_id
WHERE t.resource_id = $1 AND t.deleted_at IS NULL
  AND ($2::bigint = 0 OR t.id < $2)
ORDER BY t.id DESC
LIMIT $3
`

type ListScheduledTasksPageParams struct {
	ResourceID int64
	AfterID    int64
	PageLimit  int32
}

type ListScheduledTasksPageRow struct {
	ScheduledTask   ScheduledTask
	ApplicationUuid pgtype.UUID
}

func (q *Queries) ListScheduledTasksPage(ctx context.Context, arg ListScheduledTasksPageParams) ([]ListScheduledTasksPageRow, error) {
	rows, err := q.db.Query(ctx, listScheduledTasksPage, arg.ResourceID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledTasksPageRow
	for rows.Next() {
		var i ListScheduledTasksPageRow
		if err := rows.Scan(
			&i.ScheduledTask.ID,
			&i.ScheduledTask.Uuid,
			&i.ScheduledTask.TeamID,
			&i.ScheduledTask.ResourceID,
			&i.ScheduledTask.Container,
			&i.ScheduledTask.Name,
			&i.ScheduledTask.Command,
			&i.ScheduledTask.CronExpression,
			&i.ScheduledTask.Timezone,
			&i.ScheduledTask.Enabled,
			&i.ScheduledTask.OverlapPolicy,
			&i.ScheduledTask.MissedRunPolicy,
			&i.ScheduledTask.TimeoutSeconds,
			&i.ScheduledTask.NextRunAt,
			&i.ScheduledTask.LastRunAt,
			&i.ScheduledTask.CreatedBy,
			&i.ScheduledTask.UpdatedBy,
			&i.ScheduledTask.CreatedAt,
			&i.ScheduledTask.UpdatedAt,
			&i.ScheduledTask.DeletedAt,
			&i.ScheduledTask.Version,
			&i.ApplicationUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutionsPage = `-- name: ListTaskExecutionsPage :many
SELECT id, uuid, scheduled_task_id, status, skip_reason, exit_code, output, output_truncated, started_at, finished_at, duration_ms FROM task_executions
WHERE scheduled_task_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListTaskExecutionsPageParams struct {
	TaskID    int64
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListTaskExecutionsPage(ctx context.Context, arg ListTaskExecutionsPageParams) ([]TaskExecution, error) {
	rows, err := q.db.Query(ctx, listTaskExecutionsPage, arg.TaskID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ScheduledTaskID,
			&i.Status,
			&i.SkipReason,
			&i.ExitCode,
			&i.Output,
			&i.OutputTruncated,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScheduledTaskSchedule = `-- name: SetScheduledTaskSchedule :exec
UPDATE scheduled_tasks
SET next_run_at = COALESCE($2::timestamptz, next_run_at),
    last_run_at = COALESCE($3::timestamptz, last_run_at)
WHERE id = $1
`

type SetScheduledTaskScheduleParams struct {
	ID        int64
	NextRunAt pgtype.Timestamptz
	LastRunAt pgtype.Timestamptz
}

func (q *Queries) SetScheduledTaskSchedule(ctx context.Context, arg SetScheduledTaskScheduleParams) error {
	_, err := q.db.Exec(ctx, setScheduledTaskSchedule, arg.ID, arg.NextRunAt, arg.LastRunAt)
	return err
}

const softDeleteScheduledTask = `-- name: SoftDeleteScheduledTask :execrows
UPDATE scheduled_tasks SET deleted_at = now(), enabled = false
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteScheduledTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteScheduledTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScheduledTask = `-- name: UpdateScheduledTask :execrows
UPDATE scheduled_tasks
SET name = COALESCE($1, name),
    command = COALESCE($2, command),
    container = CASE WHEN $3::boolean THEN $4 ELSE container END,
    cron_expression = COALESCE($5, cron_expression),
    timezone = COALESCE($6, timezone),
    enabled = COALESCE($7, enabled),
    overlap_policy = COALESCE($8, overlap_policy),
    missed_run_policy = COALESCE($9, missed_run_policy),
    timeout_seconds = COALESCE($10, timeout_seconds),
    -- A changed cron means the old window is meaningless: dropping next_run_at
    -- forces the scheduler to recompute it from the new expression.
    next_run_at = CASE WHEN $5 IS NOT NULL OR $6 IS NOT NULL THEN NULL ELSE next_run_at END,
    updated_at = now(),
    updated_by = $11,
    version = version + 1
WHERE id = $12 AND version = $13 AND deleted_at IS NULL
`

type UpdateScheduledTaskParams struct {
	Name            *string
	Command         *string
	SetContainer    bool
	Container       *string
	CronExpression  *string
	Timezone        *string
	Enabled         *bool
	OverlapPolicy   *TaskOverlapPolicy
	MissedRunPolicy *TaskMissedRunPolicy
	TimeoutSeconds  *int32
	UpdatedBy       *int64
	ID              int64
	Version         int32
}

func (q *Queries) UpdateScheduledTask(ctx context.Context, arg UpdateScheduledTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduledTask,
		arg.Name,
		arg.Command,
		arg.SetContainer,
		arg.Container,
		arg.CronExpression,
		arg.Timezone,
		arg.Enabled,
		arg.OverlapPolicy,
		arg.MissedRunPolicy,
		arg.TimeoutSeconds,
		arg.UpdatedBy,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
