// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScimToken = `-- name: CreateScimToken :one

INSERT INTO scim_tokens (team_id, name, token_hash, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, team_id, name, token_hash, created_by, last_used_at, revoked_at, created_at
`

type CreateScimTokenParams struct {
	TeamID    int64
	Name      string
	TokenHash string
	CreatedBy *int64
}

// SCIM 2.0 provisioning (ADR-038 bis). A SCIM token is scoped to one team; the
// endpoints authenticate with it and act only within that team.
func (q *Queries) CreateScimToken(ctx context.Context, arg CreateScimTokenParams) (ScimToken, error) {
	row := q.db.QueryRow(ctx, createScimToken,
		arg.TeamID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
	)
	var i ScimToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScimMember = `-- name: GetScimMember :one
SELECT u.id AS user_id, u.uuid AS user_uuid, u.email, u.name, m.role, m.external_id
FROM team_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
WHERE m.team_id = $1 AND u.uuid = $2
`

type GetScimMemberParams struct {
	TeamID int64
	Uuid   pgtype.UUID
}

type GetScimMemberRow struct {
	UserID     int64
	UserUuid   pgtype.UUID
	Email      string
	Name       string
	Role       TeamRole
	ExternalID *string
}

// A team member by user UUID (the SCIM resource id), with the internal user id
// needed to revoke sessions on deprovision.
func (q *Queries) GetScimMember(ctx context.Context, arg GetScimMemberParams) (GetScimMemberRow, error) {
	row := q.db.QueryRow(ctx, getScimMember, arg.TeamID, arg.Uuid)
	var i GetScimMemberRow
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ExternalID,
	)
	return i, err
}

const getScimTokenByHash = `-- name: GetScimTokenByHash :one
SELECT s.id, s.uuid, s.team_id, t.uuid AS team_uuid
FROM scim_tokens s
JOIN teams t ON t.id = s.team_id AND t.deleted_at IS NULL
WHERE s.token_hash = $1 AND s.revoked_at IS NULL
`

type GetScimTokenByHashRow struct {
	ID       int64
	Uuid     pgtype.UUID
	TeamID   int64
	TeamUuid pgtype.UUID
}

// Resolves a bearer SCIM token to its team; unrevoked only.
func (q *Queries) GetScimTokenByHash(ctx context.Context, tokenHash string) (GetScimTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getScimTokenByHash, tokenHash)
	var i GetScimTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.TeamUuid,
	)
	return i, err
}

const getTeamMemberByExternalID = `-- name: GetTeamMemberByExternalID :one
SELECT m.id AS membership_id, m.role, m.external_id, m.custom_role_id,
       u.id AS user_id, u.uuid AS user_uuid, u.email, u.name
FROM team_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
WHERE m.team_id = $1 AND m.external_id = $2
`

type GetTeamMemberByExternalIDParams struct {
	TeamID     int64
	ExternalID *string
}

type GetTeamMemberByExternalIDRow struct {
	MembershipID int64
	Role         TeamRole
	ExternalID   *string
	CustomRoleID *int64
	UserID       int64
	UserUuid     pgtype.UUID
	Email        string
	Name         string
}

// Idempotent match for a SCIM-provisioned member (the IdP's externalId).
func (q *Queries) GetTeamMemberByExternalID(ctx context.Context, arg GetTeamMemberByExternalIDParams) (GetTeamMemberByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByExternalID, arg.TeamID, arg.ExternalID)
	var i GetTeamMemberByExternalIDRow
	err := row.Scan(
		&i.MembershipID,
		&i.Role,
		&i.ExternalID,
		&i.CustomRoleID,
		&i.UserID,
		&i.UserUuid,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const listScimTokensPage = `-- name: ListScimTokensPage :many
SELECT id, uuid, team_id, name, token_hash, created_by, last_used_at, revoked_at, created_at FROM scim_tokens
WHERE team_id = $1 AND revoked_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListScimTokensPage(ctx context.Context, teamID int64) ([]ScimToken, error) {
	rows, err := q.db.Query(ctx, listScimTokensPage, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimToken
	for rows.Next() {
		var i ScimToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersForScim = `-- name: ListTeamMembersForScim :many
SELECT m.role, m.external_id, m.created_at AS joined_at,
       u.uuid AS user_uuid, u.email, u.name,
       cr.uuid AS custom_role_uuid, cr.name AS custom_role_name
FROM team_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
LEFT JOIN custom_roles cr ON cr.id = m.custom_role_id
WHERE m.team_id = $1
ORDER BY m.id DESC
`

type ListTeamMembersForScimRow struct {
	Role           TeamRole
	ExternalID     *string
	JoinedAt       pgtype.Timestamptz
	UserUuid       pgtype.UUID
	Email          string
	Name           string
	CustomRoleUuid pgtype.UUID
	CustomRoleName *string
}

// SCIM Users/Groups source: every member with its effective role (system role,
// or the custom role uuid when set) so groups (=roles) can be assembled in Go.
func (q *Queries) ListTeamMembersForScim(ctx context.Context, teamID int64) ([]ListTeamMembersForScimRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersForScim, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersForScimRow
	for rows.Next() {
		var i ListTeamMembersForScimRow
		if err := rows.Scan(
			&i.Role,
			&i.ExternalID,
			&i.JoinedAt,
			&i.UserUuid,
			&i.Email,
			&i.Name,
			&i.CustomRoleUuid,
			&i.CustomRoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMemberByUUID = `-- name: RemoveTeamMemberByUUID :execrows
DELETE FROM team_memberships tm
USING users u
WHERE tm.user_id = u.id AND u.uuid = $1 AND tm.team_id = $2
`

type RemoveTeamMemberByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

// Deprovision: drop the membership (the account and its sessions are handled
// separately). Team-scoped by the member's user UUID.
func (q *Queries) RemoveTeamMemberByUUID(ctx context.Context, arg RemoveTeamMemberByUUIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMemberByUUID, arg.Uuid, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeApiTokensForUserInTeam = `-- name: RevokeApiTokensForUserInTeam :execrows
UPDATE api_tokens SET revoked_at = now()
WHERE team_id = $1 AND created_by = $2 AND revoked_at IS NULL
`

type RevokeApiTokensForUserInTeamParams struct {
	TeamID    int64
	CreatedBy *int64
}

// Deprovision: revoke every API token the user holds in this team.
func (q *Queries) RevokeApiTokensForUserInTeam(ctx context.Context, arg RevokeApiTokensForUserInTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeApiTokensForUserInTeam, arg.TeamID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeScimToken = `-- name: RevokeScimToken :execrows
UPDATE scim_tokens SET revoked_at = now() WHERE uuid = $1 AND team_id = $2 AND revoked_at IS NULL
`

type RevokeScimTokenParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) RevokeScimToken(ctx context.Context, arg RevokeScimTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeScimToken, arg.Uuid, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMembershipExternalID = `-- name: SetMembershipExternalID :exec
UPDATE team_memberships tm SET external_id = $1
FROM users u
WHERE tm.user_id = u.id AND u.uuid = $2 AND tm.team_id = $3
`

type SetMembershipExternalIDParams struct {
	ExternalID *string
	UserUuid   pgtype.UUID
	TeamID     int64
}

func (q *Queries) SetMembershipExternalID(ctx context.Context, arg SetMembershipExternalIDParams) error {
	_, err := q.db.Exec(ctx, setMembershipExternalID, arg.ExternalID, arg.UserUuid, arg.TeamID)
	return err
}

const touchScimTokenUsed = `-- name: TouchScimTokenUsed :exec
UPDATE scim_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchScimTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchScimTokenUsed, id)
	return err
}
