// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_memberships (team_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO NOTHING
`

type AddTeamMemberParams struct {
	TeamID int64
	UserID int64
	Role   TeamRole
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const clearFailedLogins = `-- name: ClearFailedLogins :exec
UPDATE users SET failed_login_count = 0, locked_until = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearFailedLogins(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearFailedLogins, id)
	return err
}

const createPersonalTeam = `-- name: CreatePersonalTeam :one
INSERT INTO teams (name, personal) VALUES ($1, true) RETURNING id, uuid, name, description, created_by, updated_by, created_at, updated_at, deleted_at, version, personal
`

func (q *Queries) CreatePersonalTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createPersonalTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.Personal,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, csrf_token, current_team_id, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uuid, user_id, token_hash, current_team_id, mfa_verified_at, ip, user_agent, last_seen_at, expires_at, revoked_at, created_at, csrf_token
`

type CreateSessionParams struct {
	UserID        int64
	TokenHash     string
	CsrfToken     *string
	CurrentTeamID *int64
	Ip            *netip.Addr
	UserAgent     *string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.CurrentTeamID,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.TokenHash,
		&i.CurrentTeamID,
		&i.MfaVerifiedAt,
		&i.Ip,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CsrfToken,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.uuid, s.user_id, s.token_hash, s.current_team_id, s.mfa_verified_at, s.ip, s.user_agent, s.last_seen_at, s.expires_at, s.revoked_at, s.created_at, s.csrf_token, u.email, u.name AS user_name, u.deleted_at AS user_deleted_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.deleted_at IS NULL
`

type GetSessionByTokenHashRow struct {
	ID            int64
	Uuid          pgtype.UUID
	UserID        int64
	TokenHash     string
	CurrentTeamID *int64
	MfaVerifiedAt pgtype.Timestamptz
	Ip            *netip.Addr
	UserAgent     *string
	LastSeenAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	CsrfToken     *string
	Email         string
	UserName      string
	UserDeletedAt pgtype.Timestamptz
}

// A session is only valid while it is unrevoked AND unexpired: both are checked
// in SQL so no caller can forget one of them.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.TokenHash,
		&i.CurrentTeamID,
		&i.MfaVerifiedAt,
		&i.Ip,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CsrfToken,
		&i.Email,
		&i.UserName,
		&i.UserDeletedAt,
	)
	return i, err
}

const getTeamMembershipForUser = `-- name: GetTeamMembershipForUser :one
SELECT tm.team_id, tm.role, t.uuid AS team_uuid, u.is_root FROM team_memberships tm
JOIN teams t ON t.id = tm.team_id
JOIN users u ON u.id = tm.user_id
WHERE tm.user_id = $1
ORDER BY tm.team_id
LIMIT 1
`

type GetTeamMembershipForUserRow struct {
	TeamID   int64
	Role     TeamRole
	TeamUuid pgtype.UUID
	IsRoot   bool
}

// The team a session acts in, with its role and public UUID (the dashboard
// addresses team endpoints by UUID). Falls back to the personal team.
// Carries the user's instance-root flag (users.is_root) so the session identity
// can gate instance-wide settings (rbac-matrix §3.5).
func (q *Queries) GetTeamMembershipForUser(ctx context.Context, userID int64) (GetTeamMembershipForUserRow, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipForUser, userID)
	var i GetTeamMembershipForUserRow
	err := row.Scan(
		&i.TeamID,
		&i.Role,
		&i.TeamUuid,
		&i.IsRoot,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, uuid, email, name, password_hash, is_root, email_verified_at, failed_login_count, locked_until, created_at, updated_at, deleted_at, version FROM users WHERE email = $1 AND deleted_at IS NULL
`

// Browser sessions (PRD §698).
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsRoot,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE
        WHEN failed_login_count + 1 >= $2::int
        THEN now() + make_interval(mins => $3::int)
        ELSE locked_until
    END,
    updated_at = now()
WHERE id = $1
RETURNING failed_login_count, locked_until
`

type RecordFailedLoginParams struct {
	ID          int64
	MaxAttempts int32
	LockMinutes int32
}

type RecordFailedLoginRow struct {
	FailedLoginCount int32
	LockedUntil      pgtype.Timestamptz
}

// Counts the failure and locks the account past the threshold. Returns the row
// so the caller can tell "locked now" from "still open".
func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.ID, arg.MaxAttempts, arg.LockMinutes)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const revokeAllSessionsOfUser = `-- name: RevokeAllSessionsOfUser :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

// Used on logout-everywhere and on any credential change: a password reset that
// leaves old sessions alive has reset nothing.
func (q *Queries) RevokeAllSessionsOfUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessionsOfUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
