// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const setApiEnabled = `-- name: SetApiEnabled :one

UPDATE instance_settings
SET api_enabled = $1, updated_at = now(), version = version + 1
WHERE id = 1
RETURNING id, fqdn, timezone, registration_enabled, api_enabled, dns_validation_server, transactional_email_config_enc, auto_update_enabled, auto_update_cron, onboarding_completed_at, updated_by, created_at, updated_at, version, acme_email, localhost_seeded, otlp_config_enc, mfa_required, password_login_disabled, image_retention_count
`

// Instance settings mutations (§14.2).
func (q *Queries) SetApiEnabled(ctx context.Context, apiEnabled bool) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, setApiEnabled, apiEnabled)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.Timezone,
		&i.RegistrationEnabled,
		&i.ApiEnabled,
		&i.DnsValidationServer,
		&i.TransactionalEmailConfigEnc,
		&i.AutoUpdateEnabled,
		&i.AutoUpdateCron,
		&i.OnboardingCompletedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AcmeEmail,
		&i.LocalhostSeeded,
		&i.OtlpConfigEnc,
		&i.MfaRequired,
		&i.PasswordLoginDisabled,
		&i.ImageRetentionCount,
	)
	return i, err
}

const setImageRetentionCount = `-- name: SetImageRetentionCount :one
UPDATE instance_settings
SET image_retention_count = $1, updated_at = now(), version = version + 1
WHERE id = 1
RETURNING id, fqdn, timezone, registration_enabled, api_enabled, dns_validation_server, transactional_email_config_enc, auto_update_enabled, auto_update_cron, onboarding_completed_at, updated_by, created_at, updated_at, version, acme_email, localhost_seeded, otlp_config_enc, mfa_required, password_login_disabled, image_retention_count
`

// Rollback image retention (ADR-006, §29.4). The CHECK (>= 1) keeps the live
// image protected even at the smallest setting.
func (q *Queries) SetImageRetentionCount(ctx context.Context, imageRetentionCount int32) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, setImageRetentionCount, imageRetentionCount)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.Timezone,
		&i.RegistrationEnabled,
		&i.ApiEnabled,
		&i.DnsValidationServer,
		&i.TransactionalEmailConfigEnc,
		&i.AutoUpdateEnabled,
		&i.AutoUpdateCron,
		&i.OnboardingCompletedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AcmeEmail,
		&i.LocalhostSeeded,
		&i.OtlpConfigEnc,
		&i.MfaRequired,
		&i.PasswordLoginDisabled,
		&i.ImageRetentionCount,
	)
	return i, err
}

const setInstanceIdentity = `-- name: SetInstanceIdentity :one
UPDATE instance_settings
SET fqdn = $1, acme_email = $2, updated_at = now(), version = version + 1
WHERE id = 1
RETURNING id, fqdn, timezone, registration_enabled, api_enabled, dns_validation_server, transactional_email_config_enc, auto_update_enabled, auto_update_cron, onboarding_completed_at, updated_by, created_at, updated_at, version, acme_email, localhost_seeded, otlp_config_enc, mfa_required, password_login_disabled, image_retention_count
`

type SetInstanceIdentityParams struct {
	Fqdn      *string
	AcmeEmail *string
}

// FQDN + contact ACME (§14.2) : la base fait foi après le premier démarrage,
// c'est donc ici — et nulle part ailleurs — qu'ils se modifient.
func (q *Queries) SetInstanceIdentity(ctx context.Context, arg SetInstanceIdentityParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, setInstanceIdentity, arg.Fqdn, arg.AcmeEmail)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.Timezone,
		&i.RegistrationEnabled,
		&i.ApiEnabled,
		&i.DnsValidationServer,
		&i.TransactionalEmailConfigEnc,
		&i.AutoUpdateEnabled,
		&i.AutoUpdateCron,
		&i.OnboardingCompletedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AcmeEmail,
		&i.LocalhostSeeded,
		&i.OtlpConfigEnc,
		&i.MfaRequired,
		&i.PasswordLoginDisabled,
		&i.ImageRetentionCount,
	)
	return i, err
}

const setMfaRequired = `-- name: SetMfaRequired :one
UPDATE instance_settings
SET mfa_required = $1, updated_at = now(), version = version + 1
WHERE id = 1
RETURNING id, fqdn, timezone, registration_enabled, api_enabled, dns_validation_server, transactional_email_config_enc, auto_update_enabled, auto_update_cron, onboarding_completed_at, updated_by, created_at, updated_at, version, acme_email, localhost_seeded, otlp_config_enc, mfa_required, password_login_disabled, image_retention_count
`

func (q *Queries) SetMfaRequired(ctx context.Context, mfaRequired bool) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, setMfaRequired, mfaRequired)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.Timezone,
		&i.RegistrationEnabled,
		&i.ApiEnabled,
		&i.DnsValidationServer,
		&i.TransactionalEmailConfigEnc,
		&i.AutoUpdateEnabled,
		&i.AutoUpdateCron,
		&i.OnboardingCompletedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AcmeEmail,
		&i.LocalhostSeeded,
		&i.OtlpConfigEnc,
		&i.MfaRequired,
		&i.PasswordLoginDisabled,
		&i.ImageRetentionCount,
	)
	return i, err
}

const setPasswordLoginDisabled = `-- name: SetPasswordLoginDisabled :one
UPDATE instance_settings
SET password_login_disabled = $1, updated_at = now(), version = version + 1
WHERE id = 1
RETURNING id, fqdn, timezone, registration_enabled, api_enabled, dns_validation_server, transactional_email_config_enc, auto_update_enabled, auto_update_cron, onboarding_completed_at, updated_by, created_at, updated_at, version, acme_email, localhost_seeded, otlp_config_enc, mfa_required, password_login_disabled, image_retention_count
`

func (q *Queries) SetPasswordLoginDisabled(ctx context.Context, passwordLoginDisabled bool) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, setPasswordLoginDisabled, passwordLoginDisabled)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.Timezone,
		&i.RegistrationEnabled,
		&i.ApiEnabled,
		&i.DnsValidationServer,
		&i.TransactionalEmailConfigEnc,
		&i.AutoUpdateEnabled,
		&i.AutoUpdateCron,
		&i.OnboardingCompletedAt,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AcmeEmail,
		&i.LocalhostSeeded,
		&i.OtlpConfigEnc,
		&i.MfaRequired,
		&i.PasswordLoginDisabled,
		&i.ImageRetentionCount,
	)
	return i, err
}
