// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sharedvars.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSharedVariable = `-- name: CreateSharedVariable :one

INSERT INTO shared_variables (uuid, team_id, scope, project_id, environment_id, server_id, key, value_enc, is_secret, created_by)
VALUES ($1, $2, $3, $7, $8, $9, $4, $5, $6, $10)
RETURNING id, uuid, team_id, scope, project_id, environment_id, server_id, key, value_enc, is_secret, created_by, updated_by, created_at, updated_at
`

type CreateSharedVariableParams struct {
	Uuid          pgtype.UUID
	TeamID        int64
	Scope         SharedVariableScope
	Key           string
	ValueEnc      []byte
	IsSecret      bool
	ProjectID     *int64
	EnvironmentID *int64
	ServerID      *int64
	CreatedBy     *int64
}

// Shared variables (§5.4, §3.1).
func (q *Queries) CreateSharedVariable(ctx context.Context, arg CreateSharedVariableParams) (SharedVariable, error) {
	row := q.db.QueryRow(ctx, createSharedVariable,
		arg.Uuid,
		arg.TeamID,
		arg.Scope,
		arg.Key,
		arg.ValueEnc,
		arg.IsSecret,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ServerID,
		arg.CreatedBy,
	)
	var i SharedVariable
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Scope,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServerID,
		&i.Key,
		&i.ValueEnc,
		&i.IsSecret,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSharedVariable = `-- name: DeleteSharedVariable :execrows
DELETE FROM shared_variables WHERE id = $1
`

func (q *Queries) DeleteSharedVariable(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSharedVariable, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSharedVariableByUUID = `-- name: GetSharedVariableByUUID :one
SELECT id, uuid, team_id, scope, project_id, environment_id, server_id, key, value_enc, is_secret, created_by, updated_by, created_at, updated_at FROM shared_variables WHERE uuid = $1 AND team_id = $2
`

type GetSharedVariableByUUIDParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) GetSharedVariableByUUID(ctx context.Context, arg GetSharedVariableByUUIDParams) (SharedVariable, error) {
	row := q.db.QueryRow(ctx, getSharedVariableByUUID, arg.Uuid, arg.TeamID)
	var i SharedVariable
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Scope,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServerID,
		&i.Key,
		&i.ValueEnc,
		&i.IsSecret,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSharedVariablesForResource = `-- name: ListSharedVariablesForResource :many
SELECT sv.id, sv.uuid, sv.team_id, sv.scope, sv.project_id, sv.environment_id, sv.server_id, sv.key, sv.value_enc, sv.is_secret, sv.created_by, sv.updated_by, sv.created_at, sv.updated_at FROM shared_variables sv
JOIN resources r ON r.id = $1
JOIN environments e ON e.id = r.environment_id
JOIN destinations d ON d.id = r.destination_id
WHERE sv.team_id = r.team_id AND (
    sv.scope = 'team'
    OR (sv.scope = 'project' AND sv.project_id = e.project_id)
    OR (sv.scope = 'environment' AND sv.environment_id = r.environment_id)
    OR (sv.scope = 'server' AND sv.server_id = d.server_id))
ORDER BY sv.id
`

// Everything a deployment of this resource inherits (§5.4): the team's
// variables, the ones of its project and environment, and the server-scoped
// variables of its destination server.
func (q *Queries) ListSharedVariablesForResource(ctx context.Context, resourceID int64) ([]SharedVariable, error) {
	rows, err := q.db.Query(ctx, listSharedVariablesForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SharedVariable
	for rows.Next() {
		var i SharedVariable
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Scope,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServerID,
			&i.Key,
			&i.ValueEnc,
			&i.IsSecret,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariablesPage = `-- name: ListSharedVariablesPage :many
SELECT id, uuid, team_id, scope, project_id, environment_id, server_id, key, value_enc, is_secret, created_by, updated_by, created_at, updated_at FROM shared_variables
WHERE team_id = $1
  AND ($2::shared_variable_scope IS NULL OR scope = $2::shared_variable_scope)
  AND ($3::bigint = 0 OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListSharedVariablesPageParams struct {
	TeamID    int64
	Scope     *SharedVariableScope
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListSharedVariablesPage(ctx context.Context, arg ListSharedVariablesPageParams) ([]SharedVariable, error) {
	rows, err := q.db.Query(ctx, listSharedVariablesPage,
		arg.TeamID,
		arg.Scope,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SharedVariable
	for rows.Next() {
		var i SharedVariable
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Scope,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServerID,
			&i.Key,
			&i.ValueEnc,
			&i.IsSecret,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSharedVariable = `-- name: UpdateSharedVariable :execrows
UPDATE shared_variables
SET value_enc = $2, is_secret = $3, updated_at = now()
WHERE id = $1
`

type UpdateSharedVariableParams struct {
	ID       int64
	ValueEnc []byte
	IsSecret bool
}

func (q *Queries) UpdateSharedVariable(ctx context.Context, arg UpdateSharedVariableParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSharedVariable, arg.ID, arg.ValueEnc, arg.IsSecret)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
