// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdoptedStorage = `-- name: CreateAdoptedStorage :one
INSERT INTO persistent_storages (uuid, resource_id, kind, name, host_path, mount_path, external_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uuid, resource_id, kind, name, host_path, mount_path, content, is_directory, file_mode, owner_uid, group_gid, created_by, updated_by, created_at, updated_at, external_name, is_generated
`

type CreateAdoptedStorageParams struct {
	Uuid         pgtype.UUID
	ResourceID   int64
	Kind         StorageKind
	Name         *string
	HostPath     *string
	MountPath    string
	ExternalName *string
}

// Adoption (§20.7): external_name keeps the original Docker volume name so
// the normalizing redeployment remounts the SAME data (INV-008).
func (q *Queries) CreateAdoptedStorage(ctx context.Context, arg CreateAdoptedStorageParams) (PersistentStorage, error) {
	row := q.db.QueryRow(ctx, createAdoptedStorage,
		arg.Uuid,
		arg.ResourceID,
		arg.Kind,
		arg.Name,
		arg.HostPath,
		arg.MountPath,
		arg.ExternalName,
	)
	var i PersistentStorage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Kind,
		&i.Name,
		&i.HostPath,
		&i.MountPath,
		&i.Content,
		&i.IsDirectory,
		&i.FileMode,
		&i.OwnerUid,
		&i.GroupGid,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalName,
		&i.IsGenerated,
	)
	return i, err
}

const createGeneratedStorage = `-- name: CreateGeneratedStorage :exec
INSERT INTO persistent_storages (uuid, resource_id, kind, name, mount_path, external_name, is_generated)
VALUES ($1, $2, 'volume', $3, $4, $5, true)
`

type CreateGeneratedStorageParams struct {
	Uuid         pgtype.UUID
	ResourceID   int64
	Name         *string
	MountPath    string
	ExternalName *string
}

func (q *Queries) CreateGeneratedStorage(ctx context.Context, arg CreateGeneratedStorageParams) error {
	_, err := q.db.Exec(ctx, createGeneratedStorage,
		arg.Uuid,
		arg.ResourceID,
		arg.Name,
		arg.MountPath,
		arg.ExternalName,
	)
	return err
}

const createStorage = `-- name: CreateStorage :one

INSERT INTO persistent_storages (uuid, resource_id, kind, name, host_path, mount_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, resource_id, kind, name, host_path, mount_path, content, is_directory, file_mode, owner_uid, group_gid, created_by, updated_by, created_at, updated_at, external_name, is_generated
`

type CreateStorageParams struct {
	Uuid       pgtype.UUID
	ResourceID int64
	Kind       StorageKind
	Name       *string
	HostPath   *string
	MountPath  string
}

// Persistent storages (§8).
func (q *Queries) CreateStorage(ctx context.Context, arg CreateStorageParams) (PersistentStorage, error) {
	row := q.db.QueryRow(ctx, createStorage,
		arg.Uuid,
		arg.ResourceID,
		arg.Kind,
		arg.Name,
		arg.HostPath,
		arg.MountPath,
	)
	var i PersistentStorage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Kind,
		&i.Name,
		&i.HostPath,
		&i.MountPath,
		&i.Content,
		&i.IsDirectory,
		&i.FileMode,
		&i.OwnerUid,
		&i.GroupGid,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalName,
		&i.IsGenerated,
	)
	return i, err
}

const deleteGeneratedStoragesForResource = `-- name: DeleteGeneratedStoragesForResource :exec
DELETE FROM persistent_storages WHERE resource_id = $1 AND is_generated
`

// The compose-mirrored rows (§2.4): rewritten wholesale at each deployment —
// the FILE is the source of truth, these rows only make it visible.
func (q *Queries) DeleteGeneratedStoragesForResource(ctx context.Context, resourceID int64) error {
	_, err := q.db.Exec(ctx, deleteGeneratedStoragesForResource, resourceID)
	return err
}

const deleteStorage = `-- name: DeleteStorage :execrows
DELETE FROM persistent_storages WHERE id = $1
`

func (q *Queries) DeleteStorage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStorage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStorageByUUID = `-- name: GetStorageByUUID :one
SELECT id, uuid, resource_id, kind, name, host_path, mount_path, content, is_directory, file_mode, owner_uid, group_gid, created_by, updated_by, created_at, updated_at, external_name, is_generated FROM persistent_storages WHERE uuid = $1 AND resource_id = $2
`

type GetStorageByUUIDParams struct {
	Uuid       pgtype.UUID
	ResourceID int64
}

func (q *Queries) GetStorageByUUID(ctx context.Context, arg GetStorageByUUIDParams) (PersistentStorage, error) {
	row := q.db.QueryRow(ctx, getStorageByUUID, arg.Uuid, arg.ResourceID)
	var i PersistentStorage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ResourceID,
		&i.Kind,
		&i.Name,
		&i.HostPath,
		&i.MountPath,
		&i.Content,
		&i.IsDirectory,
		&i.FileMode,
		&i.OwnerUid,
		&i.GroupGid,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalName,
		&i.IsGenerated,
	)
	return i, err
}

const listStoragesForResource = `-- name: ListStoragesForResource :many
SELECT id, uuid, resource_id, kind, name, host_path, mount_path, content, is_directory, file_mode, owner_uid, group_gid, created_by, updated_by, created_at, updated_at, external_name, is_generated FROM persistent_storages WHERE resource_id = $1 ORDER BY mount_path
`

func (q *Queries) ListStoragesForResource(ctx context.Context, resourceID int64) ([]PersistentStorage, error) {
	rows, err := q.db.Query(ctx, listStoragesForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersistentStorage
	for rows.Next() {
		var i PersistentStorage
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ResourceID,
			&i.Kind,
			&i.Name,
			&i.HostPath,
			&i.MountPath,
			&i.Content,
			&i.IsDirectory,
			&i.FileMode,
			&i.OwnerUid,
			&i.GroupGid,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalName,
			&i.IsGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
