// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO invitations (team_id, email, role, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, team_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	TeamID    int64
	Email     string
	Role      TeamRole
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Invitations (§10.1). The link token is hashed like any credential; the
// clear value is returned only once, at creation.
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one

SELECT id, uuid, name, description, created_by, updated_by, created_at, updated_at, deleted_at, version, personal FROM teams WHERE id = $1 AND deleted_at IS NULL
`

// Teams (§10.1). Cursor pagination follows ERD §12: (team_id, id DESC)
// ordering, opaque cursor carrying the last seen internal id.
func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.Personal,
	)
	return i, err
}

const getTeamByUUID = `-- name: GetTeamByUUID :one
SELECT id, uuid, name, description, created_by, updated_by, created_at, updated_at, deleted_at, version, personal FROM teams WHERE uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTeamByUUID(ctx context.Context, uuid pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByUUID, uuid)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.Personal,
	)
	return i, err
}

const listInvitationsPage = `-- name: ListInvitationsPage :many
SELECT id, uuid, team_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM invitations
WHERE team_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListInvitationsPageParams struct {
	TeamID    int64
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListInvitationsPage(ctx context.Context, arg ListInvitationsPageParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersPage = `-- name: ListTeamMembersPage :many
SELECT m.id AS membership_id, m.role, m.created_at AS joined_at,
       u.uuid AS user_uuid, u.email, u.name
FROM team_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
WHERE m.team_id = $1
  AND ($2::bigint = 0 OR m.id < $2)
ORDER BY m.id DESC
LIMIT $3
`

type ListTeamMembersPageParams struct {
	TeamID    int64
	AfterID   int64
	PageLimit int32
}

type ListTeamMembersPageRow struct {
	MembershipID int64
	Role         TeamRole
	JoinedAt     pgtype.Timestamptz
	UserUuid     pgtype.UUID
	Email        string
	Name         string
}

func (q *Queries) ListTeamMembersPage(ctx context.Context, arg ListTeamMembersPageParams) ([]ListTeamMembersPageRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersPage, arg.TeamID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersPageRow
	for rows.Next() {
		var i ListTeamMembersPageRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.Role,
			&i.JoinedAt,
			&i.UserUuid,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsPage = `-- name: ListTeamsPage :many
SELECT id, uuid, name, description, created_by, updated_by, created_at, updated_at, deleted_at, version, personal FROM teams
WHERE deleted_at IS NULL AND ($1::bigint = 0 OR id < $1)
ORDER BY id DESC
LIMIT $2
`

type ListTeamsPageParams struct {
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListTeamsPage(ctx context.Context, arg ListTeamsPageParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsPage, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.Personal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations SET revoked_at = now()
WHERE uuid = $1 AND team_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	Uuid   pgtype.UUID
	TeamID int64
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.Uuid, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
