// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terminalsessions.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTerminalSession = `-- name: ClaimTerminalSession :one
UPDATE terminal_sessions
SET claimed_at = now(), started_at = now()
WHERE token_hash = $1
  AND claimed_at IS NULL
  AND ended_at IS NULL
  AND token_expires_at > now()
RETURNING id, uuid, team_id, user_id, target_kind, server_id, resource_id, target_name, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at
`

// Single-use attach: the WHERE consumes the token atomically — a replayed
// token matches zero rows, whatever the race. started_at is reset at claim
// time so idle/max-duration windows measure the live session, not the gap
// between issuance and attach.
func (q *Queries) ClaimTerminalSession(ctx context.Context, tokenHash string) (TerminalSession, error) {
	row := q.db.QueryRow(ctx, claimTerminalSession, tokenHash)
	var i TerminalSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.TargetKind,
		&i.ServerID,
		&i.ResourceID,
		&i.TargetName,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const countOpenTerminalSessions = `-- name: CountOpenTerminalSessions :one
SELECT count(*) FROM terminal_sessions
WHERE team_id = $1
  AND ended_at IS NULL
  AND (claimed_at IS NOT NULL OR token_expires_at > now())
`

// Live sessions plus still-claimable tokens: both hold a slot of the per-team
// cap, otherwise issuing tokens in a burst would bypass it.
func (q *Queries) CountOpenTerminalSessions(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTerminalSessions, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTerminalSession = `-- name: CreateTerminalSession :one

INSERT INTO terminal_sessions (
    team_id, user_id, target_kind, server_id, resource_id, target_name,
    client_ip, token_hash, token_expires_at
) VALUES (
    $1, $6, $2, $7, $8, $3,
    $9, $4, $5
)
RETURNING id, uuid, team_id, user_id, target_kind, server_id, resource_id, target_name, client_ip, token_hash, token_expires_at, claimed_at, started_at, ended_at, end_reason, created_at
`

type CreateTerminalSessionParams struct {
	TeamID         int64
	TargetKind     TerminalTarget
	TargetName     string
	TokenHash      string
	TokenExpiresAt pgtype.Timestamptz
	UserID         *int64
	ServerID       *int64
	ResourceID     *int64
	ClientIp       *netip.Addr
}

// Web terminal sessions (PRD §5.7/§24.4, ADR-024, data-dictionary §10.6).
func (q *Queries) CreateTerminalSession(ctx context.Context, arg CreateTerminalSessionParams) (TerminalSession, error) {
	row := q.db.QueryRow(ctx, createTerminalSession,
		arg.TeamID,
		arg.TargetKind,
		arg.TargetName,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.UserID,
		arg.ServerID,
		arg.ResourceID,
		arg.ClientIp,
	)
	var i TerminalSession
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TeamID,
		&i.UserID,
		&i.TargetKind,
		&i.ServerID,
		&i.ResourceID,
		&i.TargetName,
		&i.ClientIp,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.CreatedAt,
	)
	return i, err
}

const endTerminalSession = `-- name: EndTerminalSession :execrows
UPDATE terminal_sessions
SET ended_at = now(), end_reason = $2
WHERE id = $1 AND ended_at IS NULL
`

type EndTerminalSessionParams struct {
	ID        int64
	EndReason *TerminalEndReason
}

// Idempotent: only the first close wins, so end_reason keeps the true cause
// when the WS teardown and a timeout race each other.
func (q *Queries) EndTerminalSession(ctx context.Context, arg EndTerminalSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endTerminalSession, arg.ID, arg.EndReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeTerminalSessions = `-- name: PurgeTerminalSessions :execrows
DELETE FROM terminal_sessions
WHERE ended_at IS NOT NULL
  AND ended_at < now() - make_interval(days => $1::int)
`

func (q *Queries) PurgeTerminalSessions(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTerminalSessions, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionMfaVerified = `-- name: SetSessionMfaVerified :exec
UPDATE sessions SET mfa_verified_at = now() WHERE id = $1
`

// Passkey step-up (rbac-matrix §5): stamps the browser session; freshness is
// judged by the caller against the step-up window.
func (q *Queries) SetSessionMfaVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setSessionMfaVerified, id)
	return err
}

const sweepTerminalSessions = `-- name: SweepTerminalSessions :execrows
UPDATE terminal_sessions
SET ended_at = now(),
    end_reason = CASE WHEN claimed_at IS NULL THEN 'revoked'::terminal_end_reason
                      ELSE 'disconnect'::terminal_end_reason END
WHERE ended_at IS NULL
  AND (
    (claimed_at IS NULL AND token_expires_at < now())
    OR (claimed_at IS NOT NULL AND started_at < now() - make_interval(secs => $1::int))
  )
`

// Crash net: sessions live in-process, so a row left open past any possible
// lifetime is a control-plane restart, not a session. Unclaimed expired
// tokens are closed as revoked.
func (q *Queries) SweepTerminalSessions(ctx context.Context, maxDurationSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, sweepTerminalSessions, maxDurationSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
