-- 2FA TOTP (PRD §10.2, §23.3): one factor per user, envelope-encrypted
-- secret, hashed recovery codes, and the short-lived login challenges of a
-- two-step login.

-- name: GetMfaFactorForUser :one
SELECT * FROM mfa_factors WHERE user_id = $1 AND type = 'totp';

-- name: UpsertUnconfirmedMfaFactor :one
-- Setup creates the factor, or replaces one that was never confirmed (the
-- user scanned a QR code, closed the tab, started over). A CONFIRMED factor
-- is never replaced this way — the WHERE arms the conflict update only for
-- unconfirmed rows, so setup over an active factor returns no row and the
-- caller answers 409. The uuid is generated by the caller: the envelope AAD
-- binds the ciphertext to it before the insert.
INSERT INTO mfa_factors (uuid, user_id, type, secret_enc)
VALUES ($1, $2, 'totp', $3)
ON CONFLICT (user_id, type) DO UPDATE
SET uuid = EXCLUDED.uuid,
    secret_enc = EXCLUDED.secret_enc,
    recovery_code_hashes = '{}',
    confirmed_at = NULL,
    last_used_at = NULL,
    updated_at = now()
WHERE mfa_factors.confirmed_at IS NULL
RETURNING *;

-- name: ConfirmMfaFactor :one
-- The first valid code turns the factor on and seeds the recovery codes.
-- last_used_at is set to the matched TOTP step so that very first code is
-- already replay-protected.
UPDATE mfa_factors
SET confirmed_at = now(),
    recovery_code_hashes = sqlc.arg(recovery_code_hashes)::text[],
    last_used_at = sqlc.arg(last_used_at),
    updated_at = now()
WHERE user_id = $1 AND type = 'totp' AND confirmed_at IS NULL
RETURNING *;

-- name: TouchMfaFactorUsed :execrows
-- The anti-replay gate (data-dictionary §4.3): last_used_at holds the start
-- of the last accepted TOTP step, and only a strictly later step may pass.
-- Enforced in SQL so two concurrent verifications of the same code cannot
-- both win, whatever the callers do.
UPDATE mfa_factors
SET last_used_at = sqlc.arg(used_at), updated_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < sqlc.arg(used_at));

-- name: ConsumeMfaRecoveryCode :execrows
-- Single-use by construction: the matched hash is removed in the same
-- statement that accepts it.
UPDATE mfa_factors
SET recovery_code_hashes = array_remove(recovery_code_hashes, sqlc.arg(code_hash)::text),
    updated_at = now()
WHERE id = $1
  AND confirmed_at IS NOT NULL
  AND sqlc.arg(code_hash)::text = ANY (recovery_code_hashes);

-- name: ReplaceMfaRecoveryCodes :execrows
UPDATE mfa_factors
SET recovery_code_hashes = sqlc.arg(recovery_code_hashes)::text[], updated_at = now()
WHERE user_id = $1 AND type = 'totp' AND confirmed_at IS NOT NULL;

-- name: DeleteMfaFactorForUser :execrows
DELETE FROM mfa_factors WHERE user_id = $1 AND type = 'totp';

-- name: CreateMfaChallenge :exec
INSERT INTO mfa_challenges (token_hash, user_id, expires_at)
VALUES ($1, $2, $3);

-- name: GetMfaChallenge :one
-- Read without consuming: a mistyped code must not send the user back to the
-- password form — the account lockout is what bounds the guesses.
SELECT * FROM mfa_challenges WHERE token_hash = $1 AND expires_at > now();

-- name: ConsumeMfaChallenge :one
-- DELETE ... RETURNING on success only: two concurrent verifications of the
-- same challenge cannot both mint a session.
DELETE FROM mfa_challenges
WHERE token_hash = $1 AND expires_at > now()
RETURNING *;

-- name: PurgeExpiredMfaChallenges :execrows
DELETE FROM mfa_challenges WHERE expires_at < now();
